-- Create "credit_transactions" table
CREATE TABLE "credit_transactions" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "type" character varying NOT NULL, "action" character varying NOT NULL, "amount" double precision NOT NULL, "new_balance" double precision NOT NULL, "reference_id" character varying NULL, "description" text NULL, "metadata" jsonb NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "credittransaction_reference_id" to table: "credit_transactions"
CREATE INDEX "credittransaction_reference_id" ON "credit_transactions" ("reference_id");
-- Create index "credittransaction_tenant_id" to table: "credit_transactions"
CREATE INDEX "credittransaction_tenant_id" ON "credit_transactions" ("tenant_id");
-- Create index "credittransaction_type" to table: "credit_transactions"
CREATE INDEX "credittransaction_type" ON "credit_transactions" ("type");
-- Create "delivery_logs" table
CREATE TABLE "delivery_logs" ("id" uuid NOT NULL, "tenant_id" character varying NOT NULL, "template_id" character varying NOT NULL, "channel" character varying NOT NULL, "recipient" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'sent', "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "deliverylog_created_at" to table: "delivery_logs"
CREATE INDEX "deliverylog_created_at" ON "delivery_logs" ("created_at");
-- Create index "deliverylog_tenant_id" to table: "delivery_logs"
CREATE INDEX "deliverylog_tenant_id" ON "delivery_logs" ("tenant_id");
-- Create index "deliverylog_tenant_id_created_at" to table: "delivery_logs"
CREATE INDEX "deliverylog_tenant_id_created_at" ON "delivery_logs" ("tenant_id", "created_at");
-- Create "outbox_events" table
CREATE TABLE "outbox_events" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "aggregate_type" character varying NOT NULL, "aggregate_id" uuid NOT NULL, "event_type" character varying NOT NULL, "payload" jsonb NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "attempts" bigint NOT NULL DEFAULT 0, "last_attempt_at" timestamptz NULL, "published_at" timestamptz NULL, "error_message" character varying NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "outboxevent_aggregate_type_aggregate_id" to table: "outbox_events"
CREATE INDEX "outboxevent_aggregate_type_aggregate_id" ON "outbox_events" ("aggregate_type", "aggregate_id");
-- Create index "outboxevent_created_at" to table: "outbox_events"
CREATE INDEX "outboxevent_created_at" ON "outbox_events" ("created_at");
-- Create index "outboxevent_event_type" to table: "outbox_events"
CREATE INDEX "outboxevent_event_type" ON "outbox_events" ("event_type");
-- Create index "outboxevent_status" to table: "outbox_events"
CREATE INDEX "outboxevent_status" ON "outbox_events" ("status");
-- Create index "outboxevent_tenant_id" to table: "outbox_events"
CREATE INDEX "outboxevent_tenant_id" ON "outbox_events" ("tenant_id");
-- Create "platform_billings" table
CREATE TABLE "platform_billings" ("id" uuid NOT NULL, "cost_per_sms" double precision NOT NULL DEFAULT 1, "cost_per_whatsapp" double precision NOT NULL DEFAULT 2, "min_topup_amount" double precision NOT NULL DEFAULT 500, "treasury_gateway_id" uuid NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "provider_settings" table
CREATE TABLE "provider_settings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" character varying NOT NULL, "channel" character varying NULL, "provider" character varying NULL, "provider_type" character varying NULL, "provider_name" character varying NULL, "key" character varying NULL, "value" text NULL, "description" text NULL, "is_encrypted" boolean NOT NULL DEFAULT false, "is_platform" boolean NOT NULL DEFAULT false, "is_platform_managed" boolean NOT NULL DEFAULT false, "environment" character varying NOT NULL DEFAULT 'production', "is_secret" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "status" character varying NULL DEFAULT 'active', PRIMARY KEY ("id"));
-- Create index "providersetting_tenant_id_envi_4174d78779cdd3eabfc186faa75339aa" to table: "provider_settings"
CREATE INDEX "providersetting_tenant_id_envi_4174d78779cdd3eabfc186faa75339aa" ON "provider_settings" ("tenant_id", "environment", "provider_type", "provider_name", "key");
-- Create index "providersetting_tenant_id_environment_provider_type" to table: "provider_settings"
CREATE INDEX "providersetting_tenant_id_environment_provider_type" ON "provider_settings" ("tenant_id", "environment", "provider_type");
-- Create "tenant_brandings" table
CREATE TABLE "tenant_brandings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" character varying NOT NULL, "logo_url" character varying NULL, "primary_color" character varying NULL, "secondary_color" character varying NULL, "font_family" character varying NULL, "custom_css" text NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "tenant_brandings_tenant_id_key" to table: "tenant_brandings"
CREATE UNIQUE INDEX "tenant_brandings_tenant_id_key" ON "tenant_brandings" ("tenant_id");
-- Create index "tenantbranding_tenant_id" to table: "tenant_brandings"
CREATE UNIQUE INDEX "tenantbranding_tenant_id" ON "tenant_brandings" ("tenant_id");
-- Create "tenant_credits" table
CREATE TABLE "tenant_credits" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "type" character varying NOT NULL DEFAULT 'SMS', "balance" double precision NOT NULL DEFAULT 0, "rate" double precision NOT NULL DEFAULT 0, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "tenantcredit_tenant_id_type" to table: "tenant_credits"
CREATE UNIQUE INDEX "tenantcredit_tenant_id_type" ON "tenant_credits" ("tenant_id", "type");
