-- Create "rate_limit_configs" table
CREATE TABLE "rate_limit_configs" ("id" uuid NOT NULL, "service_name" character varying NOT NULL, "key_type" character varying NOT NULL, "endpoint_pattern" character varying NOT NULL DEFAULT '*', "requests_per_window" bigint NOT NULL DEFAULT 60, "window_seconds" bigint NOT NULL DEFAULT 60, "burst_multiplier" double precision NOT NULL DEFAULT 1.5, "is_active" boolean NOT NULL DEFAULT true, "description" character varying NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "ratelimitconfig_is_active" to table: "rate_limit_configs"
CREATE INDEX "ratelimitconfig_is_active" ON "rate_limit_configs" ("is_active");
-- Create index "ratelimitconfig_service_name" to table: "rate_limit_configs"
CREATE INDEX "ratelimitconfig_service_name" ON "rate_limit_configs" ("service_name");
-- Create index "ratelimitconfig_service_name_key_type_endpoint_pattern" to table: "rate_limit_configs"
CREATE UNIQUE INDEX "ratelimitconfig_service_name_key_type_endpoint_pattern" ON "rate_limit_configs" ("service_name", "key_type", "endpoint_pattern");
-- Create "service_configs" table
CREATE TABLE "service_configs" ("id" uuid NOT NULL, "tenant_id" uuid NULL, "config_key" character varying NOT NULL, "config_value" text NOT NULL, "config_type" character varying NOT NULL DEFAULT 'string', "description" character varying NULL, "is_secret" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "serviceconfig_config_key" to table: "service_configs"
CREATE INDEX "serviceconfig_config_key" ON "service_configs" ("config_key");
-- Create index "serviceconfig_tenant_id_config_key" to table: "service_configs"
CREATE UNIQUE INDEX "serviceconfig_tenant_id_config_key" ON "service_configs" ("tenant_id", "config_key");
-- Create "notification_permissions" table
CREATE TABLE "notification_permissions" ("id" uuid NOT NULL, "permission_code" character varying NOT NULL, "name" character varying NOT NULL, "module" character varying NOT NULL, "action" character varying NOT NULL, "resource" character varying NULL, "description" text NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "notification_permissions_permission_code_key" to table: "notification_permissions"
CREATE UNIQUE INDEX "notification_permissions_permission_code_key" ON "notification_permissions" ("permission_code");
-- Create index "notificationpermission_action" to table: "notification_permissions"
CREATE INDEX "notificationpermission_action" ON "notification_permissions" ("action");
-- Create index "notificationpermission_module" to table: "notification_permissions"
CREATE INDEX "notificationpermission_module" ON "notification_permissions" ("module");
-- Create index "notificationpermission_module_action" to table: "notification_permissions"
CREATE INDEX "notificationpermission_module_action" ON "notification_permissions" ("module", "action");
-- Create index "notificationpermission_permission_code" to table: "notification_permissions"
CREATE UNIQUE INDEX "notificationpermission_permission_code" ON "notification_permissions" ("permission_code");
-- Create "notification_roles" table
CREATE TABLE "notification_roles" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "role_code" character varying NOT NULL, "name" character varying NOT NULL, "description" text NULL, "is_system_role" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "notificationrole_is_system_role" to table: "notification_roles"
CREATE INDEX "notificationrole_is_system_role" ON "notification_roles" ("is_system_role");
-- Create index "notificationrole_tenant_id" to table: "notification_roles"
CREATE INDEX "notificationrole_tenant_id" ON "notification_roles" ("tenant_id");
-- Create index "notificationrole_tenant_id_role_code" to table: "notification_roles"
CREATE UNIQUE INDEX "notificationrole_tenant_id_role_code" ON "notification_roles" ("tenant_id", "role_code");
-- Create "notification_role_permissions" table
CREATE TABLE "notification_role_permissions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "notification_role_permissions__25f30a85c4498b27500d961afa210700" FOREIGN KEY ("permission_id") REFERENCES "notification_permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "notification_role_permissions_notification_roles_role" FOREIGN KEY ("role_id") REFERENCES "notification_roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "notificationrolepermission_permission_id" to table: "notification_role_permissions"
CREATE INDEX "notificationrolepermission_permission_id" ON "notification_role_permissions" ("permission_id");
-- Create index "notificationrolepermission_role_id" to table: "notification_role_permissions"
CREATE INDEX "notificationrolepermission_role_id" ON "notification_role_permissions" ("role_id");
-- Create index "notificationrolepermission_role_id_permission_id" to table: "notification_role_permissions"
CREATE UNIQUE INDEX "notificationrolepermission_role_id_permission_id" ON "notification_role_permissions" ("role_id", "permission_id");
-- Create "user_role_assignments" table
CREATE TABLE "user_role_assignments" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "assigned_by" uuid NOT NULL, "assigned_at" timestamptz NOT NULL, "expires_at" timestamptz NULL, "notification_role_user_assignments" uuid NULL, "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "user_role_assignments_notification_roles_role" FOREIGN KEY ("role_id") REFERENCES "notification_roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "user_role_assignments_notification_roles_user_assignments" FOREIGN KEY ("notification_role_user_assignments") REFERENCES "notification_roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "user_role_assignments_users_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "userroleassignment_expires_at" to table: "user_role_assignments"
CREATE INDEX "userroleassignment_expires_at" ON "user_role_assignments" ("expires_at");
-- Create index "userroleassignment_role_id" to table: "user_role_assignments"
CREATE INDEX "userroleassignment_role_id" ON "user_role_assignments" ("role_id");
-- Create index "userroleassignment_tenant_id" to table: "user_role_assignments"
CREATE INDEX "userroleassignment_tenant_id" ON "user_role_assignments" ("tenant_id");
-- Create index "userroleassignment_tenant_id_user_id_role_id" to table: "user_role_assignments"
CREATE UNIQUE INDEX "userroleassignment_tenant_id_user_id_role_id" ON "user_role_assignments" ("tenant_id", "user_id", "role_id");
-- Create index "userroleassignment_user_id" to table: "user_role_assignments"
CREATE INDEX "userroleassignment_user_id" ON "user_role_assignments" ("user_id");
