// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CreditTransactionsColumns holds the columns for the "credit_transactions" table.
	CreditTransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"SMS", "WHATSAPP"}},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"TOPUP", "DEDUCTION", "REFUND", "ADJUSTMENT"}},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "new_balance", Type: field.TypeFloat64},
		{Name: "reference_id", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CreditTransactionsTable holds the schema information for the "credit_transactions" table.
	CreditTransactionsTable = &schema.Table{
		Name:       "credit_transactions",
		Columns:    CreditTransactionsColumns,
		PrimaryKey: []*schema.Column{CreditTransactionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "credittransaction_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{CreditTransactionsColumns[1]},
			},
			{
				Name:    "credittransaction_type",
				Unique:  false,
				Columns: []*schema.Column{CreditTransactionsColumns[2]},
			},
			{
				Name:    "credittransaction_reference_id",
				Unique:  false,
				Columns: []*schema.Column{CreditTransactionsColumns[6]},
			},
		},
	}
	// DeliveryLogsColumns holds the columns for the "delivery_logs" table.
	DeliveryLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "template_id", Type: field.TypeString},
		{Name: "channel", Type: field.TypeString},
		{Name: "recipient", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "sent"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// DeliveryLogsTable holds the schema information for the "delivery_logs" table.
	DeliveryLogsTable = &schema.Table{
		Name:       "delivery_logs",
		Columns:    DeliveryLogsColumns,
		PrimaryKey: []*schema.Column{DeliveryLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "deliverylog_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DeliveryLogsColumns[1]},
			},
			{
				Name:    "deliverylog_created_at",
				Unique:  false,
				Columns: []*schema.Column{DeliveryLogsColumns[6]},
			},
			{
				Name:    "deliverylog_tenant_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{DeliveryLogsColumns[1], DeliveryLogsColumns[6]},
			},
		},
	}
	// NotificationPermissionsColumns holds the columns for the "notification_permissions" table.
	NotificationPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "permission_code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "module", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "resource", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
	}
	// NotificationPermissionsTable holds the schema information for the "notification_permissions" table.
	NotificationPermissionsTable = &schema.Table{
		Name:       "notification_permissions",
		Columns:    NotificationPermissionsColumns,
		PrimaryKey: []*schema.Column{NotificationPermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notificationpermission_permission_code",
				Unique:  true,
				Columns: []*schema.Column{NotificationPermissionsColumns[1]},
			},
			{
				Name:    "notificationpermission_module",
				Unique:  false,
				Columns: []*schema.Column{NotificationPermissionsColumns[3]},
			},
			{
				Name:    "notificationpermission_action",
				Unique:  false,
				Columns: []*schema.Column{NotificationPermissionsColumns[4]},
			},
			{
				Name:    "notificationpermission_module_action",
				Unique:  false,
				Columns: []*schema.Column{NotificationPermissionsColumns[3], NotificationPermissionsColumns[4]},
			},
		},
	}
	// NotificationRolesColumns holds the columns for the "notification_roles" table.
	NotificationRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "role_code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_system_role", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NotificationRolesTable holds the schema information for the "notification_roles" table.
	NotificationRolesTable = &schema.Table{
		Name:       "notification_roles",
		Columns:    NotificationRolesColumns,
		PrimaryKey: []*schema.Column{NotificationRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notificationrole_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationRolesColumns[1]},
			},
			{
				Name:    "notificationrole_tenant_id_role_code",
				Unique:  true,
				Columns: []*schema.Column{NotificationRolesColumns[1], NotificationRolesColumns[2]},
			},
			{
				Name:    "notificationrole_is_system_role",
				Unique:  false,
				Columns: []*schema.Column{NotificationRolesColumns[5]},
			},
		},
	}
	// NotificationRolePermissionsColumns holds the columns for the "notification_role_permissions" table.
	NotificationRolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role_id", Type: field.TypeUUID},
		{Name: "permission_id", Type: field.TypeUUID},
	}
	// NotificationRolePermissionsTable holds the schema information for the "notification_role_permissions" table.
	NotificationRolePermissionsTable = &schema.Table{
		Name:       "notification_role_permissions",
		Columns:    NotificationRolePermissionsColumns,
		PrimaryKey: []*schema.Column{NotificationRolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_role_permissions_notification_roles_role",
				Columns:    []*schema.Column{NotificationRolePermissionsColumns[1]},
				RefColumns: []*schema.Column{NotificationRolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "notification_role_permissions_notification_permissions_permission",
				Columns:    []*schema.Column{NotificationRolePermissionsColumns[2]},
				RefColumns: []*schema.Column{NotificationPermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notificationrolepermission_role_id_permission_id",
				Unique:  true,
				Columns: []*schema.Column{NotificationRolePermissionsColumns[1], NotificationRolePermissionsColumns[2]},
			},
			{
				Name:    "notificationrolepermission_role_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationRolePermissionsColumns[1]},
			},
			{
				Name:    "notificationrolepermission_permission_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationRolePermissionsColumns[2]},
			},
		},
	}
	// OutboxEventsColumns holds the columns for the "outbox_events" table.
	OutboxEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "aggregate_type", Type: field.TypeString},
		{Name: "aggregate_id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_attempt_at", Type: field.TypeTime, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OutboxEventsTable holds the schema information for the "outbox_events" table.
	OutboxEventsTable = &schema.Table{
		Name:       "outbox_events",
		Columns:    OutboxEventsColumns,
		PrimaryKey: []*schema.Column{OutboxEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "outboxevent_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OutboxEventsColumns[1]},
			},
			{
				Name:    "outboxevent_aggregate_type_aggregate_id",
				Unique:  false,
				Columns: []*schema.Column{OutboxEventsColumns[2], OutboxEventsColumns[3]},
			},
			{
				Name:    "outboxevent_event_type",
				Unique:  false,
				Columns: []*schema.Column{OutboxEventsColumns[4]},
			},
			{
				Name:    "outboxevent_status",
				Unique:  false,
				Columns: []*schema.Column{OutboxEventsColumns[6]},
			},
			{
				Name:    "outboxevent_created_at",
				Unique:  false,
				Columns: []*schema.Column{OutboxEventsColumns[11]},
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "module", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
	}
	// PlatformBillingsColumns holds the columns for the "platform_billings" table.
	PlatformBillingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "cost_per_sms", Type: field.TypeFloat64, Default: 1},
		{Name: "cost_per_whatsapp", Type: field.TypeFloat64, Default: 2},
		{Name: "min_topup_amount", Type: field.TypeFloat64, Default: 500},
		{Name: "treasury_gateway_id", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PlatformBillingsTable holds the schema information for the "platform_billings" table.
	PlatformBillingsTable = &schema.Table{
		Name:       "platform_billings",
		Columns:    PlatformBillingsColumns,
		PrimaryKey: []*schema.Column{PlatformBillingsColumns[0]},
	}
	// ProviderSettingsColumns holds the columns for the "provider_settings" table.
	ProviderSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "channel", Type: field.TypeString, Nullable: true},
		{Name: "provider", Type: field.TypeString, Nullable: true},
		{Name: "provider_type", Type: field.TypeString, Nullable: true},
		{Name: "provider_name", Type: field.TypeString, Nullable: true},
		{Name: "key", Type: field.TypeString, Nullable: true},
		{Name: "value", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_encrypted", Type: field.TypeBool, Default: false},
		{Name: "is_platform", Type: field.TypeBool, Default: false},
		{Name: "is_platform_managed", Type: field.TypeBool, Default: false},
		{Name: "environment", Type: field.TypeString, Default: "production"},
		{Name: "is_secret", Type: field.TypeBool, Default: false},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeString, Nullable: true, Default: "active"},
	}
	// ProviderSettingsTable holds the schema information for the "provider_settings" table.
	ProviderSettingsTable = &schema.Table{
		Name:       "provider_settings",
		Columns:    ProviderSettingsColumns,
		PrimaryKey: []*schema.Column{ProviderSettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "providersetting_tenant_id_environment_provider_type_provider_name_key",
				Unique:  false,
				Columns: []*schema.Column{ProviderSettingsColumns[1], ProviderSettingsColumns[12], ProviderSettingsColumns[4], ProviderSettingsColumns[5], ProviderSettingsColumns[6]},
			},
			{
				Name:    "providersetting_tenant_id_environment_provider_type",
				Unique:  false,
				Columns: []*schema.Column{ProviderSettingsColumns[1], ProviderSettingsColumns[12], ProviderSettingsColumns[4]},
			},
		},
	}
	// RateLimitConfigsColumns holds the columns for the "rate_limit_configs" table.
	RateLimitConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "service_name", Type: field.TypeString},
		{Name: "key_type", Type: field.TypeString},
		{Name: "endpoint_pattern", Type: field.TypeString, Default: "*"},
		{Name: "requests_per_window", Type: field.TypeInt, Default: 60},
		{Name: "window_seconds", Type: field.TypeInt, Default: 60},
		{Name: "burst_multiplier", Type: field.TypeFloat64, Default: 1.5},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RateLimitConfigsTable holds the schema information for the "rate_limit_configs" table.
	RateLimitConfigsTable = &schema.Table{
		Name:       "rate_limit_configs",
		Columns:    RateLimitConfigsColumns,
		PrimaryKey: []*schema.Column{RateLimitConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ratelimitconfig_service_name_key_type_endpoint_pattern",
				Unique:  true,
				Columns: []*schema.Column{RateLimitConfigsColumns[1], RateLimitConfigsColumns[2], RateLimitConfigsColumns[3]},
			},
			{
				Name:    "ratelimitconfig_service_name",
				Unique:  false,
				Columns: []*schema.Column{RateLimitConfigsColumns[1]},
			},
			{
				Name:    "ratelimitconfig_is_active",
				Unique:  false,
				Columns: []*schema.Column{RateLimitConfigsColumns[7]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "scope", Type: field.TypeString, Default: "tenant"},
		{Name: "system_role", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// ServiceConfigsColumns holds the columns for the "service_configs" table.
	ServiceConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID, Nullable: true},
		{Name: "config_key", Type: field.TypeString},
		{Name: "config_value", Type: field.TypeString, Size: 2147483647},
		{Name: "config_type", Type: field.TypeString, Default: "string"},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "is_secret", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ServiceConfigsTable holds the schema information for the "service_configs" table.
	ServiceConfigsTable = &schema.Table{
		Name:       "service_configs",
		Columns:    ServiceConfigsColumns,
		PrimaryKey: []*schema.Column{ServiceConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "serviceconfig_tenant_id_config_key",
				Unique:  true,
				Columns: []*schema.Column{ServiceConfigsColumns[1], ServiceConfigsColumns[2]},
			},
			{
				Name:    "serviceconfig_config_key",
				Unique:  false,
				Columns: []*schema.Column{ServiceConfigsColumns[2]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "contact_email", Type: field.TypeString, Nullable: true},
		{Name: "contact_phone", Type: field.TypeString, Nullable: true},
		{Name: "logo_url", Type: field.TypeString, Nullable: true},
		{Name: "website", Type: field.TypeString, Nullable: true},
		{Name: "country", Type: field.TypeString, Nullable: true, Default: "KE"},
		{Name: "timezone", Type: field.TypeString, Nullable: true, Default: "Africa/Nairobi"},
		{Name: "brand_colors", Type: field.TypeJSON, Nullable: true},
		{Name: "org_size", Type: field.TypeString, Nullable: true},
		{Name: "use_case", Type: field.TypeString, Nullable: true},
		{Name: "subscription_plan", Type: field.TypeString, Nullable: true},
		{Name: "subscription_status", Type: field.TypeString, Nullable: true},
		{Name: "subscription_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "subscription_id", Type: field.TypeString, Nullable: true},
		{Name: "tier_limits", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenant_slug",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[2]},
			},
			{
				Name:    "tenant_status",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[3]},
			},
		},
	}
	// TenantCreditsColumns holds the columns for the "tenant_credits" table.
	TenantCreditsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"SMS", "WHATSAPP"}, Default: "SMS"},
		{Name: "balance", Type: field.TypeFloat64, Default: 0},
		{Name: "rate", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantCreditsTable holds the schema information for the "tenant_credits" table.
	TenantCreditsTable = &schema.Table{
		Name:       "tenant_credits",
		Columns:    TenantCreditsColumns,
		PrimaryKey: []*schema.Column{TenantCreditsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenantcredit_tenant_id_type",
				Unique:  true,
				Columns: []*schema.Column{TenantCreditsColumns[1], TenantCreditsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "auth_service_user_id", Type: field.TypeUUID, Unique: true, Nullable: true},
		{Name: "email", Type: field.TypeString},
		{Name: "sync_status", Type: field.TypeString, Default: "pending"},
		{Name: "sync_at", Type: field.TypeTime, Nullable: true},
		{Name: "full_name", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "primary_role", Type: field.TypeString, Nullable: true},
		{Name: "locale", Type: field.TypeString, Default: "en"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUUID},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_tenants_users",
				Columns:    []*schema.Column{UsersColumns[14]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_tenant_id_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[14], UsersColumns[2]},
			},
			{
				Name:    "user_tenant_id_auth_service_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[14], UsersColumns[1]},
			},
			{
				Name:    "user_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[14], UsersColumns[7]},
			},
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
			{
				Name:    "user_sync_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
			{
				Name:    "user_auth_service_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[12]},
			},
		},
	}
	// UserRoleAssignmentsColumns holds the columns for the "user_role_assignments" table.
	UserRoleAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "assigned_by", Type: field.TypeUUID},
		{Name: "assigned_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "notification_role_user_assignments", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "role_id", Type: field.TypeUUID},
	}
	// UserRoleAssignmentsTable holds the schema information for the "user_role_assignments" table.
	UserRoleAssignmentsTable = &schema.Table{
		Name:       "user_role_assignments",
		Columns:    UserRoleAssignmentsColumns,
		PrimaryKey: []*schema.Column{UserRoleAssignmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_role_assignments_notification_roles_user_assignments",
				Columns:    []*schema.Column{UserRoleAssignmentsColumns[5]},
				RefColumns: []*schema.Column{NotificationRolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "user_role_assignments_users_user",
				Columns:    []*schema.Column{UserRoleAssignmentsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_role_assignments_notification_roles_role",
				Columns:    []*schema.Column{UserRoleAssignmentsColumns[7]},
				RefColumns: []*schema.Column{NotificationRolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userroleassignment_tenant_id_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRoleAssignmentsColumns[1], UserRoleAssignmentsColumns[6], UserRoleAssignmentsColumns[7]},
			},
			{
				Name:    "userroleassignment_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{UserRoleAssignmentsColumns[1]},
			},
			{
				Name:    "userroleassignment_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserRoleAssignmentsColumns[6]},
			},
			{
				Name:    "userroleassignment_role_id",
				Unique:  false,
				Columns: []*schema.Column{UserRoleAssignmentsColumns[7]},
			},
			{
				Name:    "userroleassignment_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserRoleAssignmentsColumns[4]},
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeString},
		{Name: "permission_id", Type: field.TypeUUID},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0], RolePermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_role_id",
				Columns:    []*schema.Column{RolePermissionsColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_permissions_permission_id",
				Columns:    []*schema.Column{RolePermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "role_id", Type: field.TypeString},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0], UserRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_user_id",
				Columns:    []*schema.Column{UserRolesColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_roles_role_id",
				Columns:    []*schema.Column{UserRolesColumns[1]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CreditTransactionsTable,
		DeliveryLogsTable,
		NotificationPermissionsTable,
		NotificationRolesTable,
		NotificationRolePermissionsTable,
		OutboxEventsTable,
		PermissionsTable,
		PlatformBillingsTable,
		ProviderSettingsTable,
		RateLimitConfigsTable,
		RolesTable,
		ServiceConfigsTable,
		TenantsTable,
		TenantCreditsTable,
		UsersTable,
		UserRoleAssignmentsTable,
		RolePermissionsTable,
		UserRolesTable,
	}
)

func init() {
	NotificationRolePermissionsTable.ForeignKeys[0].RefTable = NotificationRolesTable
	NotificationRolePermissionsTable.ForeignKeys[1].RefTable = NotificationPermissionsTable
	UsersTable.ForeignKeys[0].RefTable = TenantsTable
	UserRoleAssignmentsTable.ForeignKeys[0].RefTable = NotificationRolesTable
	UserRoleAssignmentsTable.ForeignKeys[1].RefTable = UsersTable
	UserRoleAssignmentsTable.ForeignKeys[2].RefTable = NotificationRolesTable
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolePermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
	UserRolesTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[1].RefTable = RolesTable
}
