// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/credittransaction"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// CreditTransactionUpdate is the builder for updating CreditTransaction entities.
type CreditTransactionUpdate struct {
	config
	hooks     []Hook
	mutation  *CreditTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CreditTransactionUpdate builder.
func (ctu *CreditTransactionUpdate) Where(ps ...predicate.CreditTransaction) *CreditTransactionUpdate {
	ctu.mutation.Where(ps...)
	return ctu
}

// SetTenantID sets the "tenant_id" field.
func (ctu *CreditTransactionUpdate) SetTenantID(u uuid.UUID) *CreditTransactionUpdate {
	ctu.mutation.SetTenantID(u)
	return ctu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (ctu *CreditTransactionUpdate) SetNillableTenantID(u *uuid.UUID) *CreditTransactionUpdate {
	if u != nil {
		ctu.SetTenantID(*u)
	}
	return ctu
}

// SetType sets the "type" field.
func (ctu *CreditTransactionUpdate) SetType(c credittransaction.Type) *CreditTransactionUpdate {
	ctu.mutation.SetType(c)
	return ctu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ctu *CreditTransactionUpdate) SetNillableType(c *credittransaction.Type) *CreditTransactionUpdate {
	if c != nil {
		ctu.SetType(*c)
	}
	return ctu
}

// SetAction sets the "action" field.
func (ctu *CreditTransactionUpdate) SetAction(c credittransaction.Action) *CreditTransactionUpdate {
	ctu.mutation.SetAction(c)
	return ctu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (ctu *CreditTransactionUpdate) SetNillableAction(c *credittransaction.Action) *CreditTransactionUpdate {
	if c != nil {
		ctu.SetAction(*c)
	}
	return ctu
}

// SetAmount sets the "amount" field.
func (ctu *CreditTransactionUpdate) SetAmount(f float64) *CreditTransactionUpdate {
	ctu.mutation.ResetAmount()
	ctu.mutation.SetAmount(f)
	return ctu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ctu *CreditTransactionUpdate) SetNillableAmount(f *float64) *CreditTransactionUpdate {
	if f != nil {
		ctu.SetAmount(*f)
	}
	return ctu
}

// AddAmount adds f to the "amount" field.
func (ctu *CreditTransactionUpdate) AddAmount(f float64) *CreditTransactionUpdate {
	ctu.mutation.AddAmount(f)
	return ctu
}

// SetNewBalance sets the "new_balance" field.
func (ctu *CreditTransactionUpdate) SetNewBalance(f float64) *CreditTransactionUpdate {
	ctu.mutation.ResetNewBalance()
	ctu.mutation.SetNewBalance(f)
	return ctu
}

// SetNillableNewBalance sets the "new_balance" field if the given value is not nil.
func (ctu *CreditTransactionUpdate) SetNillableNewBalance(f *float64) *CreditTransactionUpdate {
	if f != nil {
		ctu.SetNewBalance(*f)
	}
	return ctu
}

// AddNewBalance adds f to the "new_balance" field.
func (ctu *CreditTransactionUpdate) AddNewBalance(f float64) *CreditTransactionUpdate {
	ctu.mutation.AddNewBalance(f)
	return ctu
}

// SetReferenceID sets the "reference_id" field.
func (ctu *CreditTransactionUpdate) SetReferenceID(s string) *CreditTransactionUpdate {
	ctu.mutation.SetReferenceID(s)
	return ctu
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (ctu *CreditTransactionUpdate) SetNillableReferenceID(s *string) *CreditTransactionUpdate {
	if s != nil {
		ctu.SetReferenceID(*s)
	}
	return ctu
}

// ClearReferenceID clears the value of the "reference_id" field.
func (ctu *CreditTransactionUpdate) ClearReferenceID() *CreditTransactionUpdate {
	ctu.mutation.ClearReferenceID()
	return ctu
}

// SetDescription sets the "description" field.
func (ctu *CreditTransactionUpdate) SetDescription(s string) *CreditTransactionUpdate {
	ctu.mutation.SetDescription(s)
	return ctu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ctu *CreditTransactionUpdate) SetNillableDescription(s *string) *CreditTransactionUpdate {
	if s != nil {
		ctu.SetDescription(*s)
	}
	return ctu
}

// ClearDescription clears the value of the "description" field.
func (ctu *CreditTransactionUpdate) ClearDescription() *CreditTransactionUpdate {
	ctu.mutation.ClearDescription()
	return ctu
}

// SetMetadata sets the "metadata" field.
func (ctu *CreditTransactionUpdate) SetMetadata(m map[string]interface{}) *CreditTransactionUpdate {
	ctu.mutation.SetMetadata(m)
	return ctu
}

// Mutation returns the CreditTransactionMutation object of the builder.
func (ctu *CreditTransactionUpdate) Mutation() *CreditTransactionMutation {
	return ctu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ctu *CreditTransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ctu.sqlSave, ctu.mutation, ctu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ctu *CreditTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := ctu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ctu *CreditTransactionUpdate) Exec(ctx context.Context) error {
	_, err := ctu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctu *CreditTransactionUpdate) ExecX(ctx context.Context) {
	if err := ctu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ctu *CreditTransactionUpdate) check() error {
	if v, ok := ctu.mutation.GetType(); ok {
		if err := credittransaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CreditTransaction.type": %w`, err)}
		}
	}
	if v, ok := ctu.mutation.Action(); ok {
		if err := credittransaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "CreditTransaction.action": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ctu *CreditTransactionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CreditTransactionUpdate {
	ctu.modifiers = append(ctu.modifiers, modifiers...)
	return ctu
}

func (ctu *CreditTransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ctu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(credittransaction.Table, credittransaction.Columns, sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeUUID))
	if ps := ctu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ctu.mutation.TenantID(); ok {
		_spec.SetField(credittransaction.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := ctu.mutation.GetType(); ok {
		_spec.SetField(credittransaction.FieldType, field.TypeEnum, value)
	}
	if value, ok := ctu.mutation.Action(); ok {
		_spec.SetField(credittransaction.FieldAction, field.TypeEnum, value)
	}
	if value, ok := ctu.mutation.Amount(); ok {
		_spec.SetField(credittransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := ctu.mutation.AddedAmount(); ok {
		_spec.AddField(credittransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := ctu.mutation.NewBalance(); ok {
		_spec.SetField(credittransaction.FieldNewBalance, field.TypeFloat64, value)
	}
	if value, ok := ctu.mutation.AddedNewBalance(); ok {
		_spec.AddField(credittransaction.FieldNewBalance, field.TypeFloat64, value)
	}
	if value, ok := ctu.mutation.ReferenceID(); ok {
		_spec.SetField(credittransaction.FieldReferenceID, field.TypeString, value)
	}
	if ctu.mutation.ReferenceIDCleared() {
		_spec.ClearField(credittransaction.FieldReferenceID, field.TypeString)
	}
	if value, ok := ctu.mutation.Description(); ok {
		_spec.SetField(credittransaction.FieldDescription, field.TypeString, value)
	}
	if ctu.mutation.DescriptionCleared() {
		_spec.ClearField(credittransaction.FieldDescription, field.TypeString)
	}
	if value, ok := ctu.mutation.Metadata(); ok {
		_spec.SetField(credittransaction.FieldMetadata, field.TypeJSON, value)
	}
	_spec.AddModifiers(ctu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, ctu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credittransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ctu.mutation.done = true
	return n, nil
}

// CreditTransactionUpdateOne is the builder for updating a single CreditTransaction entity.
type CreditTransactionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CreditTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTenantID sets the "tenant_id" field.
func (ctuo *CreditTransactionUpdateOne) SetTenantID(u uuid.UUID) *CreditTransactionUpdateOne {
	ctuo.mutation.SetTenantID(u)
	return ctuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (ctuo *CreditTransactionUpdateOne) SetNillableTenantID(u *uuid.UUID) *CreditTransactionUpdateOne {
	if u != nil {
		ctuo.SetTenantID(*u)
	}
	return ctuo
}

// SetType sets the "type" field.
func (ctuo *CreditTransactionUpdateOne) SetType(c credittransaction.Type) *CreditTransactionUpdateOne {
	ctuo.mutation.SetType(c)
	return ctuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ctuo *CreditTransactionUpdateOne) SetNillableType(c *credittransaction.Type) *CreditTransactionUpdateOne {
	if c != nil {
		ctuo.SetType(*c)
	}
	return ctuo
}

// SetAction sets the "action" field.
func (ctuo *CreditTransactionUpdateOne) SetAction(c credittransaction.Action) *CreditTransactionUpdateOne {
	ctuo.mutation.SetAction(c)
	return ctuo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (ctuo *CreditTransactionUpdateOne) SetNillableAction(c *credittransaction.Action) *CreditTransactionUpdateOne {
	if c != nil {
		ctuo.SetAction(*c)
	}
	return ctuo
}

// SetAmount sets the "amount" field.
func (ctuo *CreditTransactionUpdateOne) SetAmount(f float64) *CreditTransactionUpdateOne {
	ctuo.mutation.ResetAmount()
	ctuo.mutation.SetAmount(f)
	return ctuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ctuo *CreditTransactionUpdateOne) SetNillableAmount(f *float64) *CreditTransactionUpdateOne {
	if f != nil {
		ctuo.SetAmount(*f)
	}
	return ctuo
}

// AddAmount adds f to the "amount" field.
func (ctuo *CreditTransactionUpdateOne) AddAmount(f float64) *CreditTransactionUpdateOne {
	ctuo.mutation.AddAmount(f)
	return ctuo
}

// SetNewBalance sets the "new_balance" field.
func (ctuo *CreditTransactionUpdateOne) SetNewBalance(f float64) *CreditTransactionUpdateOne {
	ctuo.mutation.ResetNewBalance()
	ctuo.mutation.SetNewBalance(f)
	return ctuo
}

// SetNillableNewBalance sets the "new_balance" field if the given value is not nil.
func (ctuo *CreditTransactionUpdateOne) SetNillableNewBalance(f *float64) *CreditTransactionUpdateOne {
	if f != nil {
		ctuo.SetNewBalance(*f)
	}
	return ctuo
}

// AddNewBalance adds f to the "new_balance" field.
func (ctuo *CreditTransactionUpdateOne) AddNewBalance(f float64) *CreditTransactionUpdateOne {
	ctuo.mutation.AddNewBalance(f)
	return ctuo
}

// SetReferenceID sets the "reference_id" field.
func (ctuo *CreditTransactionUpdateOne) SetReferenceID(s string) *CreditTransactionUpdateOne {
	ctuo.mutation.SetReferenceID(s)
	return ctuo
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (ctuo *CreditTransactionUpdateOne) SetNillableReferenceID(s *string) *CreditTransactionUpdateOne {
	if s != nil {
		ctuo.SetReferenceID(*s)
	}
	return ctuo
}

// ClearReferenceID clears the value of the "reference_id" field.
func (ctuo *CreditTransactionUpdateOne) ClearReferenceID() *CreditTransactionUpdateOne {
	ctuo.mutation.ClearReferenceID()
	return ctuo
}

// SetDescription sets the "description" field.
func (ctuo *CreditTransactionUpdateOne) SetDescription(s string) *CreditTransactionUpdateOne {
	ctuo.mutation.SetDescription(s)
	return ctuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ctuo *CreditTransactionUpdateOne) SetNillableDescription(s *string) *CreditTransactionUpdateOne {
	if s != nil {
		ctuo.SetDescription(*s)
	}
	return ctuo
}

// ClearDescription clears the value of the "description" field.
func (ctuo *CreditTransactionUpdateOne) ClearDescription() *CreditTransactionUpdateOne {
	ctuo.mutation.ClearDescription()
	return ctuo
}

// SetMetadata sets the "metadata" field.
func (ctuo *CreditTransactionUpdateOne) SetMetadata(m map[string]interface{}) *CreditTransactionUpdateOne {
	ctuo.mutation.SetMetadata(m)
	return ctuo
}

// Mutation returns the CreditTransactionMutation object of the builder.
func (ctuo *CreditTransactionUpdateOne) Mutation() *CreditTransactionMutation {
	return ctuo.mutation
}

// Where appends a list predicates to the CreditTransactionUpdate builder.
func (ctuo *CreditTransactionUpdateOne) Where(ps ...predicate.CreditTransaction) *CreditTransactionUpdateOne {
	ctuo.mutation.Where(ps...)
	return ctuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ctuo *CreditTransactionUpdateOne) Select(field string, fields ...string) *CreditTransactionUpdateOne {
	ctuo.fields = append([]string{field}, fields...)
	return ctuo
}

// Save executes the query and returns the updated CreditTransaction entity.
func (ctuo *CreditTransactionUpdateOne) Save(ctx context.Context) (*CreditTransaction, error) {
	return withHooks(ctx, ctuo.sqlSave, ctuo.mutation, ctuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ctuo *CreditTransactionUpdateOne) SaveX(ctx context.Context) *CreditTransaction {
	node, err := ctuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ctuo *CreditTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := ctuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctuo *CreditTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := ctuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ctuo *CreditTransactionUpdateOne) check() error {
	if v, ok := ctuo.mutation.GetType(); ok {
		if err := credittransaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CreditTransaction.type": %w`, err)}
		}
	}
	if v, ok := ctuo.mutation.Action(); ok {
		if err := credittransaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "CreditTransaction.action": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ctuo *CreditTransactionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CreditTransactionUpdateOne {
	ctuo.modifiers = append(ctuo.modifiers, modifiers...)
	return ctuo
}

func (ctuo *CreditTransactionUpdateOne) sqlSave(ctx context.Context) (_node *CreditTransaction, err error) {
	if err := ctuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(credittransaction.Table, credittransaction.Columns, sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeUUID))
	id, ok := ctuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreditTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ctuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credittransaction.FieldID)
		for _, f := range fields {
			if !credittransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credittransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ctuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ctuo.mutation.TenantID(); ok {
		_spec.SetField(credittransaction.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := ctuo.mutation.GetType(); ok {
		_spec.SetField(credittransaction.FieldType, field.TypeEnum, value)
	}
	if value, ok := ctuo.mutation.Action(); ok {
		_spec.SetField(credittransaction.FieldAction, field.TypeEnum, value)
	}
	if value, ok := ctuo.mutation.Amount(); ok {
		_spec.SetField(credittransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := ctuo.mutation.AddedAmount(); ok {
		_spec.AddField(credittransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := ctuo.mutation.NewBalance(); ok {
		_spec.SetField(credittransaction.FieldNewBalance, field.TypeFloat64, value)
	}
	if value, ok := ctuo.mutation.AddedNewBalance(); ok {
		_spec.AddField(credittransaction.FieldNewBalance, field.TypeFloat64, value)
	}
	if value, ok := ctuo.mutation.ReferenceID(); ok {
		_spec.SetField(credittransaction.FieldReferenceID, field.TypeString, value)
	}
	if ctuo.mutation.ReferenceIDCleared() {
		_spec.ClearField(credittransaction.FieldReferenceID, field.TypeString)
	}
	if value, ok := ctuo.mutation.Description(); ok {
		_spec.SetField(credittransaction.FieldDescription, field.TypeString, value)
	}
	if ctuo.mutation.DescriptionCleared() {
		_spec.ClearField(credittransaction.FieldDescription, field.TypeString)
	}
	if value, ok := ctuo.mutation.Metadata(); ok {
		_spec.SetField(credittransaction.FieldMetadata, field.TypeJSON, value)
	}
	_spec.AddModifiers(ctuo.modifiers...)
	_node = &CreditTransaction{config: ctuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ctuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credittransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ctuo.mutation.done = true
	return _node, nil
}
