// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/notifications-api/internal/ent/deliverylog"
	"github.com/google/uuid"
)

// DeliveryLog is the model entity for the DeliveryLog schema.
type DeliveryLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// Template identifier (e.g. order_confirmation)
	TemplateID string `json:"template_id,omitempty"`
	// email, sms, push
	Channel string `json:"channel,omitempty"`
	// Recipient holds the value of the "recipient" field.
	Recipient string `json:"recipient,omitempty"`
	// sent, delivered, failed
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeliveryLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deliverylog.FieldTenantID, deliverylog.FieldTemplateID, deliverylog.FieldChannel, deliverylog.FieldRecipient, deliverylog.FieldStatus:
			values[i] = new(sql.NullString)
		case deliverylog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case deliverylog.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeliveryLog fields.
func (dl *DeliveryLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deliverylog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				dl.ID = *value
			}
		case deliverylog.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				dl.TenantID = value.String
			}
		case deliverylog.FieldTemplateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				dl.TemplateID = value.String
			}
		case deliverylog.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				dl.Channel = value.String
			}
		case deliverylog.FieldRecipient:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient", values[i])
			} else if value.Valid {
				dl.Recipient = value.String
			}
		case deliverylog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				dl.Status = value.String
			}
		case deliverylog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				dl.CreatedAt = value.Time
			}
		default:
			dl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeliveryLog.
// This includes values selected through modifiers, order, etc.
func (dl *DeliveryLog) Value(name string) (ent.Value, error) {
	return dl.selectValues.Get(name)
}

// Update returns a builder for updating this DeliveryLog.
// Note that you need to call DeliveryLog.Unwrap() before calling this method if this DeliveryLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (dl *DeliveryLog) Update() *DeliveryLogUpdateOne {
	return NewDeliveryLogClient(dl.config).UpdateOne(dl)
}

// Unwrap unwraps the DeliveryLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dl *DeliveryLog) Unwrap() *DeliveryLog {
	_tx, ok := dl.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeliveryLog is not a transactional entity")
	}
	dl.config.driver = _tx.drv
	return dl
}

// String implements the fmt.Stringer.
func (dl *DeliveryLog) String() string {
	var builder strings.Builder
	builder.WriteString("DeliveryLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dl.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(dl.TenantID)
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(dl.TemplateID)
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(dl.Channel)
	builder.WriteString(", ")
	builder.WriteString("recipient=")
	builder.WriteString(dl.Recipient)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(dl.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(dl.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeliveryLogs is a parsable slice of DeliveryLog.
type DeliveryLogs []*DeliveryLog
