// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/deliverylog"
	"github.com/google/uuid"
)

// DeliveryLogCreate is the builder for creating a DeliveryLog entity.
type DeliveryLogCreate struct {
	config
	mutation *DeliveryLogMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (dlc *DeliveryLogCreate) SetTenantID(s string) *DeliveryLogCreate {
	dlc.mutation.SetTenantID(s)
	return dlc
}

// SetTemplateID sets the "template_id" field.
func (dlc *DeliveryLogCreate) SetTemplateID(s string) *DeliveryLogCreate {
	dlc.mutation.SetTemplateID(s)
	return dlc
}

// SetChannel sets the "channel" field.
func (dlc *DeliveryLogCreate) SetChannel(s string) *DeliveryLogCreate {
	dlc.mutation.SetChannel(s)
	return dlc
}

// SetRecipient sets the "recipient" field.
func (dlc *DeliveryLogCreate) SetRecipient(s string) *DeliveryLogCreate {
	dlc.mutation.SetRecipient(s)
	return dlc
}

// SetStatus sets the "status" field.
func (dlc *DeliveryLogCreate) SetStatus(s string) *DeliveryLogCreate {
	dlc.mutation.SetStatus(s)
	return dlc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dlc *DeliveryLogCreate) SetNillableStatus(s *string) *DeliveryLogCreate {
	if s != nil {
		dlc.SetStatus(*s)
	}
	return dlc
}

// SetCreatedAt sets the "created_at" field.
func (dlc *DeliveryLogCreate) SetCreatedAt(t time.Time) *DeliveryLogCreate {
	dlc.mutation.SetCreatedAt(t)
	return dlc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dlc *DeliveryLogCreate) SetNillableCreatedAt(t *time.Time) *DeliveryLogCreate {
	if t != nil {
		dlc.SetCreatedAt(*t)
	}
	return dlc
}

// SetID sets the "id" field.
func (dlc *DeliveryLogCreate) SetID(u uuid.UUID) *DeliveryLogCreate {
	dlc.mutation.SetID(u)
	return dlc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dlc *DeliveryLogCreate) SetNillableID(u *uuid.UUID) *DeliveryLogCreate {
	if u != nil {
		dlc.SetID(*u)
	}
	return dlc
}

// Mutation returns the DeliveryLogMutation object of the builder.
func (dlc *DeliveryLogCreate) Mutation() *DeliveryLogMutation {
	return dlc.mutation
}

// Save creates the DeliveryLog in the database.
func (dlc *DeliveryLogCreate) Save(ctx context.Context) (*DeliveryLog, error) {
	dlc.defaults()
	return withHooks(ctx, dlc.sqlSave, dlc.mutation, dlc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dlc *DeliveryLogCreate) SaveX(ctx context.Context) *DeliveryLog {
	v, err := dlc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dlc *DeliveryLogCreate) Exec(ctx context.Context) error {
	_, err := dlc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dlc *DeliveryLogCreate) ExecX(ctx context.Context) {
	if err := dlc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dlc *DeliveryLogCreate) defaults() {
	if _, ok := dlc.mutation.Status(); !ok {
		v := deliverylog.DefaultStatus
		dlc.mutation.SetStatus(v)
	}
	if _, ok := dlc.mutation.CreatedAt(); !ok {
		v := deliverylog.DefaultCreatedAt()
		dlc.mutation.SetCreatedAt(v)
	}
	if _, ok := dlc.mutation.ID(); !ok {
		v := deliverylog.DefaultID()
		dlc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dlc *DeliveryLogCreate) check() error {
	if _, ok := dlc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "DeliveryLog.tenant_id"`)}
	}
	if v, ok := dlc.mutation.TenantID(); ok {
		if err := deliverylog.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.tenant_id": %w`, err)}
		}
	}
	if _, ok := dlc.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "DeliveryLog.template_id"`)}
	}
	if v, ok := dlc.mutation.TemplateID(); ok {
		if err := deliverylog.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.template_id": %w`, err)}
		}
	}
	if _, ok := dlc.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "DeliveryLog.channel"`)}
	}
	if v, ok := dlc.mutation.Channel(); ok {
		if err := deliverylog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.channel": %w`, err)}
		}
	}
	if _, ok := dlc.mutation.Recipient(); !ok {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required field "DeliveryLog.recipient"`)}
	}
	if v, ok := dlc.mutation.Recipient(); ok {
		if err := deliverylog.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.recipient": %w`, err)}
		}
	}
	if _, ok := dlc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DeliveryLog.status"`)}
	}
	if _, ok := dlc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeliveryLog.created_at"`)}
	}
	return nil
}

func (dlc *DeliveryLogCreate) sqlSave(ctx context.Context) (*DeliveryLog, error) {
	if err := dlc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dlc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dlc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dlc.mutation.id = &_node.ID
	dlc.mutation.done = true
	return _node, nil
}

func (dlc *DeliveryLogCreate) createSpec() (*DeliveryLog, *sqlgraph.CreateSpec) {
	var (
		_node = &DeliveryLog{config: dlc.config}
		_spec = sqlgraph.NewCreateSpec(deliverylog.Table, sqlgraph.NewFieldSpec(deliverylog.FieldID, field.TypeUUID))
	)
	if id, ok := dlc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dlc.mutation.TenantID(); ok {
		_spec.SetField(deliverylog.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := dlc.mutation.TemplateID(); ok {
		_spec.SetField(deliverylog.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = value
	}
	if value, ok := dlc.mutation.Channel(); ok {
		_spec.SetField(deliverylog.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := dlc.mutation.Recipient(); ok {
		_spec.SetField(deliverylog.FieldRecipient, field.TypeString, value)
		_node.Recipient = value
	}
	if value, ok := dlc.mutation.Status(); ok {
		_spec.SetField(deliverylog.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := dlc.mutation.CreatedAt(); ok {
		_spec.SetField(deliverylog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DeliveryLogCreateBulk is the builder for creating many DeliveryLog entities in bulk.
type DeliveryLogCreateBulk struct {
	config
	err      error
	builders []*DeliveryLogCreate
}

// Save creates the DeliveryLog entities in the database.
func (dlcb *DeliveryLogCreateBulk) Save(ctx context.Context) ([]*DeliveryLog, error) {
	if dlcb.err != nil {
		return nil, dlcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dlcb.builders))
	nodes := make([]*DeliveryLog, len(dlcb.builders))
	mutators := make([]Mutator, len(dlcb.builders))
	for i := range dlcb.builders {
		func(i int, root context.Context) {
			builder := dlcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeliveryLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dlcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dlcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dlcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dlcb *DeliveryLogCreateBulk) SaveX(ctx context.Context) []*DeliveryLog {
	v, err := dlcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dlcb *DeliveryLogCreateBulk) Exec(ctx context.Context) error {
	_, err := dlcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dlcb *DeliveryLogCreateBulk) ExecX(ctx context.Context) {
	if err := dlcb.Exec(ctx); err != nil {
		panic(err)
	}
}
