// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/deliverylog"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
)

// DeliveryLogUpdate is the builder for updating DeliveryLog entities.
type DeliveryLogUpdate struct {
	config
	hooks     []Hook
	mutation  *DeliveryLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeliveryLogUpdate builder.
func (dlu *DeliveryLogUpdate) Where(ps ...predicate.DeliveryLog) *DeliveryLogUpdate {
	dlu.mutation.Where(ps...)
	return dlu
}

// SetTenantID sets the "tenant_id" field.
func (dlu *DeliveryLogUpdate) SetTenantID(s string) *DeliveryLogUpdate {
	dlu.mutation.SetTenantID(s)
	return dlu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (dlu *DeliveryLogUpdate) SetNillableTenantID(s *string) *DeliveryLogUpdate {
	if s != nil {
		dlu.SetTenantID(*s)
	}
	return dlu
}

// SetTemplateID sets the "template_id" field.
func (dlu *DeliveryLogUpdate) SetTemplateID(s string) *DeliveryLogUpdate {
	dlu.mutation.SetTemplateID(s)
	return dlu
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (dlu *DeliveryLogUpdate) SetNillableTemplateID(s *string) *DeliveryLogUpdate {
	if s != nil {
		dlu.SetTemplateID(*s)
	}
	return dlu
}

// SetChannel sets the "channel" field.
func (dlu *DeliveryLogUpdate) SetChannel(s string) *DeliveryLogUpdate {
	dlu.mutation.SetChannel(s)
	return dlu
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (dlu *DeliveryLogUpdate) SetNillableChannel(s *string) *DeliveryLogUpdate {
	if s != nil {
		dlu.SetChannel(*s)
	}
	return dlu
}

// SetRecipient sets the "recipient" field.
func (dlu *DeliveryLogUpdate) SetRecipient(s string) *DeliveryLogUpdate {
	dlu.mutation.SetRecipient(s)
	return dlu
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (dlu *DeliveryLogUpdate) SetNillableRecipient(s *string) *DeliveryLogUpdate {
	if s != nil {
		dlu.SetRecipient(*s)
	}
	return dlu
}

// SetStatus sets the "status" field.
func (dlu *DeliveryLogUpdate) SetStatus(s string) *DeliveryLogUpdate {
	dlu.mutation.SetStatus(s)
	return dlu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dlu *DeliveryLogUpdate) SetNillableStatus(s *string) *DeliveryLogUpdate {
	if s != nil {
		dlu.SetStatus(*s)
	}
	return dlu
}

// Mutation returns the DeliveryLogMutation object of the builder.
func (dlu *DeliveryLogUpdate) Mutation() *DeliveryLogMutation {
	return dlu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dlu *DeliveryLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, dlu.sqlSave, dlu.mutation, dlu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dlu *DeliveryLogUpdate) SaveX(ctx context.Context) int {
	affected, err := dlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dlu *DeliveryLogUpdate) Exec(ctx context.Context) error {
	_, err := dlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dlu *DeliveryLogUpdate) ExecX(ctx context.Context) {
	if err := dlu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dlu *DeliveryLogUpdate) check() error {
	if v, ok := dlu.mutation.TenantID(); ok {
		if err := deliverylog.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.tenant_id": %w`, err)}
		}
	}
	if v, ok := dlu.mutation.TemplateID(); ok {
		if err := deliverylog.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.template_id": %w`, err)}
		}
	}
	if v, ok := dlu.mutation.Channel(); ok {
		if err := deliverylog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.channel": %w`, err)}
		}
	}
	if v, ok := dlu.mutation.Recipient(); ok {
		if err := deliverylog.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.recipient": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (dlu *DeliveryLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeliveryLogUpdate {
	dlu.modifiers = append(dlu.modifiers, modifiers...)
	return dlu
}

func (dlu *DeliveryLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dlu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(deliverylog.Table, deliverylog.Columns, sqlgraph.NewFieldSpec(deliverylog.FieldID, field.TypeUUID))
	if ps := dlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dlu.mutation.TenantID(); ok {
		_spec.SetField(deliverylog.FieldTenantID, field.TypeString, value)
	}
	if value, ok := dlu.mutation.TemplateID(); ok {
		_spec.SetField(deliverylog.FieldTemplateID, field.TypeString, value)
	}
	if value, ok := dlu.mutation.Channel(); ok {
		_spec.SetField(deliverylog.FieldChannel, field.TypeString, value)
	}
	if value, ok := dlu.mutation.Recipient(); ok {
		_spec.SetField(deliverylog.FieldRecipient, field.TypeString, value)
	}
	if value, ok := dlu.mutation.Status(); ok {
		_spec.SetField(deliverylog.FieldStatus, field.TypeString, value)
	}
	_spec.AddModifiers(dlu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, dlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deliverylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dlu.mutation.done = true
	return n, nil
}

// DeliveryLogUpdateOne is the builder for updating a single DeliveryLog entity.
type DeliveryLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeliveryLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTenantID sets the "tenant_id" field.
func (dluo *DeliveryLogUpdateOne) SetTenantID(s string) *DeliveryLogUpdateOne {
	dluo.mutation.SetTenantID(s)
	return dluo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (dluo *DeliveryLogUpdateOne) SetNillableTenantID(s *string) *DeliveryLogUpdateOne {
	if s != nil {
		dluo.SetTenantID(*s)
	}
	return dluo
}

// SetTemplateID sets the "template_id" field.
func (dluo *DeliveryLogUpdateOne) SetTemplateID(s string) *DeliveryLogUpdateOne {
	dluo.mutation.SetTemplateID(s)
	return dluo
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (dluo *DeliveryLogUpdateOne) SetNillableTemplateID(s *string) *DeliveryLogUpdateOne {
	if s != nil {
		dluo.SetTemplateID(*s)
	}
	return dluo
}

// SetChannel sets the "channel" field.
func (dluo *DeliveryLogUpdateOne) SetChannel(s string) *DeliveryLogUpdateOne {
	dluo.mutation.SetChannel(s)
	return dluo
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (dluo *DeliveryLogUpdateOne) SetNillableChannel(s *string) *DeliveryLogUpdateOne {
	if s != nil {
		dluo.SetChannel(*s)
	}
	return dluo
}

// SetRecipient sets the "recipient" field.
func (dluo *DeliveryLogUpdateOne) SetRecipient(s string) *DeliveryLogUpdateOne {
	dluo.mutation.SetRecipient(s)
	return dluo
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (dluo *DeliveryLogUpdateOne) SetNillableRecipient(s *string) *DeliveryLogUpdateOne {
	if s != nil {
		dluo.SetRecipient(*s)
	}
	return dluo
}

// SetStatus sets the "status" field.
func (dluo *DeliveryLogUpdateOne) SetStatus(s string) *DeliveryLogUpdateOne {
	dluo.mutation.SetStatus(s)
	return dluo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (dluo *DeliveryLogUpdateOne) SetNillableStatus(s *string) *DeliveryLogUpdateOne {
	if s != nil {
		dluo.SetStatus(*s)
	}
	return dluo
}

// Mutation returns the DeliveryLogMutation object of the builder.
func (dluo *DeliveryLogUpdateOne) Mutation() *DeliveryLogMutation {
	return dluo.mutation
}

// Where appends a list predicates to the DeliveryLogUpdate builder.
func (dluo *DeliveryLogUpdateOne) Where(ps ...predicate.DeliveryLog) *DeliveryLogUpdateOne {
	dluo.mutation.Where(ps...)
	return dluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dluo *DeliveryLogUpdateOne) Select(field string, fields ...string) *DeliveryLogUpdateOne {
	dluo.fields = append([]string{field}, fields...)
	return dluo
}

// Save executes the query and returns the updated DeliveryLog entity.
func (dluo *DeliveryLogUpdateOne) Save(ctx context.Context) (*DeliveryLog, error) {
	return withHooks(ctx, dluo.sqlSave, dluo.mutation, dluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dluo *DeliveryLogUpdateOne) SaveX(ctx context.Context) *DeliveryLog {
	node, err := dluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dluo *DeliveryLogUpdateOne) Exec(ctx context.Context) error {
	_, err := dluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dluo *DeliveryLogUpdateOne) ExecX(ctx context.Context) {
	if err := dluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dluo *DeliveryLogUpdateOne) check() error {
	if v, ok := dluo.mutation.TenantID(); ok {
		if err := deliverylog.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.tenant_id": %w`, err)}
		}
	}
	if v, ok := dluo.mutation.TemplateID(); ok {
		if err := deliverylog.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.template_id": %w`, err)}
		}
	}
	if v, ok := dluo.mutation.Channel(); ok {
		if err := deliverylog.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.channel": %w`, err)}
		}
	}
	if v, ok := dluo.mutation.Recipient(); ok {
		if err := deliverylog.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "DeliveryLog.recipient": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (dluo *DeliveryLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeliveryLogUpdateOne {
	dluo.modifiers = append(dluo.modifiers, modifiers...)
	return dluo
}

func (dluo *DeliveryLogUpdateOne) sqlSave(ctx context.Context) (_node *DeliveryLog, err error) {
	if err := dluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deliverylog.Table, deliverylog.Columns, sqlgraph.NewFieldSpec(deliverylog.FieldID, field.TypeUUID))
	id, ok := dluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeliveryLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deliverylog.FieldID)
		for _, f := range fields {
			if !deliverylog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deliverylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dluo.mutation.TenantID(); ok {
		_spec.SetField(deliverylog.FieldTenantID, field.TypeString, value)
	}
	if value, ok := dluo.mutation.TemplateID(); ok {
		_spec.SetField(deliverylog.FieldTemplateID, field.TypeString, value)
	}
	if value, ok := dluo.mutation.Channel(); ok {
		_spec.SetField(deliverylog.FieldChannel, field.TypeString, value)
	}
	if value, ok := dluo.mutation.Recipient(); ok {
		_spec.SetField(deliverylog.FieldRecipient, field.TypeString, value)
	}
	if value, ok := dluo.mutation.Status(); ok {
		_spec.SetField(deliverylog.FieldStatus, field.TypeString, value)
	}
	_spec.AddModifiers(dluo.modifiers...)
	_node = &DeliveryLog{config: dluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deliverylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dluo.mutation.done = true
	return _node, nil
}
