// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/notifications-api/internal/ent/outboxevent"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
	"github.com/bengobox/notifications-api/internal/ent/providersetting"
	"github.com/bengobox/notifications-api/internal/ent/tenantbranding"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeOutboxEvent     = "OutboxEvent"
	TypeProviderSetting = "ProviderSetting"
	TypeTenantBranding  = "TenantBranding"
)

// OutboxEventMutation represents an operation that mutates the OutboxEvent nodes in the graph.
type OutboxEventMutation struct {
	config
	op              Op
	typ             string
	id              *uuid.UUID
	tenant_id       *uuid.UUID
	aggregate_type  *string
	aggregate_id    *uuid.UUID
	event_type      *string
	payload         *map[string]interface{}
	status          *string
	attempts        *int
	addattempts     *int
	last_attempt_at *time.Time
	published_at    *time.Time
	error_message   *string
	created_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*OutboxEvent, error)
	predicates      []predicate.OutboxEvent
}

var _ ent.Mutation = (*OutboxEventMutation)(nil)

// outboxeventOption allows management of the mutation configuration using functional options.
type outboxeventOption func(*OutboxEventMutation)

// newOutboxEventMutation creates new mutation for the OutboxEvent entity.
func newOutboxEventMutation(c config, op Op, opts ...outboxeventOption) *OutboxEventMutation {
	m := &OutboxEventMutation{
		config:        c,
		op:            op,
		typ:           TypeOutboxEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withOutboxEventID sets the ID field of the mutation.
func withOutboxEventID(id uuid.UUID) outboxeventOption {
	return func(m *OutboxEventMutation) {
		var (
			err   error
			once  sync.Once
			value *OutboxEvent
		)
		m.oldValue = func(ctx context.Context) (*OutboxEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().OutboxEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withOutboxEvent sets the old OutboxEvent of the mutation.
func withOutboxEvent(node *OutboxEvent) outboxeventOption {
	return func(m *OutboxEventMutation) {
		m.oldValue = func(context.Context) (*OutboxEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m OutboxEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m OutboxEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of OutboxEvent entities.
func (m *OutboxEventMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *OutboxEventMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *OutboxEventMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().OutboxEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTenantID sets the "tenant_id" field.
func (m *OutboxEventMutation) SetTenantID(u uuid.UUID) {
	m.tenant_id = &u
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *OutboxEventMutation) TenantID() (r uuid.UUID, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldTenantID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *OutboxEventMutation) ResetTenantID() {
	m.tenant_id = nil
}

// SetAggregateType sets the "aggregate_type" field.
func (m *OutboxEventMutation) SetAggregateType(s string) {
	m.aggregate_type = &s
}

// AggregateType returns the value of the "aggregate_type" field in the mutation.
func (m *OutboxEventMutation) AggregateType() (r string, exists bool) {
	v := m.aggregate_type
	if v == nil {
		return
	}
	return *v, true
}

// OldAggregateType returns the old "aggregate_type" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldAggregateType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAggregateType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAggregateType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAggregateType: %w", err)
	}
	return oldValue.AggregateType, nil
}

// ResetAggregateType resets all changes to the "aggregate_type" field.
func (m *OutboxEventMutation) ResetAggregateType() {
	m.aggregate_type = nil
}

// SetAggregateID sets the "aggregate_id" field.
func (m *OutboxEventMutation) SetAggregateID(u uuid.UUID) {
	m.aggregate_id = &u
}

// AggregateID returns the value of the "aggregate_id" field in the mutation.
func (m *OutboxEventMutation) AggregateID() (r uuid.UUID, exists bool) {
	v := m.aggregate_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAggregateID returns the old "aggregate_id" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldAggregateID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAggregateID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAggregateID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAggregateID: %w", err)
	}
	return oldValue.AggregateID, nil
}

// ResetAggregateID resets all changes to the "aggregate_id" field.
func (m *OutboxEventMutation) ResetAggregateID() {
	m.aggregate_id = nil
}

// SetEventType sets the "event_type" field.
func (m *OutboxEventMutation) SetEventType(s string) {
	m.event_type = &s
}

// EventType returns the value of the "event_type" field in the mutation.
func (m *OutboxEventMutation) EventType() (r string, exists bool) {
	v := m.event_type
	if v == nil {
		return
	}
	return *v, true
}

// OldEventType returns the old "event_type" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldEventType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventType: %w", err)
	}
	return oldValue.EventType, nil
}

// ResetEventType resets all changes to the "event_type" field.
func (m *OutboxEventMutation) ResetEventType() {
	m.event_type = nil
}

// SetPayload sets the "payload" field.
func (m *OutboxEventMutation) SetPayload(value map[string]interface{}) {
	m.payload = &value
}

// Payload returns the value of the "payload" field in the mutation.
func (m *OutboxEventMutation) Payload() (r map[string]interface{}, exists bool) {
	v := m.payload
	if v == nil {
		return
	}
	return *v, true
}

// OldPayload returns the old "payload" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldPayload(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPayload is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPayload requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPayload: %w", err)
	}
	return oldValue.Payload, nil
}

// ResetPayload resets all changes to the "payload" field.
func (m *OutboxEventMutation) ResetPayload() {
	m.payload = nil
}

// SetStatus sets the "status" field.
func (m *OutboxEventMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *OutboxEventMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *OutboxEventMutation) ResetStatus() {
	m.status = nil
}

// SetAttempts sets the "attempts" field.
func (m *OutboxEventMutation) SetAttempts(i int) {
	m.attempts = &i
	m.addattempts = nil
}

// Attempts returns the value of the "attempts" field in the mutation.
func (m *OutboxEventMutation) Attempts() (r int, exists bool) {
	v := m.attempts
	if v == nil {
		return
	}
	return *v, true
}

// OldAttempts returns the old "attempts" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldAttempts(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttempts is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttempts requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttempts: %w", err)
	}
	return oldValue.Attempts, nil
}

// AddAttempts adds i to the "attempts" field.
func (m *OutboxEventMutation) AddAttempts(i int) {
	if m.addattempts != nil {
		*m.addattempts += i
	} else {
		m.addattempts = &i
	}
}

// AddedAttempts returns the value that was added to the "attempts" field in this mutation.
func (m *OutboxEventMutation) AddedAttempts() (r int, exists bool) {
	v := m.addattempts
	if v == nil {
		return
	}
	return *v, true
}

// ResetAttempts resets all changes to the "attempts" field.
func (m *OutboxEventMutation) ResetAttempts() {
	m.attempts = nil
	m.addattempts = nil
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (m *OutboxEventMutation) SetLastAttemptAt(t time.Time) {
	m.last_attempt_at = &t
}

// LastAttemptAt returns the value of the "last_attempt_at" field in the mutation.
func (m *OutboxEventMutation) LastAttemptAt() (r time.Time, exists bool) {
	v := m.last_attempt_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastAttemptAt returns the old "last_attempt_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldLastAttemptAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastAttemptAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastAttemptAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastAttemptAt: %w", err)
	}
	return oldValue.LastAttemptAt, nil
}

// ClearLastAttemptAt clears the value of the "last_attempt_at" field.
func (m *OutboxEventMutation) ClearLastAttemptAt() {
	m.last_attempt_at = nil
	m.clearedFields[outboxevent.FieldLastAttemptAt] = struct{}{}
}

// LastAttemptAtCleared returns if the "last_attempt_at" field was cleared in this mutation.
func (m *OutboxEventMutation) LastAttemptAtCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldLastAttemptAt]
	return ok
}

// ResetLastAttemptAt resets all changes to the "last_attempt_at" field.
func (m *OutboxEventMutation) ResetLastAttemptAt() {
	m.last_attempt_at = nil
	delete(m.clearedFields, outboxevent.FieldLastAttemptAt)
}

// SetPublishedAt sets the "published_at" field.
func (m *OutboxEventMutation) SetPublishedAt(t time.Time) {
	m.published_at = &t
}

// PublishedAt returns the value of the "published_at" field in the mutation.
func (m *OutboxEventMutation) PublishedAt() (r time.Time, exists bool) {
	v := m.published_at
	if v == nil {
		return
	}
	return *v, true
}

// OldPublishedAt returns the old "published_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldPublishedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublishedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublishedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublishedAt: %w", err)
	}
	return oldValue.PublishedAt, nil
}

// ClearPublishedAt clears the value of the "published_at" field.
func (m *OutboxEventMutation) ClearPublishedAt() {
	m.published_at = nil
	m.clearedFields[outboxevent.FieldPublishedAt] = struct{}{}
}

// PublishedAtCleared returns if the "published_at" field was cleared in this mutation.
func (m *OutboxEventMutation) PublishedAtCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldPublishedAt]
	return ok
}

// ResetPublishedAt resets all changes to the "published_at" field.
func (m *OutboxEventMutation) ResetPublishedAt() {
	m.published_at = nil
	delete(m.clearedFields, outboxevent.FieldPublishedAt)
}

// SetErrorMessage sets the "error_message" field.
func (m *OutboxEventMutation) SetErrorMessage(s string) {
	m.error_message = &s
}

// ErrorMessage returns the value of the "error_message" field in the mutation.
func (m *OutboxEventMutation) ErrorMessage() (r string, exists bool) {
	v := m.error_message
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorMessage returns the old "error_message" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldErrorMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorMessage: %w", err)
	}
	return oldValue.ErrorMessage, nil
}

// ClearErrorMessage clears the value of the "error_message" field.
func (m *OutboxEventMutation) ClearErrorMessage() {
	m.error_message = nil
	m.clearedFields[outboxevent.FieldErrorMessage] = struct{}{}
}

// ErrorMessageCleared returns if the "error_message" field was cleared in this mutation.
func (m *OutboxEventMutation) ErrorMessageCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldErrorMessage]
	return ok
}

// ResetErrorMessage resets all changes to the "error_message" field.
func (m *OutboxEventMutation) ResetErrorMessage() {
	m.error_message = nil
	delete(m.clearedFields, outboxevent.FieldErrorMessage)
}

// SetCreatedAt sets the "created_at" field.
func (m *OutboxEventMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *OutboxEventMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *OutboxEventMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the OutboxEventMutation builder.
func (m *OutboxEventMutation) Where(ps ...predicate.OutboxEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the OutboxEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *OutboxEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.OutboxEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *OutboxEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *OutboxEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (OutboxEvent).
func (m *OutboxEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *OutboxEventMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.tenant_id != nil {
		fields = append(fields, outboxevent.FieldTenantID)
	}
	if m.aggregate_type != nil {
		fields = append(fields, outboxevent.FieldAggregateType)
	}
	if m.aggregate_id != nil {
		fields = append(fields, outboxevent.FieldAggregateID)
	}
	if m.event_type != nil {
		fields = append(fields, outboxevent.FieldEventType)
	}
	if m.payload != nil {
		fields = append(fields, outboxevent.FieldPayload)
	}
	if m.status != nil {
		fields = append(fields, outboxevent.FieldStatus)
	}
	if m.attempts != nil {
		fields = append(fields, outboxevent.FieldAttempts)
	}
	if m.last_attempt_at != nil {
		fields = append(fields, outboxevent.FieldLastAttemptAt)
	}
	if m.published_at != nil {
		fields = append(fields, outboxevent.FieldPublishedAt)
	}
	if m.error_message != nil {
		fields = append(fields, outboxevent.FieldErrorMessage)
	}
	if m.created_at != nil {
		fields = append(fields, outboxevent.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *OutboxEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case outboxevent.FieldTenantID:
		return m.TenantID()
	case outboxevent.FieldAggregateType:
		return m.AggregateType()
	case outboxevent.FieldAggregateID:
		return m.AggregateID()
	case outboxevent.FieldEventType:
		return m.EventType()
	case outboxevent.FieldPayload:
		return m.Payload()
	case outboxevent.FieldStatus:
		return m.Status()
	case outboxevent.FieldAttempts:
		return m.Attempts()
	case outboxevent.FieldLastAttemptAt:
		return m.LastAttemptAt()
	case outboxevent.FieldPublishedAt:
		return m.PublishedAt()
	case outboxevent.FieldErrorMessage:
		return m.ErrorMessage()
	case outboxevent.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *OutboxEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case outboxevent.FieldTenantID:
		return m.OldTenantID(ctx)
	case outboxevent.FieldAggregateType:
		return m.OldAggregateType(ctx)
	case outboxevent.FieldAggregateID:
		return m.OldAggregateID(ctx)
	case outboxevent.FieldEventType:
		return m.OldEventType(ctx)
	case outboxevent.FieldPayload:
		return m.OldPayload(ctx)
	case outboxevent.FieldStatus:
		return m.OldStatus(ctx)
	case outboxevent.FieldAttempts:
		return m.OldAttempts(ctx)
	case outboxevent.FieldLastAttemptAt:
		return m.OldLastAttemptAt(ctx)
	case outboxevent.FieldPublishedAt:
		return m.OldPublishedAt(ctx)
	case outboxevent.FieldErrorMessage:
		return m.OldErrorMessage(ctx)
	case outboxevent.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown OutboxEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OutboxEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case outboxevent.FieldTenantID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case outboxevent.FieldAggregateType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAggregateType(v)
		return nil
	case outboxevent.FieldAggregateID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAggregateID(v)
		return nil
	case outboxevent.FieldEventType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventType(v)
		return nil
	case outboxevent.FieldPayload:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPayload(v)
		return nil
	case outboxevent.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case outboxevent.FieldAttempts:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttempts(v)
		return nil
	case outboxevent.FieldLastAttemptAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastAttemptAt(v)
		return nil
	case outboxevent.FieldPublishedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublishedAt(v)
		return nil
	case outboxevent.FieldErrorMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorMessage(v)
		return nil
	case outboxevent.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *OutboxEventMutation) AddedFields() []string {
	var fields []string
	if m.addattempts != nil {
		fields = append(fields, outboxevent.FieldAttempts)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *OutboxEventMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case outboxevent.FieldAttempts:
		return m.AddedAttempts()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OutboxEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	case outboxevent.FieldAttempts:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAttempts(v)
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *OutboxEventMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(outboxevent.FieldLastAttemptAt) {
		fields = append(fields, outboxevent.FieldLastAttemptAt)
	}
	if m.FieldCleared(outboxevent.FieldPublishedAt) {
		fields = append(fields, outboxevent.FieldPublishedAt)
	}
	if m.FieldCleared(outboxevent.FieldErrorMessage) {
		fields = append(fields, outboxevent.FieldErrorMessage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *OutboxEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *OutboxEventMutation) ClearField(name string) error {
	switch name {
	case outboxevent.FieldLastAttemptAt:
		m.ClearLastAttemptAt()
		return nil
	case outboxevent.FieldPublishedAt:
		m.ClearPublishedAt()
		return nil
	case outboxevent.FieldErrorMessage:
		m.ClearErrorMessage()
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *OutboxEventMutation) ResetField(name string) error {
	switch name {
	case outboxevent.FieldTenantID:
		m.ResetTenantID()
		return nil
	case outboxevent.FieldAggregateType:
		m.ResetAggregateType()
		return nil
	case outboxevent.FieldAggregateID:
		m.ResetAggregateID()
		return nil
	case outboxevent.FieldEventType:
		m.ResetEventType()
		return nil
	case outboxevent.FieldPayload:
		m.ResetPayload()
		return nil
	case outboxevent.FieldStatus:
		m.ResetStatus()
		return nil
	case outboxevent.FieldAttempts:
		m.ResetAttempts()
		return nil
	case outboxevent.FieldLastAttemptAt:
		m.ResetLastAttemptAt()
		return nil
	case outboxevent.FieldPublishedAt:
		m.ResetPublishedAt()
		return nil
	case outboxevent.FieldErrorMessage:
		m.ResetErrorMessage()
		return nil
	case outboxevent.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OutboxEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *OutboxEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OutboxEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *OutboxEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OutboxEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *OutboxEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *OutboxEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown OutboxEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *OutboxEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown OutboxEvent edge %s", name)
}

// ProviderSettingMutation represents an operation that mutates the ProviderSetting nodes in the graph.
type ProviderSettingMutation struct {
	config
	op            Op
	typ           string
	id            *int
	tenant_id     *string
	channel       *string
	provider      *string
	provider_type *string
	provider_name *string
	key           *string
	value         *string
	description   *string
	is_encrypted  *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ProviderSetting, error)
	predicates    []predicate.ProviderSetting
}

var _ ent.Mutation = (*ProviderSettingMutation)(nil)

// providersettingOption allows management of the mutation configuration using functional options.
type providersettingOption func(*ProviderSettingMutation)

// newProviderSettingMutation creates new mutation for the ProviderSetting entity.
func newProviderSettingMutation(c config, op Op, opts ...providersettingOption) *ProviderSettingMutation {
	m := &ProviderSettingMutation{
		config:        c,
		op:            op,
		typ:           TypeProviderSetting,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProviderSettingID sets the ID field of the mutation.
func withProviderSettingID(id int) providersettingOption {
	return func(m *ProviderSettingMutation) {
		var (
			err   error
			once  sync.Once
			value *ProviderSetting
		)
		m.oldValue = func(ctx context.Context) (*ProviderSetting, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ProviderSetting.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProviderSetting sets the old ProviderSetting of the mutation.
func withProviderSetting(node *ProviderSetting) providersettingOption {
	return func(m *ProviderSettingMutation) {
		m.oldValue = func(context.Context) (*ProviderSetting, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProviderSettingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProviderSettingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProviderSettingMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProviderSettingMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ProviderSetting.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTenantID sets the "tenant_id" field.
func (m *ProviderSettingMutation) SetTenantID(s string) {
	m.tenant_id = &s
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *ProviderSettingMutation) TenantID() (r string, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldTenantID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *ProviderSettingMutation) ResetTenantID() {
	m.tenant_id = nil
}

// SetChannel sets the "channel" field.
func (m *ProviderSettingMutation) SetChannel(s string) {
	m.channel = &s
}

// Channel returns the value of the "channel" field in the mutation.
func (m *ProviderSettingMutation) Channel() (r string, exists bool) {
	v := m.channel
	if v == nil {
		return
	}
	return *v, true
}

// OldChannel returns the old "channel" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldChannel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChannel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChannel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChannel: %w", err)
	}
	return oldValue.Channel, nil
}

// ClearChannel clears the value of the "channel" field.
func (m *ProviderSettingMutation) ClearChannel() {
	m.channel = nil
	m.clearedFields[providersetting.FieldChannel] = struct{}{}
}

// ChannelCleared returns if the "channel" field was cleared in this mutation.
func (m *ProviderSettingMutation) ChannelCleared() bool {
	_, ok := m.clearedFields[providersetting.FieldChannel]
	return ok
}

// ResetChannel resets all changes to the "channel" field.
func (m *ProviderSettingMutation) ResetChannel() {
	m.channel = nil
	delete(m.clearedFields, providersetting.FieldChannel)
}

// SetProvider sets the "provider" field.
func (m *ProviderSettingMutation) SetProvider(s string) {
	m.provider = &s
}

// Provider returns the value of the "provider" field in the mutation.
func (m *ProviderSettingMutation) Provider() (r string, exists bool) {
	v := m.provider
	if v == nil {
		return
	}
	return *v, true
}

// OldProvider returns the old "provider" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldProvider(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProvider is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProvider requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProvider: %w", err)
	}
	return oldValue.Provider, nil
}

// ClearProvider clears the value of the "provider" field.
func (m *ProviderSettingMutation) ClearProvider() {
	m.provider = nil
	m.clearedFields[providersetting.FieldProvider] = struct{}{}
}

// ProviderCleared returns if the "provider" field was cleared in this mutation.
func (m *ProviderSettingMutation) ProviderCleared() bool {
	_, ok := m.clearedFields[providersetting.FieldProvider]
	return ok
}

// ResetProvider resets all changes to the "provider" field.
func (m *ProviderSettingMutation) ResetProvider() {
	m.provider = nil
	delete(m.clearedFields, providersetting.FieldProvider)
}

// SetProviderType sets the "provider_type" field.
func (m *ProviderSettingMutation) SetProviderType(s string) {
	m.provider_type = &s
}

// ProviderType returns the value of the "provider_type" field in the mutation.
func (m *ProviderSettingMutation) ProviderType() (r string, exists bool) {
	v := m.provider_type
	if v == nil {
		return
	}
	return *v, true
}

// OldProviderType returns the old "provider_type" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldProviderType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProviderType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProviderType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProviderType: %w", err)
	}
	return oldValue.ProviderType, nil
}

// ClearProviderType clears the value of the "provider_type" field.
func (m *ProviderSettingMutation) ClearProviderType() {
	m.provider_type = nil
	m.clearedFields[providersetting.FieldProviderType] = struct{}{}
}

// ProviderTypeCleared returns if the "provider_type" field was cleared in this mutation.
func (m *ProviderSettingMutation) ProviderTypeCleared() bool {
	_, ok := m.clearedFields[providersetting.FieldProviderType]
	return ok
}

// ResetProviderType resets all changes to the "provider_type" field.
func (m *ProviderSettingMutation) ResetProviderType() {
	m.provider_type = nil
	delete(m.clearedFields, providersetting.FieldProviderType)
}

// SetProviderName sets the "provider_name" field.
func (m *ProviderSettingMutation) SetProviderName(s string) {
	m.provider_name = &s
}

// ProviderName returns the value of the "provider_name" field in the mutation.
func (m *ProviderSettingMutation) ProviderName() (r string, exists bool) {
	v := m.provider_name
	if v == nil {
		return
	}
	return *v, true
}

// OldProviderName returns the old "provider_name" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldProviderName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProviderName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProviderName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProviderName: %w", err)
	}
	return oldValue.ProviderName, nil
}

// ClearProviderName clears the value of the "provider_name" field.
func (m *ProviderSettingMutation) ClearProviderName() {
	m.provider_name = nil
	m.clearedFields[providersetting.FieldProviderName] = struct{}{}
}

// ProviderNameCleared returns if the "provider_name" field was cleared in this mutation.
func (m *ProviderSettingMutation) ProviderNameCleared() bool {
	_, ok := m.clearedFields[providersetting.FieldProviderName]
	return ok
}

// ResetProviderName resets all changes to the "provider_name" field.
func (m *ProviderSettingMutation) ResetProviderName() {
	m.provider_name = nil
	delete(m.clearedFields, providersetting.FieldProviderName)
}

// SetKey sets the "key" field.
func (m *ProviderSettingMutation) SetKey(s string) {
	m.key = &s
}

// Key returns the value of the "key" field in the mutation.
func (m *ProviderSettingMutation) Key() (r string, exists bool) {
	v := m.key
	if v == nil {
		return
	}
	return *v, true
}

// OldKey returns the old "key" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKey: %w", err)
	}
	return oldValue.Key, nil
}

// ClearKey clears the value of the "key" field.
func (m *ProviderSettingMutation) ClearKey() {
	m.key = nil
	m.clearedFields[providersetting.FieldKey] = struct{}{}
}

// KeyCleared returns if the "key" field was cleared in this mutation.
func (m *ProviderSettingMutation) KeyCleared() bool {
	_, ok := m.clearedFields[providersetting.FieldKey]
	return ok
}

// ResetKey resets all changes to the "key" field.
func (m *ProviderSettingMutation) ResetKey() {
	m.key = nil
	delete(m.clearedFields, providersetting.FieldKey)
}

// SetValue sets the "value" field.
func (m *ProviderSettingMutation) SetValue(s string) {
	m.value = &s
}

// Value returns the value of the "value" field in the mutation.
func (m *ProviderSettingMutation) Value() (r string, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// ClearValue clears the value of the "value" field.
func (m *ProviderSettingMutation) ClearValue() {
	m.value = nil
	m.clearedFields[providersetting.FieldValue] = struct{}{}
}

// ValueCleared returns if the "value" field was cleared in this mutation.
func (m *ProviderSettingMutation) ValueCleared() bool {
	_, ok := m.clearedFields[providersetting.FieldValue]
	return ok
}

// ResetValue resets all changes to the "value" field.
func (m *ProviderSettingMutation) ResetValue() {
	m.value = nil
	delete(m.clearedFields, providersetting.FieldValue)
}

// SetDescription sets the "description" field.
func (m *ProviderSettingMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *ProviderSettingMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *ProviderSettingMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[providersetting.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *ProviderSettingMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[providersetting.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *ProviderSettingMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, providersetting.FieldDescription)
}

// SetIsEncrypted sets the "is_encrypted" field.
func (m *ProviderSettingMutation) SetIsEncrypted(b bool) {
	m.is_encrypted = &b
}

// IsEncrypted returns the value of the "is_encrypted" field in the mutation.
func (m *ProviderSettingMutation) IsEncrypted() (r bool, exists bool) {
	v := m.is_encrypted
	if v == nil {
		return
	}
	return *v, true
}

// OldIsEncrypted returns the old "is_encrypted" field's value of the ProviderSetting entity.
// If the ProviderSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderSettingMutation) OldIsEncrypted(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsEncrypted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsEncrypted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsEncrypted: %w", err)
	}
	return oldValue.IsEncrypted, nil
}

// ResetIsEncrypted resets all changes to the "is_encrypted" field.
func (m *ProviderSettingMutation) ResetIsEncrypted() {
	m.is_encrypted = nil
}

// Where appends a list predicates to the ProviderSettingMutation builder.
func (m *ProviderSettingMutation) Where(ps ...predicate.ProviderSetting) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProviderSettingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProviderSettingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ProviderSetting, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProviderSettingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProviderSettingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ProviderSetting).
func (m *ProviderSettingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProviderSettingMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.tenant_id != nil {
		fields = append(fields, providersetting.FieldTenantID)
	}
	if m.channel != nil {
		fields = append(fields, providersetting.FieldChannel)
	}
	if m.provider != nil {
		fields = append(fields, providersetting.FieldProvider)
	}
	if m.provider_type != nil {
		fields = append(fields, providersetting.FieldProviderType)
	}
	if m.provider_name != nil {
		fields = append(fields, providersetting.FieldProviderName)
	}
	if m.key != nil {
		fields = append(fields, providersetting.FieldKey)
	}
	if m.value != nil {
		fields = append(fields, providersetting.FieldValue)
	}
	if m.description != nil {
		fields = append(fields, providersetting.FieldDescription)
	}
	if m.is_encrypted != nil {
		fields = append(fields, providersetting.FieldIsEncrypted)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProviderSettingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case providersetting.FieldTenantID:
		return m.TenantID()
	case providersetting.FieldChannel:
		return m.Channel()
	case providersetting.FieldProvider:
		return m.Provider()
	case providersetting.FieldProviderType:
		return m.ProviderType()
	case providersetting.FieldProviderName:
		return m.ProviderName()
	case providersetting.FieldKey:
		return m.Key()
	case providersetting.FieldValue:
		return m.Value()
	case providersetting.FieldDescription:
		return m.Description()
	case providersetting.FieldIsEncrypted:
		return m.IsEncrypted()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProviderSettingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case providersetting.FieldTenantID:
		return m.OldTenantID(ctx)
	case providersetting.FieldChannel:
		return m.OldChannel(ctx)
	case providersetting.FieldProvider:
		return m.OldProvider(ctx)
	case providersetting.FieldProviderType:
		return m.OldProviderType(ctx)
	case providersetting.FieldProviderName:
		return m.OldProviderName(ctx)
	case providersetting.FieldKey:
		return m.OldKey(ctx)
	case providersetting.FieldValue:
		return m.OldValue(ctx)
	case providersetting.FieldDescription:
		return m.OldDescription(ctx)
	case providersetting.FieldIsEncrypted:
		return m.OldIsEncrypted(ctx)
	}
	return nil, fmt.Errorf("unknown ProviderSetting field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProviderSettingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case providersetting.FieldTenantID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case providersetting.FieldChannel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChannel(v)
		return nil
	case providersetting.FieldProvider:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProvider(v)
		return nil
	case providersetting.FieldProviderType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderType(v)
		return nil
	case providersetting.FieldProviderName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderName(v)
		return nil
	case providersetting.FieldKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKey(v)
		return nil
	case providersetting.FieldValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	case providersetting.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case providersetting.FieldIsEncrypted:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsEncrypted(v)
		return nil
	}
	return fmt.Errorf("unknown ProviderSetting field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProviderSettingMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProviderSettingMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProviderSettingMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ProviderSetting numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProviderSettingMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(providersetting.FieldChannel) {
		fields = append(fields, providersetting.FieldChannel)
	}
	if m.FieldCleared(providersetting.FieldProvider) {
		fields = append(fields, providersetting.FieldProvider)
	}
	if m.FieldCleared(providersetting.FieldProviderType) {
		fields = append(fields, providersetting.FieldProviderType)
	}
	if m.FieldCleared(providersetting.FieldProviderName) {
		fields = append(fields, providersetting.FieldProviderName)
	}
	if m.FieldCleared(providersetting.FieldKey) {
		fields = append(fields, providersetting.FieldKey)
	}
	if m.FieldCleared(providersetting.FieldValue) {
		fields = append(fields, providersetting.FieldValue)
	}
	if m.FieldCleared(providersetting.FieldDescription) {
		fields = append(fields, providersetting.FieldDescription)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProviderSettingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProviderSettingMutation) ClearField(name string) error {
	switch name {
	case providersetting.FieldChannel:
		m.ClearChannel()
		return nil
	case providersetting.FieldProvider:
		m.ClearProvider()
		return nil
	case providersetting.FieldProviderType:
		m.ClearProviderType()
		return nil
	case providersetting.FieldProviderName:
		m.ClearProviderName()
		return nil
	case providersetting.FieldKey:
		m.ClearKey()
		return nil
	case providersetting.FieldValue:
		m.ClearValue()
		return nil
	case providersetting.FieldDescription:
		m.ClearDescription()
		return nil
	}
	return fmt.Errorf("unknown ProviderSetting nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProviderSettingMutation) ResetField(name string) error {
	switch name {
	case providersetting.FieldTenantID:
		m.ResetTenantID()
		return nil
	case providersetting.FieldChannel:
		m.ResetChannel()
		return nil
	case providersetting.FieldProvider:
		m.ResetProvider()
		return nil
	case providersetting.FieldProviderType:
		m.ResetProviderType()
		return nil
	case providersetting.FieldProviderName:
		m.ResetProviderName()
		return nil
	case providersetting.FieldKey:
		m.ResetKey()
		return nil
	case providersetting.FieldValue:
		m.ResetValue()
		return nil
	case providersetting.FieldDescription:
		m.ResetDescription()
		return nil
	case providersetting.FieldIsEncrypted:
		m.ResetIsEncrypted()
		return nil
	}
	return fmt.Errorf("unknown ProviderSetting field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProviderSettingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProviderSettingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProviderSettingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProviderSettingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProviderSettingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProviderSettingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProviderSettingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ProviderSetting unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProviderSettingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ProviderSetting edge %s", name)
}

// TenantBrandingMutation represents an operation that mutates the TenantBranding nodes in the graph.
type TenantBrandingMutation struct {
	config
	op              Op
	typ             string
	id              *int
	tenant_id       *string
	logo_url        *string
	primary_color   *string
	secondary_color *string
	font_family     *string
	custom_css      *string
	metadata        *map[string]interface{}
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*TenantBranding, error)
	predicates      []predicate.TenantBranding
}

var _ ent.Mutation = (*TenantBrandingMutation)(nil)

// tenantbrandingOption allows management of the mutation configuration using functional options.
type tenantbrandingOption func(*TenantBrandingMutation)

// newTenantBrandingMutation creates new mutation for the TenantBranding entity.
func newTenantBrandingMutation(c config, op Op, opts ...tenantbrandingOption) *TenantBrandingMutation {
	m := &TenantBrandingMutation{
		config:        c,
		op:            op,
		typ:           TypeTenantBranding,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTenantBrandingID sets the ID field of the mutation.
func withTenantBrandingID(id int) tenantbrandingOption {
	return func(m *TenantBrandingMutation) {
		var (
			err   error
			once  sync.Once
			value *TenantBranding
		)
		m.oldValue = func(ctx context.Context) (*TenantBranding, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TenantBranding.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTenantBranding sets the old TenantBranding of the mutation.
func withTenantBranding(node *TenantBranding) tenantbrandingOption {
	return func(m *TenantBrandingMutation) {
		m.oldValue = func(context.Context) (*TenantBranding, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TenantBrandingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TenantBrandingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TenantBrandingMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TenantBrandingMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TenantBranding.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTenantID sets the "tenant_id" field.
func (m *TenantBrandingMutation) SetTenantID(s string) {
	m.tenant_id = &s
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *TenantBrandingMutation) TenantID() (r string, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the TenantBranding entity.
// If the TenantBranding object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TenantBrandingMutation) OldTenantID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *TenantBrandingMutation) ResetTenantID() {
	m.tenant_id = nil
}

// SetLogoURL sets the "logo_url" field.
func (m *TenantBrandingMutation) SetLogoURL(s string) {
	m.logo_url = &s
}

// LogoURL returns the value of the "logo_url" field in the mutation.
func (m *TenantBrandingMutation) LogoURL() (r string, exists bool) {
	v := m.logo_url
	if v == nil {
		return
	}
	return *v, true
}

// OldLogoURL returns the old "logo_url" field's value of the TenantBranding entity.
// If the TenantBranding object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TenantBrandingMutation) OldLogoURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLogoURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLogoURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLogoURL: %w", err)
	}
	return oldValue.LogoURL, nil
}

// ClearLogoURL clears the value of the "logo_url" field.
func (m *TenantBrandingMutation) ClearLogoURL() {
	m.logo_url = nil
	m.clearedFields[tenantbranding.FieldLogoURL] = struct{}{}
}

// LogoURLCleared returns if the "logo_url" field was cleared in this mutation.
func (m *TenantBrandingMutation) LogoURLCleared() bool {
	_, ok := m.clearedFields[tenantbranding.FieldLogoURL]
	return ok
}

// ResetLogoURL resets all changes to the "logo_url" field.
func (m *TenantBrandingMutation) ResetLogoURL() {
	m.logo_url = nil
	delete(m.clearedFields, tenantbranding.FieldLogoURL)
}

// SetPrimaryColor sets the "primary_color" field.
func (m *TenantBrandingMutation) SetPrimaryColor(s string) {
	m.primary_color = &s
}

// PrimaryColor returns the value of the "primary_color" field in the mutation.
func (m *TenantBrandingMutation) PrimaryColor() (r string, exists bool) {
	v := m.primary_color
	if v == nil {
		return
	}
	return *v, true
}

// OldPrimaryColor returns the old "primary_color" field's value of the TenantBranding entity.
// If the TenantBranding object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TenantBrandingMutation) OldPrimaryColor(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrimaryColor is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrimaryColor requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrimaryColor: %w", err)
	}
	return oldValue.PrimaryColor, nil
}

// ClearPrimaryColor clears the value of the "primary_color" field.
func (m *TenantBrandingMutation) ClearPrimaryColor() {
	m.primary_color = nil
	m.clearedFields[tenantbranding.FieldPrimaryColor] = struct{}{}
}

// PrimaryColorCleared returns if the "primary_color" field was cleared in this mutation.
func (m *TenantBrandingMutation) PrimaryColorCleared() bool {
	_, ok := m.clearedFields[tenantbranding.FieldPrimaryColor]
	return ok
}

// ResetPrimaryColor resets all changes to the "primary_color" field.
func (m *TenantBrandingMutation) ResetPrimaryColor() {
	m.primary_color = nil
	delete(m.clearedFields, tenantbranding.FieldPrimaryColor)
}

// SetSecondaryColor sets the "secondary_color" field.
func (m *TenantBrandingMutation) SetSecondaryColor(s string) {
	m.secondary_color = &s
}

// SecondaryColor returns the value of the "secondary_color" field in the mutation.
func (m *TenantBrandingMutation) SecondaryColor() (r string, exists bool) {
	v := m.secondary_color
	if v == nil {
		return
	}
	return *v, true
}

// OldSecondaryColor returns the old "secondary_color" field's value of the TenantBranding entity.
// If the TenantBranding object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TenantBrandingMutation) OldSecondaryColor(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSecondaryColor is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSecondaryColor requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSecondaryColor: %w", err)
	}
	return oldValue.SecondaryColor, nil
}

// ClearSecondaryColor clears the value of the "secondary_color" field.
func (m *TenantBrandingMutation) ClearSecondaryColor() {
	m.secondary_color = nil
	m.clearedFields[tenantbranding.FieldSecondaryColor] = struct{}{}
}

// SecondaryColorCleared returns if the "secondary_color" field was cleared in this mutation.
func (m *TenantBrandingMutation) SecondaryColorCleared() bool {
	_, ok := m.clearedFields[tenantbranding.FieldSecondaryColor]
	return ok
}

// ResetSecondaryColor resets all changes to the "secondary_color" field.
func (m *TenantBrandingMutation) ResetSecondaryColor() {
	m.secondary_color = nil
	delete(m.clearedFields, tenantbranding.FieldSecondaryColor)
}

// SetFontFamily sets the "font_family" field.
func (m *TenantBrandingMutation) SetFontFamily(s string) {
	m.font_family = &s
}

// FontFamily returns the value of the "font_family" field in the mutation.
func (m *TenantBrandingMutation) FontFamily() (r string, exists bool) {
	v := m.font_family
	if v == nil {
		return
	}
	return *v, true
}

// OldFontFamily returns the old "font_family" field's value of the TenantBranding entity.
// If the TenantBranding object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TenantBrandingMutation) OldFontFamily(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFontFamily is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFontFamily requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFontFamily: %w", err)
	}
	return oldValue.FontFamily, nil
}

// ClearFontFamily clears the value of the "font_family" field.
func (m *TenantBrandingMutation) ClearFontFamily() {
	m.font_family = nil
	m.clearedFields[tenantbranding.FieldFontFamily] = struct{}{}
}

// FontFamilyCleared returns if the "font_family" field was cleared in this mutation.
func (m *TenantBrandingMutation) FontFamilyCleared() bool {
	_, ok := m.clearedFields[tenantbranding.FieldFontFamily]
	return ok
}

// ResetFontFamily resets all changes to the "font_family" field.
func (m *TenantBrandingMutation) ResetFontFamily() {
	m.font_family = nil
	delete(m.clearedFields, tenantbranding.FieldFontFamily)
}

// SetCustomCSS sets the "custom_css" field.
func (m *TenantBrandingMutation) SetCustomCSS(s string) {
	m.custom_css = &s
}

// CustomCSS returns the value of the "custom_css" field in the mutation.
func (m *TenantBrandingMutation) CustomCSS() (r string, exists bool) {
	v := m.custom_css
	if v == nil {
		return
	}
	return *v, true
}

// OldCustomCSS returns the old "custom_css" field's value of the TenantBranding entity.
// If the TenantBranding object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TenantBrandingMutation) OldCustomCSS(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCustomCSS is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCustomCSS requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCustomCSS: %w", err)
	}
	return oldValue.CustomCSS, nil
}

// ClearCustomCSS clears the value of the "custom_css" field.
func (m *TenantBrandingMutation) ClearCustomCSS() {
	m.custom_css = nil
	m.clearedFields[tenantbranding.FieldCustomCSS] = struct{}{}
}

// CustomCSSCleared returns if the "custom_css" field was cleared in this mutation.
func (m *TenantBrandingMutation) CustomCSSCleared() bool {
	_, ok := m.clearedFields[tenantbranding.FieldCustomCSS]
	return ok
}

// ResetCustomCSS resets all changes to the "custom_css" field.
func (m *TenantBrandingMutation) ResetCustomCSS() {
	m.custom_css = nil
	delete(m.clearedFields, tenantbranding.FieldCustomCSS)
}

// SetMetadata sets the "metadata" field.
func (m *TenantBrandingMutation) SetMetadata(value map[string]interface{}) {
	m.metadata = &value
}

// Metadata returns the value of the "metadata" field in the mutation.
func (m *TenantBrandingMutation) Metadata() (r map[string]interface{}, exists bool) {
	v := m.metadata
	if v == nil {
		return
	}
	return *v, true
}

// OldMetadata returns the old "metadata" field's value of the TenantBranding entity.
// If the TenantBranding object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TenantBrandingMutation) OldMetadata(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMetadata is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMetadata requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMetadata: %w", err)
	}
	return oldValue.Metadata, nil
}

// ClearMetadata clears the value of the "metadata" field.
func (m *TenantBrandingMutation) ClearMetadata() {
	m.metadata = nil
	m.clearedFields[tenantbranding.FieldMetadata] = struct{}{}
}

// MetadataCleared returns if the "metadata" field was cleared in this mutation.
func (m *TenantBrandingMutation) MetadataCleared() bool {
	_, ok := m.clearedFields[tenantbranding.FieldMetadata]
	return ok
}

// ResetMetadata resets all changes to the "metadata" field.
func (m *TenantBrandingMutation) ResetMetadata() {
	m.metadata = nil
	delete(m.clearedFields, tenantbranding.FieldMetadata)
}

// Where appends a list predicates to the TenantBrandingMutation builder.
func (m *TenantBrandingMutation) Where(ps ...predicate.TenantBranding) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TenantBrandingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TenantBrandingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TenantBranding, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TenantBrandingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TenantBrandingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TenantBranding).
func (m *TenantBrandingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TenantBrandingMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.tenant_id != nil {
		fields = append(fields, tenantbranding.FieldTenantID)
	}
	if m.logo_url != nil {
		fields = append(fields, tenantbranding.FieldLogoURL)
	}
	if m.primary_color != nil {
		fields = append(fields, tenantbranding.FieldPrimaryColor)
	}
	if m.secondary_color != nil {
		fields = append(fields, tenantbranding.FieldSecondaryColor)
	}
	if m.font_family != nil {
		fields = append(fields, tenantbranding.FieldFontFamily)
	}
	if m.custom_css != nil {
		fields = append(fields, tenantbranding.FieldCustomCSS)
	}
	if m.metadata != nil {
		fields = append(fields, tenantbranding.FieldMetadata)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TenantBrandingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tenantbranding.FieldTenantID:
		return m.TenantID()
	case tenantbranding.FieldLogoURL:
		return m.LogoURL()
	case tenantbranding.FieldPrimaryColor:
		return m.PrimaryColor()
	case tenantbranding.FieldSecondaryColor:
		return m.SecondaryColor()
	case tenantbranding.FieldFontFamily:
		return m.FontFamily()
	case tenantbranding.FieldCustomCSS:
		return m.CustomCSS()
	case tenantbranding.FieldMetadata:
		return m.Metadata()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TenantBrandingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tenantbranding.FieldTenantID:
		return m.OldTenantID(ctx)
	case tenantbranding.FieldLogoURL:
		return m.OldLogoURL(ctx)
	case tenantbranding.FieldPrimaryColor:
		return m.OldPrimaryColor(ctx)
	case tenantbranding.FieldSecondaryColor:
		return m.OldSecondaryColor(ctx)
	case tenantbranding.FieldFontFamily:
		return m.OldFontFamily(ctx)
	case tenantbranding.FieldCustomCSS:
		return m.OldCustomCSS(ctx)
	case tenantbranding.FieldMetadata:
		return m.OldMetadata(ctx)
	}
	return nil, fmt.Errorf("unknown TenantBranding field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TenantBrandingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tenantbranding.FieldTenantID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case tenantbranding.FieldLogoURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLogoURL(v)
		return nil
	case tenantbranding.FieldPrimaryColor:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrimaryColor(v)
		return nil
	case tenantbranding.FieldSecondaryColor:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSecondaryColor(v)
		return nil
	case tenantbranding.FieldFontFamily:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFontFamily(v)
		return nil
	case tenantbranding.FieldCustomCSS:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCustomCSS(v)
		return nil
	case tenantbranding.FieldMetadata:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMetadata(v)
		return nil
	}
	return fmt.Errorf("unknown TenantBranding field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TenantBrandingMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TenantBrandingMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TenantBrandingMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TenantBranding numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TenantBrandingMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(tenantbranding.FieldLogoURL) {
		fields = append(fields, tenantbranding.FieldLogoURL)
	}
	if m.FieldCleared(tenantbranding.FieldPrimaryColor) {
		fields = append(fields, tenantbranding.FieldPrimaryColor)
	}
	if m.FieldCleared(tenantbranding.FieldSecondaryColor) {
		fields = append(fields, tenantbranding.FieldSecondaryColor)
	}
	if m.FieldCleared(tenantbranding.FieldFontFamily) {
		fields = append(fields, tenantbranding.FieldFontFamily)
	}
	if m.FieldCleared(tenantbranding.FieldCustomCSS) {
		fields = append(fields, tenantbranding.FieldCustomCSS)
	}
	if m.FieldCleared(tenantbranding.FieldMetadata) {
		fields = append(fields, tenantbranding.FieldMetadata)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TenantBrandingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TenantBrandingMutation) ClearField(name string) error {
	switch name {
	case tenantbranding.FieldLogoURL:
		m.ClearLogoURL()
		return nil
	case tenantbranding.FieldPrimaryColor:
		m.ClearPrimaryColor()
		return nil
	case tenantbranding.FieldSecondaryColor:
		m.ClearSecondaryColor()
		return nil
	case tenantbranding.FieldFontFamily:
		m.ClearFontFamily()
		return nil
	case tenantbranding.FieldCustomCSS:
		m.ClearCustomCSS()
		return nil
	case tenantbranding.FieldMetadata:
		m.ClearMetadata()
		return nil
	}
	return fmt.Errorf("unknown TenantBranding nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TenantBrandingMutation) ResetField(name string) error {
	switch name {
	case tenantbranding.FieldTenantID:
		m.ResetTenantID()
		return nil
	case tenantbranding.FieldLogoURL:
		m.ResetLogoURL()
		return nil
	case tenantbranding.FieldPrimaryColor:
		m.ResetPrimaryColor()
		return nil
	case tenantbranding.FieldSecondaryColor:
		m.ResetSecondaryColor()
		return nil
	case tenantbranding.FieldFontFamily:
		m.ResetFontFamily()
		return nil
	case tenantbranding.FieldCustomCSS:
		m.ResetCustomCSS()
		return nil
	case tenantbranding.FieldMetadata:
		m.ResetMetadata()
		return nil
	}
	return fmt.Errorf("unknown TenantBranding field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TenantBrandingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TenantBrandingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TenantBrandingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TenantBrandingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TenantBrandingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TenantBrandingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TenantBrandingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown TenantBranding unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TenantBrandingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown TenantBranding edge %s", name)
}
