// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/notificationpermission"
	"github.com/bengobox/notifications-api/internal/ent/notificationrole"
	"github.com/bengobox/notifications-api/internal/ent/notificationrolepermission"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
	"github.com/bengobox/notifications-api/internal/ent/userroleassignment"
	"github.com/google/uuid"
)

// NotificationRoleUpdate is the builder for updating NotificationRole entities.
type NotificationRoleUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationRoleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationRoleUpdate builder.
func (nru *NotificationRoleUpdate) Where(ps ...predicate.NotificationRole) *NotificationRoleUpdate {
	nru.mutation.Where(ps...)
	return nru
}

// SetTenantID sets the "tenant_id" field.
func (nru *NotificationRoleUpdate) SetTenantID(u uuid.UUID) *NotificationRoleUpdate {
	nru.mutation.SetTenantID(u)
	return nru
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (nru *NotificationRoleUpdate) SetNillableTenantID(u *uuid.UUID) *NotificationRoleUpdate {
	if u != nil {
		nru.SetTenantID(*u)
	}
	return nru
}

// SetRoleCode sets the "role_code" field.
func (nru *NotificationRoleUpdate) SetRoleCode(s string) *NotificationRoleUpdate {
	nru.mutation.SetRoleCode(s)
	return nru
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (nru *NotificationRoleUpdate) SetNillableRoleCode(s *string) *NotificationRoleUpdate {
	if s != nil {
		nru.SetRoleCode(*s)
	}
	return nru
}

// SetName sets the "name" field.
func (nru *NotificationRoleUpdate) SetName(s string) *NotificationRoleUpdate {
	nru.mutation.SetName(s)
	return nru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nru *NotificationRoleUpdate) SetNillableName(s *string) *NotificationRoleUpdate {
	if s != nil {
		nru.SetName(*s)
	}
	return nru
}

// SetDescription sets the "description" field.
func (nru *NotificationRoleUpdate) SetDescription(s string) *NotificationRoleUpdate {
	nru.mutation.SetDescription(s)
	return nru
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (nru *NotificationRoleUpdate) SetNillableDescription(s *string) *NotificationRoleUpdate {
	if s != nil {
		nru.SetDescription(*s)
	}
	return nru
}

// ClearDescription clears the value of the "description" field.
func (nru *NotificationRoleUpdate) ClearDescription() *NotificationRoleUpdate {
	nru.mutation.ClearDescription()
	return nru
}

// SetIsSystemRole sets the "is_system_role" field.
func (nru *NotificationRoleUpdate) SetIsSystemRole(b bool) *NotificationRoleUpdate {
	nru.mutation.SetIsSystemRole(b)
	return nru
}

// SetNillableIsSystemRole sets the "is_system_role" field if the given value is not nil.
func (nru *NotificationRoleUpdate) SetNillableIsSystemRole(b *bool) *NotificationRoleUpdate {
	if b != nil {
		nru.SetIsSystemRole(*b)
	}
	return nru
}

// SetUpdatedAt sets the "updated_at" field.
func (nru *NotificationRoleUpdate) SetUpdatedAt(t time.Time) *NotificationRoleUpdate {
	nru.mutation.SetUpdatedAt(t)
	return nru
}

// AddPermissionIDs adds the "permissions" edge to the NotificationPermission entity by IDs.
func (nru *NotificationRoleUpdate) AddPermissionIDs(ids ...uuid.UUID) *NotificationRoleUpdate {
	nru.mutation.AddPermissionIDs(ids...)
	return nru
}

// AddPermissions adds the "permissions" edges to the NotificationPermission entity.
func (nru *NotificationRoleUpdate) AddPermissions(n ...*NotificationPermission) *NotificationRoleUpdate {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nru.AddPermissionIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignments" edge to the UserRoleAssignment entity by IDs.
func (nru *NotificationRoleUpdate) AddUserAssignmentIDs(ids ...uuid.UUID) *NotificationRoleUpdate {
	nru.mutation.AddUserAssignmentIDs(ids...)
	return nru
}

// AddUserAssignments adds the "user_assignments" edges to the UserRoleAssignment entity.
func (nru *NotificationRoleUpdate) AddUserAssignments(u ...*UserRoleAssignment) *NotificationRoleUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return nru.AddUserAssignmentIDs(ids...)
}

// AddNotificationRolePermissionIDs adds the "notification_role_permissions" edge to the NotificationRolePermission entity by IDs.
func (nru *NotificationRoleUpdate) AddNotificationRolePermissionIDs(ids ...int) *NotificationRoleUpdate {
	nru.mutation.AddNotificationRolePermissionIDs(ids...)
	return nru
}

// AddNotificationRolePermissions adds the "notification_role_permissions" edges to the NotificationRolePermission entity.
func (nru *NotificationRoleUpdate) AddNotificationRolePermissions(n ...*NotificationRolePermission) *NotificationRoleUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nru.AddNotificationRolePermissionIDs(ids...)
}

// Mutation returns the NotificationRoleMutation object of the builder.
func (nru *NotificationRoleUpdate) Mutation() *NotificationRoleMutation {
	return nru.mutation
}

// ClearPermissions clears all "permissions" edges to the NotificationPermission entity.
func (nru *NotificationRoleUpdate) ClearPermissions() *NotificationRoleUpdate {
	nru.mutation.ClearPermissions()
	return nru
}

// RemovePermissionIDs removes the "permissions" edge to NotificationPermission entities by IDs.
func (nru *NotificationRoleUpdate) RemovePermissionIDs(ids ...uuid.UUID) *NotificationRoleUpdate {
	nru.mutation.RemovePermissionIDs(ids...)
	return nru
}

// RemovePermissions removes "permissions" edges to NotificationPermission entities.
func (nru *NotificationRoleUpdate) RemovePermissions(n ...*NotificationPermission) *NotificationRoleUpdate {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nru.RemovePermissionIDs(ids...)
}

// ClearUserAssignments clears all "user_assignments" edges to the UserRoleAssignment entity.
func (nru *NotificationRoleUpdate) ClearUserAssignments() *NotificationRoleUpdate {
	nru.mutation.ClearUserAssignments()
	return nru
}

// RemoveUserAssignmentIDs removes the "user_assignments" edge to UserRoleAssignment entities by IDs.
func (nru *NotificationRoleUpdate) RemoveUserAssignmentIDs(ids ...uuid.UUID) *NotificationRoleUpdate {
	nru.mutation.RemoveUserAssignmentIDs(ids...)
	return nru
}

// RemoveUserAssignments removes "user_assignments" edges to UserRoleAssignment entities.
func (nru *NotificationRoleUpdate) RemoveUserAssignments(u ...*UserRoleAssignment) *NotificationRoleUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return nru.RemoveUserAssignmentIDs(ids...)
}

// ClearNotificationRolePermissions clears all "notification_role_permissions" edges to the NotificationRolePermission entity.
func (nru *NotificationRoleUpdate) ClearNotificationRolePermissions() *NotificationRoleUpdate {
	nru.mutation.ClearNotificationRolePermissions()
	return nru
}

// RemoveNotificationRolePermissionIDs removes the "notification_role_permissions" edge to NotificationRolePermission entities by IDs.
func (nru *NotificationRoleUpdate) RemoveNotificationRolePermissionIDs(ids ...int) *NotificationRoleUpdate {
	nru.mutation.RemoveNotificationRolePermissionIDs(ids...)
	return nru
}

// RemoveNotificationRolePermissions removes "notification_role_permissions" edges to NotificationRolePermission entities.
func (nru *NotificationRoleUpdate) RemoveNotificationRolePermissions(n ...*NotificationRolePermission) *NotificationRoleUpdate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nru.RemoveNotificationRolePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nru *NotificationRoleUpdate) Save(ctx context.Context) (int, error) {
	nru.defaults()
	return withHooks(ctx, nru.sqlSave, nru.mutation, nru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nru *NotificationRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := nru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nru *NotificationRoleUpdate) Exec(ctx context.Context) error {
	_, err := nru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nru *NotificationRoleUpdate) ExecX(ctx context.Context) {
	if err := nru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nru *NotificationRoleUpdate) defaults() {
	if _, ok := nru.mutation.UpdatedAt(); !ok {
		v := notificationrole.UpdateDefaultUpdatedAt()
		nru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nru *NotificationRoleUpdate) check() error {
	if v, ok := nru.mutation.RoleCode(); ok {
		if err := notificationrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "NotificationRole.role_code": %w`, err)}
		}
	}
	if v, ok := nru.mutation.Name(); ok {
		if err := notificationrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationRole.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nru *NotificationRoleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationRoleUpdate {
	nru.modifiers = append(nru.modifiers, modifiers...)
	return nru
}

func (nru *NotificationRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationrole.Table, notificationrole.Columns, sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID))
	if ps := nru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nru.mutation.TenantID(); ok {
		_spec.SetField(notificationrole.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := nru.mutation.RoleCode(); ok {
		_spec.SetField(notificationrole.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := nru.mutation.Name(); ok {
		_spec.SetField(notificationrole.FieldName, field.TypeString, value)
	}
	if value, ok := nru.mutation.Description(); ok {
		_spec.SetField(notificationrole.FieldDescription, field.TypeString, value)
	}
	if nru.mutation.DescriptionCleared() {
		_spec.ClearField(notificationrole.FieldDescription, field.TypeString)
	}
	if value, ok := nru.mutation.IsSystemRole(); ok {
		_spec.SetField(notificationrole.FieldIsSystemRole, field.TypeBool, value)
	}
	if value, ok := nru.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if nru.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notificationrole.PermissionsTable,
			Columns: notificationrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nru.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !nru.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notificationrole.PermissionsTable,
			Columns: notificationrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nru.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notificationrole.PermissionsTable,
			Columns: notificationrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nru.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationrole.UserAssignmentsTable,
			Columns: []string{notificationrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nru.mutation.RemovedUserAssignmentsIDs(); len(nodes) > 0 && !nru.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationrole.UserAssignmentsTable,
			Columns: []string{notificationrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nru.mutation.UserAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationrole.UserAssignmentsTable,
			Columns: []string{notificationrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nru.mutation.NotificationRolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   notificationrole.NotificationRolePermissionsTable,
			Columns: []string{notificationrole.NotificationRolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nru.mutation.RemovedNotificationRolePermissionsIDs(); len(nodes) > 0 && !nru.mutation.NotificationRolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   notificationrole.NotificationRolePermissionsTable,
			Columns: []string{notificationrole.NotificationRolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nru.mutation.NotificationRolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   notificationrole.NotificationRolePermissionsTable,
			Columns: []string{notificationrole.NotificationRolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, nru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nru.mutation.done = true
	return n, nil
}

// NotificationRoleUpdateOne is the builder for updating a single NotificationRole entity.
type NotificationRoleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationRoleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTenantID sets the "tenant_id" field.
func (nruo *NotificationRoleUpdateOne) SetTenantID(u uuid.UUID) *NotificationRoleUpdateOne {
	nruo.mutation.SetTenantID(u)
	return nruo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (nruo *NotificationRoleUpdateOne) SetNillableTenantID(u *uuid.UUID) *NotificationRoleUpdateOne {
	if u != nil {
		nruo.SetTenantID(*u)
	}
	return nruo
}

// SetRoleCode sets the "role_code" field.
func (nruo *NotificationRoleUpdateOne) SetRoleCode(s string) *NotificationRoleUpdateOne {
	nruo.mutation.SetRoleCode(s)
	return nruo
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (nruo *NotificationRoleUpdateOne) SetNillableRoleCode(s *string) *NotificationRoleUpdateOne {
	if s != nil {
		nruo.SetRoleCode(*s)
	}
	return nruo
}

// SetName sets the "name" field.
func (nruo *NotificationRoleUpdateOne) SetName(s string) *NotificationRoleUpdateOne {
	nruo.mutation.SetName(s)
	return nruo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (nruo *NotificationRoleUpdateOne) SetNillableName(s *string) *NotificationRoleUpdateOne {
	if s != nil {
		nruo.SetName(*s)
	}
	return nruo
}

// SetDescription sets the "description" field.
func (nruo *NotificationRoleUpdateOne) SetDescription(s string) *NotificationRoleUpdateOne {
	nruo.mutation.SetDescription(s)
	return nruo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (nruo *NotificationRoleUpdateOne) SetNillableDescription(s *string) *NotificationRoleUpdateOne {
	if s != nil {
		nruo.SetDescription(*s)
	}
	return nruo
}

// ClearDescription clears the value of the "description" field.
func (nruo *NotificationRoleUpdateOne) ClearDescription() *NotificationRoleUpdateOne {
	nruo.mutation.ClearDescription()
	return nruo
}

// SetIsSystemRole sets the "is_system_role" field.
func (nruo *NotificationRoleUpdateOne) SetIsSystemRole(b bool) *NotificationRoleUpdateOne {
	nruo.mutation.SetIsSystemRole(b)
	return nruo
}

// SetNillableIsSystemRole sets the "is_system_role" field if the given value is not nil.
func (nruo *NotificationRoleUpdateOne) SetNillableIsSystemRole(b *bool) *NotificationRoleUpdateOne {
	if b != nil {
		nruo.SetIsSystemRole(*b)
	}
	return nruo
}

// SetUpdatedAt sets the "updated_at" field.
func (nruo *NotificationRoleUpdateOne) SetUpdatedAt(t time.Time) *NotificationRoleUpdateOne {
	nruo.mutation.SetUpdatedAt(t)
	return nruo
}

// AddPermissionIDs adds the "permissions" edge to the NotificationPermission entity by IDs.
func (nruo *NotificationRoleUpdateOne) AddPermissionIDs(ids ...uuid.UUID) *NotificationRoleUpdateOne {
	nruo.mutation.AddPermissionIDs(ids...)
	return nruo
}

// AddPermissions adds the "permissions" edges to the NotificationPermission entity.
func (nruo *NotificationRoleUpdateOne) AddPermissions(n ...*NotificationPermission) *NotificationRoleUpdateOne {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nruo.AddPermissionIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignments" edge to the UserRoleAssignment entity by IDs.
func (nruo *NotificationRoleUpdateOne) AddUserAssignmentIDs(ids ...uuid.UUID) *NotificationRoleUpdateOne {
	nruo.mutation.AddUserAssignmentIDs(ids...)
	return nruo
}

// AddUserAssignments adds the "user_assignments" edges to the UserRoleAssignment entity.
func (nruo *NotificationRoleUpdateOne) AddUserAssignments(u ...*UserRoleAssignment) *NotificationRoleUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return nruo.AddUserAssignmentIDs(ids...)
}

// AddNotificationRolePermissionIDs adds the "notification_role_permissions" edge to the NotificationRolePermission entity by IDs.
func (nruo *NotificationRoleUpdateOne) AddNotificationRolePermissionIDs(ids ...int) *NotificationRoleUpdateOne {
	nruo.mutation.AddNotificationRolePermissionIDs(ids...)
	return nruo
}

// AddNotificationRolePermissions adds the "notification_role_permissions" edges to the NotificationRolePermission entity.
func (nruo *NotificationRoleUpdateOne) AddNotificationRolePermissions(n ...*NotificationRolePermission) *NotificationRoleUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nruo.AddNotificationRolePermissionIDs(ids...)
}

// Mutation returns the NotificationRoleMutation object of the builder.
func (nruo *NotificationRoleUpdateOne) Mutation() *NotificationRoleMutation {
	return nruo.mutation
}

// ClearPermissions clears all "permissions" edges to the NotificationPermission entity.
func (nruo *NotificationRoleUpdateOne) ClearPermissions() *NotificationRoleUpdateOne {
	nruo.mutation.ClearPermissions()
	return nruo
}

// RemovePermissionIDs removes the "permissions" edge to NotificationPermission entities by IDs.
func (nruo *NotificationRoleUpdateOne) RemovePermissionIDs(ids ...uuid.UUID) *NotificationRoleUpdateOne {
	nruo.mutation.RemovePermissionIDs(ids...)
	return nruo
}

// RemovePermissions removes "permissions" edges to NotificationPermission entities.
func (nruo *NotificationRoleUpdateOne) RemovePermissions(n ...*NotificationPermission) *NotificationRoleUpdateOne {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nruo.RemovePermissionIDs(ids...)
}

// ClearUserAssignments clears all "user_assignments" edges to the UserRoleAssignment entity.
func (nruo *NotificationRoleUpdateOne) ClearUserAssignments() *NotificationRoleUpdateOne {
	nruo.mutation.ClearUserAssignments()
	return nruo
}

// RemoveUserAssignmentIDs removes the "user_assignments" edge to UserRoleAssignment entities by IDs.
func (nruo *NotificationRoleUpdateOne) RemoveUserAssignmentIDs(ids ...uuid.UUID) *NotificationRoleUpdateOne {
	nruo.mutation.RemoveUserAssignmentIDs(ids...)
	return nruo
}

// RemoveUserAssignments removes "user_assignments" edges to UserRoleAssignment entities.
func (nruo *NotificationRoleUpdateOne) RemoveUserAssignments(u ...*UserRoleAssignment) *NotificationRoleUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return nruo.RemoveUserAssignmentIDs(ids...)
}

// ClearNotificationRolePermissions clears all "notification_role_permissions" edges to the NotificationRolePermission entity.
func (nruo *NotificationRoleUpdateOne) ClearNotificationRolePermissions() *NotificationRoleUpdateOne {
	nruo.mutation.ClearNotificationRolePermissions()
	return nruo
}

// RemoveNotificationRolePermissionIDs removes the "notification_role_permissions" edge to NotificationRolePermission entities by IDs.
func (nruo *NotificationRoleUpdateOne) RemoveNotificationRolePermissionIDs(ids ...int) *NotificationRoleUpdateOne {
	nruo.mutation.RemoveNotificationRolePermissionIDs(ids...)
	return nruo
}

// RemoveNotificationRolePermissions removes "notification_role_permissions" edges to NotificationRolePermission entities.
func (nruo *NotificationRoleUpdateOne) RemoveNotificationRolePermissions(n ...*NotificationRolePermission) *NotificationRoleUpdateOne {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nruo.RemoveNotificationRolePermissionIDs(ids...)
}

// Where appends a list predicates to the NotificationRoleUpdate builder.
func (nruo *NotificationRoleUpdateOne) Where(ps ...predicate.NotificationRole) *NotificationRoleUpdateOne {
	nruo.mutation.Where(ps...)
	return nruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nruo *NotificationRoleUpdateOne) Select(field string, fields ...string) *NotificationRoleUpdateOne {
	nruo.fields = append([]string{field}, fields...)
	return nruo
}

// Save executes the query and returns the updated NotificationRole entity.
func (nruo *NotificationRoleUpdateOne) Save(ctx context.Context) (*NotificationRole, error) {
	nruo.defaults()
	return withHooks(ctx, nruo.sqlSave, nruo.mutation, nruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nruo *NotificationRoleUpdateOne) SaveX(ctx context.Context) *NotificationRole {
	node, err := nruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nruo *NotificationRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := nruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nruo *NotificationRoleUpdateOne) ExecX(ctx context.Context) {
	if err := nruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nruo *NotificationRoleUpdateOne) defaults() {
	if _, ok := nruo.mutation.UpdatedAt(); !ok {
		v := notificationrole.UpdateDefaultUpdatedAt()
		nruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nruo *NotificationRoleUpdateOne) check() error {
	if v, ok := nruo.mutation.RoleCode(); ok {
		if err := notificationrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "NotificationRole.role_code": %w`, err)}
		}
	}
	if v, ok := nruo.mutation.Name(); ok {
		if err := notificationrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationRole.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nruo *NotificationRoleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationRoleUpdateOne {
	nruo.modifiers = append(nruo.modifiers, modifiers...)
	return nruo
}

func (nruo *NotificationRoleUpdateOne) sqlSave(ctx context.Context) (_node *NotificationRole, err error) {
	if err := nruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationrole.Table, notificationrole.Columns, sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID))
	id, ok := nruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationrole.FieldID)
		for _, f := range fields {
			if !notificationrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nruo.mutation.TenantID(); ok {
		_spec.SetField(notificationrole.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := nruo.mutation.RoleCode(); ok {
		_spec.SetField(notificationrole.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := nruo.mutation.Name(); ok {
		_spec.SetField(notificationrole.FieldName, field.TypeString, value)
	}
	if value, ok := nruo.mutation.Description(); ok {
		_spec.SetField(notificationrole.FieldDescription, field.TypeString, value)
	}
	if nruo.mutation.DescriptionCleared() {
		_spec.ClearField(notificationrole.FieldDescription, field.TypeString)
	}
	if value, ok := nruo.mutation.IsSystemRole(); ok {
		_spec.SetField(notificationrole.FieldIsSystemRole, field.TypeBool, value)
	}
	if value, ok := nruo.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if nruo.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notificationrole.PermissionsTable,
			Columns: notificationrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nruo.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !nruo.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notificationrole.PermissionsTable,
			Columns: notificationrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nruo.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notificationrole.PermissionsTable,
			Columns: notificationrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nruo.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationrole.UserAssignmentsTable,
			Columns: []string{notificationrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nruo.mutation.RemovedUserAssignmentsIDs(); len(nodes) > 0 && !nruo.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationrole.UserAssignmentsTable,
			Columns: []string{notificationrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nruo.mutation.UserAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationrole.UserAssignmentsTable,
			Columns: []string{notificationrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nruo.mutation.NotificationRolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   notificationrole.NotificationRolePermissionsTable,
			Columns: []string{notificationrole.NotificationRolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nruo.mutation.RemovedNotificationRolePermissionsIDs(); len(nodes) > 0 && !nruo.mutation.NotificationRolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   notificationrole.NotificationRolePermissionsTable,
			Columns: []string{notificationrole.NotificationRolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nruo.mutation.NotificationRolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   notificationrole.NotificationRolePermissionsTable,
			Columns: []string{notificationrole.NotificationRolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nruo.modifiers...)
	_node = &NotificationRole{config: nruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nruo.mutation.done = true
	return _node, nil
}
