// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/notificationpermission"
	"github.com/bengobox/notifications-api/internal/ent/notificationrole"
	"github.com/bengobox/notifications-api/internal/ent/notificationrolepermission"
	"github.com/bengobox/notifications-api/internal/ent/userroleassignment"
	"github.com/google/uuid"
)

// NotificationRoleCreate is the builder for creating a NotificationRole entity.
type NotificationRoleCreate struct {
	config
	mutation *NotificationRoleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (nrc *NotificationRoleCreate) SetTenantID(u uuid.UUID) *NotificationRoleCreate {
	nrc.mutation.SetTenantID(u)
	return nrc
}

// SetRoleCode sets the "role_code" field.
func (nrc *NotificationRoleCreate) SetRoleCode(s string) *NotificationRoleCreate {
	nrc.mutation.SetRoleCode(s)
	return nrc
}

// SetName sets the "name" field.
func (nrc *NotificationRoleCreate) SetName(s string) *NotificationRoleCreate {
	nrc.mutation.SetName(s)
	return nrc
}

// SetDescription sets the "description" field.
func (nrc *NotificationRoleCreate) SetDescription(s string) *NotificationRoleCreate {
	nrc.mutation.SetDescription(s)
	return nrc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (nrc *NotificationRoleCreate) SetNillableDescription(s *string) *NotificationRoleCreate {
	if s != nil {
		nrc.SetDescription(*s)
	}
	return nrc
}

// SetIsSystemRole sets the "is_system_role" field.
func (nrc *NotificationRoleCreate) SetIsSystemRole(b bool) *NotificationRoleCreate {
	nrc.mutation.SetIsSystemRole(b)
	return nrc
}

// SetNillableIsSystemRole sets the "is_system_role" field if the given value is not nil.
func (nrc *NotificationRoleCreate) SetNillableIsSystemRole(b *bool) *NotificationRoleCreate {
	if b != nil {
		nrc.SetIsSystemRole(*b)
	}
	return nrc
}

// SetCreatedAt sets the "created_at" field.
func (nrc *NotificationRoleCreate) SetCreatedAt(t time.Time) *NotificationRoleCreate {
	nrc.mutation.SetCreatedAt(t)
	return nrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nrc *NotificationRoleCreate) SetNillableCreatedAt(t *time.Time) *NotificationRoleCreate {
	if t != nil {
		nrc.SetCreatedAt(*t)
	}
	return nrc
}

// SetUpdatedAt sets the "updated_at" field.
func (nrc *NotificationRoleCreate) SetUpdatedAt(t time.Time) *NotificationRoleCreate {
	nrc.mutation.SetUpdatedAt(t)
	return nrc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (nrc *NotificationRoleCreate) SetNillableUpdatedAt(t *time.Time) *NotificationRoleCreate {
	if t != nil {
		nrc.SetUpdatedAt(*t)
	}
	return nrc
}

// SetID sets the "id" field.
func (nrc *NotificationRoleCreate) SetID(u uuid.UUID) *NotificationRoleCreate {
	nrc.mutation.SetID(u)
	return nrc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (nrc *NotificationRoleCreate) SetNillableID(u *uuid.UUID) *NotificationRoleCreate {
	if u != nil {
		nrc.SetID(*u)
	}
	return nrc
}

// AddPermissionIDs adds the "permissions" edge to the NotificationPermission entity by IDs.
func (nrc *NotificationRoleCreate) AddPermissionIDs(ids ...uuid.UUID) *NotificationRoleCreate {
	nrc.mutation.AddPermissionIDs(ids...)
	return nrc
}

// AddPermissions adds the "permissions" edges to the NotificationPermission entity.
func (nrc *NotificationRoleCreate) AddPermissions(n ...*NotificationPermission) *NotificationRoleCreate {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nrc.AddPermissionIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignments" edge to the UserRoleAssignment entity by IDs.
func (nrc *NotificationRoleCreate) AddUserAssignmentIDs(ids ...uuid.UUID) *NotificationRoleCreate {
	nrc.mutation.AddUserAssignmentIDs(ids...)
	return nrc
}

// AddUserAssignments adds the "user_assignments" edges to the UserRoleAssignment entity.
func (nrc *NotificationRoleCreate) AddUserAssignments(u ...*UserRoleAssignment) *NotificationRoleCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return nrc.AddUserAssignmentIDs(ids...)
}

// AddNotificationRolePermissionIDs adds the "notification_role_permissions" edge to the NotificationRolePermission entity by IDs.
func (nrc *NotificationRoleCreate) AddNotificationRolePermissionIDs(ids ...int) *NotificationRoleCreate {
	nrc.mutation.AddNotificationRolePermissionIDs(ids...)
	return nrc
}

// AddNotificationRolePermissions adds the "notification_role_permissions" edges to the NotificationRolePermission entity.
func (nrc *NotificationRoleCreate) AddNotificationRolePermissions(n ...*NotificationRolePermission) *NotificationRoleCreate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return nrc.AddNotificationRolePermissionIDs(ids...)
}

// Mutation returns the NotificationRoleMutation object of the builder.
func (nrc *NotificationRoleCreate) Mutation() *NotificationRoleMutation {
	return nrc.mutation
}

// Save creates the NotificationRole in the database.
func (nrc *NotificationRoleCreate) Save(ctx context.Context) (*NotificationRole, error) {
	nrc.defaults()
	return withHooks(ctx, nrc.sqlSave, nrc.mutation, nrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nrc *NotificationRoleCreate) SaveX(ctx context.Context) *NotificationRole {
	v, err := nrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nrc *NotificationRoleCreate) Exec(ctx context.Context) error {
	_, err := nrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nrc *NotificationRoleCreate) ExecX(ctx context.Context) {
	if err := nrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nrc *NotificationRoleCreate) defaults() {
	if _, ok := nrc.mutation.IsSystemRole(); !ok {
		v := notificationrole.DefaultIsSystemRole
		nrc.mutation.SetIsSystemRole(v)
	}
	if _, ok := nrc.mutation.CreatedAt(); !ok {
		v := notificationrole.DefaultCreatedAt()
		nrc.mutation.SetCreatedAt(v)
	}
	if _, ok := nrc.mutation.UpdatedAt(); !ok {
		v := notificationrole.DefaultUpdatedAt()
		nrc.mutation.SetUpdatedAt(v)
	}
	if _, ok := nrc.mutation.ID(); !ok {
		v := notificationrole.DefaultID()
		nrc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nrc *NotificationRoleCreate) check() error {
	if _, ok := nrc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "NotificationRole.tenant_id"`)}
	}
	if _, ok := nrc.mutation.RoleCode(); !ok {
		return &ValidationError{Name: "role_code", err: errors.New(`ent: missing required field "NotificationRole.role_code"`)}
	}
	if v, ok := nrc.mutation.RoleCode(); ok {
		if err := notificationrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "NotificationRole.role_code": %w`, err)}
		}
	}
	if _, ok := nrc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "NotificationRole.name"`)}
	}
	if v, ok := nrc.mutation.Name(); ok {
		if err := notificationrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationRole.name": %w`, err)}
		}
	}
	if _, ok := nrc.mutation.IsSystemRole(); !ok {
		return &ValidationError{Name: "is_system_role", err: errors.New(`ent: missing required field "NotificationRole.is_system_role"`)}
	}
	if _, ok := nrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationRole.created_at"`)}
	}
	if _, ok := nrc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationRole.updated_at"`)}
	}
	return nil
}

func (nrc *NotificationRoleCreate) sqlSave(ctx context.Context) (*NotificationRole, error) {
	if err := nrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	nrc.mutation.id = &_node.ID
	nrc.mutation.done = true
	return _node, nil
}

func (nrc *NotificationRoleCreate) createSpec() (*NotificationRole, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationRole{config: nrc.config}
		_spec = sqlgraph.NewCreateSpec(notificationrole.Table, sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = nrc.conflict
	if id, ok := nrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := nrc.mutation.TenantID(); ok {
		_spec.SetField(notificationrole.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := nrc.mutation.RoleCode(); ok {
		_spec.SetField(notificationrole.FieldRoleCode, field.TypeString, value)
		_node.RoleCode = value
	}
	if value, ok := nrc.mutation.Name(); ok {
		_spec.SetField(notificationrole.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := nrc.mutation.Description(); ok {
		_spec.SetField(notificationrole.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := nrc.mutation.IsSystemRole(); ok {
		_spec.SetField(notificationrole.FieldIsSystemRole, field.TypeBool, value)
		_node.IsSystemRole = value
	}
	if value, ok := nrc.mutation.CreatedAt(); ok {
		_spec.SetField(notificationrole.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := nrc.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationrole.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := nrc.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   notificationrole.PermissionsTable,
			Columns: notificationrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nrc.mutation.UserAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationrole.UserAssignmentsTable,
			Columns: []string{notificationrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := nrc.mutation.NotificationRolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   notificationrole.NotificationRolePermissionsTable,
			Columns: []string{notificationrole.NotificationRolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationRole.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationRoleUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (nrc *NotificationRoleCreate) OnConflict(opts ...sql.ConflictOption) *NotificationRoleUpsertOne {
	nrc.conflict = opts
	return &NotificationRoleUpsertOne{
		create: nrc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nrc *NotificationRoleCreate) OnConflictColumns(columns ...string) *NotificationRoleUpsertOne {
	nrc.conflict = append(nrc.conflict, sql.ConflictColumns(columns...))
	return &NotificationRoleUpsertOne{
		create: nrc,
	}
}

type (
	// NotificationRoleUpsertOne is the builder for "upsert"-ing
	//  one NotificationRole node.
	NotificationRoleUpsertOne struct {
		create *NotificationRoleCreate
	}

	// NotificationRoleUpsert is the "OnConflict" setter.
	NotificationRoleUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *NotificationRoleUpsert) SetTenantID(v uuid.UUID) *NotificationRoleUpsert {
	u.Set(notificationrole.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NotificationRoleUpsert) UpdateTenantID() *NotificationRoleUpsert {
	u.SetExcluded(notificationrole.FieldTenantID)
	return u
}

// SetRoleCode sets the "role_code" field.
func (u *NotificationRoleUpsert) SetRoleCode(v string) *NotificationRoleUpsert {
	u.Set(notificationrole.FieldRoleCode, v)
	return u
}

// UpdateRoleCode sets the "role_code" field to the value that was provided on create.
func (u *NotificationRoleUpsert) UpdateRoleCode() *NotificationRoleUpsert {
	u.SetExcluded(notificationrole.FieldRoleCode)
	return u
}

// SetName sets the "name" field.
func (u *NotificationRoleUpsert) SetName(v string) *NotificationRoleUpsert {
	u.Set(notificationrole.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotificationRoleUpsert) UpdateName() *NotificationRoleUpsert {
	u.SetExcluded(notificationrole.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *NotificationRoleUpsert) SetDescription(v string) *NotificationRoleUpsert {
	u.Set(notificationrole.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *NotificationRoleUpsert) UpdateDescription() *NotificationRoleUpsert {
	u.SetExcluded(notificationrole.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *NotificationRoleUpsert) ClearDescription() *NotificationRoleUpsert {
	u.SetNull(notificationrole.FieldDescription)
	return u
}

// SetIsSystemRole sets the "is_system_role" field.
func (u *NotificationRoleUpsert) SetIsSystemRole(v bool) *NotificationRoleUpsert {
	u.Set(notificationrole.FieldIsSystemRole, v)
	return u
}

// UpdateIsSystemRole sets the "is_system_role" field to the value that was provided on create.
func (u *NotificationRoleUpsert) UpdateIsSystemRole() *NotificationRoleUpsert {
	u.SetExcluded(notificationrole.FieldIsSystemRole)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationRoleUpsert) SetUpdatedAt(v time.Time) *NotificationRoleUpsert {
	u.Set(notificationrole.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationRoleUpsert) UpdateUpdatedAt() *NotificationRoleUpsert {
	u.SetExcluded(notificationrole.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationrole.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationRoleUpsertOne) UpdateNewValues() *NotificationRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationrole.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(notificationrole.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationRole.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationRoleUpsertOne) Ignore() *NotificationRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationRoleUpsertOne) DoNothing() *NotificationRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationRoleCreate.OnConflict
// documentation for more info.
func (u *NotificationRoleUpsertOne) Update(set func(*NotificationRoleUpsert)) *NotificationRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationRoleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *NotificationRoleUpsertOne) SetTenantID(v uuid.UUID) *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NotificationRoleUpsertOne) UpdateTenantID() *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateTenantID()
	})
}

// SetRoleCode sets the "role_code" field.
func (u *NotificationRoleUpsertOne) SetRoleCode(v string) *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetRoleCode(v)
	})
}

// UpdateRoleCode sets the "role_code" field to the value that was provided on create.
func (u *NotificationRoleUpsertOne) UpdateRoleCode() *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateRoleCode()
	})
}

// SetName sets the "name" field.
func (u *NotificationRoleUpsertOne) SetName(v string) *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotificationRoleUpsertOne) UpdateName() *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *NotificationRoleUpsertOne) SetDescription(v string) *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *NotificationRoleUpsertOne) UpdateDescription() *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *NotificationRoleUpsertOne) ClearDescription() *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.ClearDescription()
	})
}

// SetIsSystemRole sets the "is_system_role" field.
func (u *NotificationRoleUpsertOne) SetIsSystemRole(v bool) *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetIsSystemRole(v)
	})
}

// UpdateIsSystemRole sets the "is_system_role" field to the value that was provided on create.
func (u *NotificationRoleUpsertOne) UpdateIsSystemRole() *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateIsSystemRole()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationRoleUpsertOne) SetUpdatedAt(v time.Time) *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationRoleUpsertOne) UpdateUpdatedAt() *NotificationRoleUpsertOne {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NotificationRoleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationRoleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationRoleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationRoleUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NotificationRoleUpsertOne.ID is not supported by MySQL driver. Use NotificationRoleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationRoleUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationRoleCreateBulk is the builder for creating many NotificationRole entities in bulk.
type NotificationRoleCreateBulk struct {
	config
	err      error
	builders []*NotificationRoleCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationRole entities in the database.
func (nrcb *NotificationRoleCreateBulk) Save(ctx context.Context) ([]*NotificationRole, error) {
	if nrcb.err != nil {
		return nil, nrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(nrcb.builders))
	nodes := make([]*NotificationRole, len(nrcb.builders))
	mutators := make([]Mutator, len(nrcb.builders))
	for i := range nrcb.builders {
		func(i int, root context.Context) {
			builder := nrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = nrcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nrcb *NotificationRoleCreateBulk) SaveX(ctx context.Context) []*NotificationRole {
	v, err := nrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nrcb *NotificationRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := nrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nrcb *NotificationRoleCreateBulk) ExecX(ctx context.Context) {
	if err := nrcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationRole.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationRoleUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (nrcb *NotificationRoleCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationRoleUpsertBulk {
	nrcb.conflict = opts
	return &NotificationRoleUpsertBulk{
		create: nrcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nrcb *NotificationRoleCreateBulk) OnConflictColumns(columns ...string) *NotificationRoleUpsertBulk {
	nrcb.conflict = append(nrcb.conflict, sql.ConflictColumns(columns...))
	return &NotificationRoleUpsertBulk{
		create: nrcb,
	}
}

// NotificationRoleUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationRole nodes.
type NotificationRoleUpsertBulk struct {
	create *NotificationRoleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationrole.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationRoleUpsertBulk) UpdateNewValues() *NotificationRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationrole.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(notificationrole.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationRole.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationRoleUpsertBulk) Ignore() *NotificationRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationRoleUpsertBulk) DoNothing() *NotificationRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationRoleCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationRoleUpsertBulk) Update(set func(*NotificationRoleUpsert)) *NotificationRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationRoleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *NotificationRoleUpsertBulk) SetTenantID(v uuid.UUID) *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NotificationRoleUpsertBulk) UpdateTenantID() *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateTenantID()
	})
}

// SetRoleCode sets the "role_code" field.
func (u *NotificationRoleUpsertBulk) SetRoleCode(v string) *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetRoleCode(v)
	})
}

// UpdateRoleCode sets the "role_code" field to the value that was provided on create.
func (u *NotificationRoleUpsertBulk) UpdateRoleCode() *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateRoleCode()
	})
}

// SetName sets the "name" field.
func (u *NotificationRoleUpsertBulk) SetName(v string) *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotificationRoleUpsertBulk) UpdateName() *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *NotificationRoleUpsertBulk) SetDescription(v string) *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *NotificationRoleUpsertBulk) UpdateDescription() *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *NotificationRoleUpsertBulk) ClearDescription() *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.ClearDescription()
	})
}

// SetIsSystemRole sets the "is_system_role" field.
func (u *NotificationRoleUpsertBulk) SetIsSystemRole(v bool) *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetIsSystemRole(v)
	})
}

// UpdateIsSystemRole sets the "is_system_role" field to the value that was provided on create.
func (u *NotificationRoleUpsertBulk) UpdateIsSystemRole() *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateIsSystemRole()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationRoleUpsertBulk) SetUpdatedAt(v time.Time) *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationRoleUpsertBulk) UpdateUpdatedAt() *NotificationRoleUpsertBulk {
	return u.Update(func(s *NotificationRoleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NotificationRoleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationRoleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationRoleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationRoleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
