// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/notificationpermission"
	"github.com/bengobox/notifications-api/internal/ent/notificationrole"
	"github.com/bengobox/notifications-api/internal/ent/notificationrolepermission"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// NotificationRolePermissionUpdate is the builder for updating NotificationRolePermission entities.
type NotificationRolePermissionUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationRolePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationRolePermissionUpdate builder.
func (nrpu *NotificationRolePermissionUpdate) Where(ps ...predicate.NotificationRolePermission) *NotificationRolePermissionUpdate {
	nrpu.mutation.Where(ps...)
	return nrpu
}

// SetRoleID sets the "role_id" field.
func (nrpu *NotificationRolePermissionUpdate) SetRoleID(u uuid.UUID) *NotificationRolePermissionUpdate {
	nrpu.mutation.SetRoleID(u)
	return nrpu
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (nrpu *NotificationRolePermissionUpdate) SetNillableRoleID(u *uuid.UUID) *NotificationRolePermissionUpdate {
	if u != nil {
		nrpu.SetRoleID(*u)
	}
	return nrpu
}

// SetPermissionID sets the "permission_id" field.
func (nrpu *NotificationRolePermissionUpdate) SetPermissionID(u uuid.UUID) *NotificationRolePermissionUpdate {
	nrpu.mutation.SetPermissionID(u)
	return nrpu
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (nrpu *NotificationRolePermissionUpdate) SetNillablePermissionID(u *uuid.UUID) *NotificationRolePermissionUpdate {
	if u != nil {
		nrpu.SetPermissionID(*u)
	}
	return nrpu
}

// SetRole sets the "role" edge to the NotificationRole entity.
func (nrpu *NotificationRolePermissionUpdate) SetRole(n *NotificationRole) *NotificationRolePermissionUpdate {
	return nrpu.SetRoleID(n.ID)
}

// SetPermission sets the "permission" edge to the NotificationPermission entity.
func (nrpu *NotificationRolePermissionUpdate) SetPermission(n *NotificationPermission) *NotificationRolePermissionUpdate {
	return nrpu.SetPermissionID(n.ID)
}

// Mutation returns the NotificationRolePermissionMutation object of the builder.
func (nrpu *NotificationRolePermissionUpdate) Mutation() *NotificationRolePermissionMutation {
	return nrpu.mutation
}

// ClearRole clears the "role" edge to the NotificationRole entity.
func (nrpu *NotificationRolePermissionUpdate) ClearRole() *NotificationRolePermissionUpdate {
	nrpu.mutation.ClearRole()
	return nrpu
}

// ClearPermission clears the "permission" edge to the NotificationPermission entity.
func (nrpu *NotificationRolePermissionUpdate) ClearPermission() *NotificationRolePermissionUpdate {
	nrpu.mutation.ClearPermission()
	return nrpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nrpu *NotificationRolePermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, nrpu.sqlSave, nrpu.mutation, nrpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nrpu *NotificationRolePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := nrpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nrpu *NotificationRolePermissionUpdate) Exec(ctx context.Context) error {
	_, err := nrpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nrpu *NotificationRolePermissionUpdate) ExecX(ctx context.Context) {
	if err := nrpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nrpu *NotificationRolePermissionUpdate) check() error {
	if _, ok := nrpu.mutation.RoleID(); nrpu.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "NotificationRolePermission.role"`)
	}
	if _, ok := nrpu.mutation.PermissionID(); nrpu.mutation.PermissionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "NotificationRolePermission.permission"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nrpu *NotificationRolePermissionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationRolePermissionUpdate {
	nrpu.modifiers = append(nrpu.modifiers, modifiers...)
	return nrpu
}

func (nrpu *NotificationRolePermissionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nrpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationrolepermission.Table, notificationrolepermission.Columns, sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt))
	if ps := nrpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if nrpu.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nrpu.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nrpu.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nrpu.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nrpu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, nrpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nrpu.mutation.done = true
	return n, nil
}

// NotificationRolePermissionUpdateOne is the builder for updating a single NotificationRolePermission entity.
type NotificationRolePermissionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationRolePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRoleID sets the "role_id" field.
func (nrpuo *NotificationRolePermissionUpdateOne) SetRoleID(u uuid.UUID) *NotificationRolePermissionUpdateOne {
	nrpuo.mutation.SetRoleID(u)
	return nrpuo
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (nrpuo *NotificationRolePermissionUpdateOne) SetNillableRoleID(u *uuid.UUID) *NotificationRolePermissionUpdateOne {
	if u != nil {
		nrpuo.SetRoleID(*u)
	}
	return nrpuo
}

// SetPermissionID sets the "permission_id" field.
func (nrpuo *NotificationRolePermissionUpdateOne) SetPermissionID(u uuid.UUID) *NotificationRolePermissionUpdateOne {
	nrpuo.mutation.SetPermissionID(u)
	return nrpuo
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (nrpuo *NotificationRolePermissionUpdateOne) SetNillablePermissionID(u *uuid.UUID) *NotificationRolePermissionUpdateOne {
	if u != nil {
		nrpuo.SetPermissionID(*u)
	}
	return nrpuo
}

// SetRole sets the "role" edge to the NotificationRole entity.
func (nrpuo *NotificationRolePermissionUpdateOne) SetRole(n *NotificationRole) *NotificationRolePermissionUpdateOne {
	return nrpuo.SetRoleID(n.ID)
}

// SetPermission sets the "permission" edge to the NotificationPermission entity.
func (nrpuo *NotificationRolePermissionUpdateOne) SetPermission(n *NotificationPermission) *NotificationRolePermissionUpdateOne {
	return nrpuo.SetPermissionID(n.ID)
}

// Mutation returns the NotificationRolePermissionMutation object of the builder.
func (nrpuo *NotificationRolePermissionUpdateOne) Mutation() *NotificationRolePermissionMutation {
	return nrpuo.mutation
}

// ClearRole clears the "role" edge to the NotificationRole entity.
func (nrpuo *NotificationRolePermissionUpdateOne) ClearRole() *NotificationRolePermissionUpdateOne {
	nrpuo.mutation.ClearRole()
	return nrpuo
}

// ClearPermission clears the "permission" edge to the NotificationPermission entity.
func (nrpuo *NotificationRolePermissionUpdateOne) ClearPermission() *NotificationRolePermissionUpdateOne {
	nrpuo.mutation.ClearPermission()
	return nrpuo
}

// Where appends a list predicates to the NotificationRolePermissionUpdate builder.
func (nrpuo *NotificationRolePermissionUpdateOne) Where(ps ...predicate.NotificationRolePermission) *NotificationRolePermissionUpdateOne {
	nrpuo.mutation.Where(ps...)
	return nrpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nrpuo *NotificationRolePermissionUpdateOne) Select(field string, fields ...string) *NotificationRolePermissionUpdateOne {
	nrpuo.fields = append([]string{field}, fields...)
	return nrpuo
}

// Save executes the query and returns the updated NotificationRolePermission entity.
func (nrpuo *NotificationRolePermissionUpdateOne) Save(ctx context.Context) (*NotificationRolePermission, error) {
	return withHooks(ctx, nrpuo.sqlSave, nrpuo.mutation, nrpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nrpuo *NotificationRolePermissionUpdateOne) SaveX(ctx context.Context) *NotificationRolePermission {
	node, err := nrpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nrpuo *NotificationRolePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := nrpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nrpuo *NotificationRolePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := nrpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nrpuo *NotificationRolePermissionUpdateOne) check() error {
	if _, ok := nrpuo.mutation.RoleID(); nrpuo.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "NotificationRolePermission.role"`)
	}
	if _, ok := nrpuo.mutation.PermissionID(); nrpuo.mutation.PermissionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "NotificationRolePermission.permission"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nrpuo *NotificationRolePermissionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationRolePermissionUpdateOne {
	nrpuo.modifiers = append(nrpuo.modifiers, modifiers...)
	return nrpuo
}

func (nrpuo *NotificationRolePermissionUpdateOne) sqlSave(ctx context.Context) (_node *NotificationRolePermission, err error) {
	if err := nrpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationrolepermission.Table, notificationrolepermission.Columns, sqlgraph.NewFieldSpec(notificationrolepermission.FieldID, field.TypeInt))
	id, ok := nrpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationRolePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nrpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationrolepermission.FieldID)
		for _, f := range fields {
			if !notificationrolepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationrolepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nrpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if nrpuo.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nrpuo.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.RoleTable,
			Columns: []string{notificationrolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nrpuo.mutation.PermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nrpuo.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationrolepermission.PermissionTable,
			Columns: []string{notificationrolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationpermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nrpuo.modifiers...)
	_node = &NotificationRolePermission{config: nrpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nrpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationrolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nrpuo.mutation.done = true
	return _node, nil
}
