// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/providersetting"
)

// ProviderSettingCreate is the builder for creating a ProviderSetting entity.
type ProviderSettingCreate struct {
	config
	mutation *ProviderSettingMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (psc *ProviderSettingCreate) SetTenantID(s string) *ProviderSettingCreate {
	psc.mutation.SetTenantID(s)
	return psc
}

// SetChannel sets the "channel" field.
func (psc *ProviderSettingCreate) SetChannel(s string) *ProviderSettingCreate {
	psc.mutation.SetChannel(s)
	return psc
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableChannel(s *string) *ProviderSettingCreate {
	if s != nil {
		psc.SetChannel(*s)
	}
	return psc
}

// SetProvider sets the "provider" field.
func (psc *ProviderSettingCreate) SetProvider(s string) *ProviderSettingCreate {
	psc.mutation.SetProvider(s)
	return psc
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableProvider(s *string) *ProviderSettingCreate {
	if s != nil {
		psc.SetProvider(*s)
	}
	return psc
}

// SetProviderType sets the "provider_type" field.
func (psc *ProviderSettingCreate) SetProviderType(s string) *ProviderSettingCreate {
	psc.mutation.SetProviderType(s)
	return psc
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableProviderType(s *string) *ProviderSettingCreate {
	if s != nil {
		psc.SetProviderType(*s)
	}
	return psc
}

// SetProviderName sets the "provider_name" field.
func (psc *ProviderSettingCreate) SetProviderName(s string) *ProviderSettingCreate {
	psc.mutation.SetProviderName(s)
	return psc
}

// SetNillableProviderName sets the "provider_name" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableProviderName(s *string) *ProviderSettingCreate {
	if s != nil {
		psc.SetProviderName(*s)
	}
	return psc
}

// SetKey sets the "key" field.
func (psc *ProviderSettingCreate) SetKey(s string) *ProviderSettingCreate {
	psc.mutation.SetKey(s)
	return psc
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableKey(s *string) *ProviderSettingCreate {
	if s != nil {
		psc.SetKey(*s)
	}
	return psc
}

// SetValue sets the "value" field.
func (psc *ProviderSettingCreate) SetValue(s string) *ProviderSettingCreate {
	psc.mutation.SetValue(s)
	return psc
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableValue(s *string) *ProviderSettingCreate {
	if s != nil {
		psc.SetValue(*s)
	}
	return psc
}

// SetDescription sets the "description" field.
func (psc *ProviderSettingCreate) SetDescription(s string) *ProviderSettingCreate {
	psc.mutation.SetDescription(s)
	return psc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableDescription(s *string) *ProviderSettingCreate {
	if s != nil {
		psc.SetDescription(*s)
	}
	return psc
}

// SetIsEncrypted sets the "is_encrypted" field.
func (psc *ProviderSettingCreate) SetIsEncrypted(b bool) *ProviderSettingCreate {
	psc.mutation.SetIsEncrypted(b)
	return psc
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableIsEncrypted(b *bool) *ProviderSettingCreate {
	if b != nil {
		psc.SetIsEncrypted(*b)
	}
	return psc
}

// SetIsPlatform sets the "is_platform" field.
func (psc *ProviderSettingCreate) SetIsPlatform(b bool) *ProviderSettingCreate {
	psc.mutation.SetIsPlatform(b)
	return psc
}

// SetNillableIsPlatform sets the "is_platform" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableIsPlatform(b *bool) *ProviderSettingCreate {
	if b != nil {
		psc.SetIsPlatform(*b)
	}
	return psc
}

// SetIsActive sets the "is_active" field.
func (psc *ProviderSettingCreate) SetIsActive(b bool) *ProviderSettingCreate {
	psc.mutation.SetIsActive(b)
	return psc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableIsActive(b *bool) *ProviderSettingCreate {
	if b != nil {
		psc.SetIsActive(*b)
	}
	return psc
}

// SetStatus sets the "status" field.
func (psc *ProviderSettingCreate) SetStatus(s string) *ProviderSettingCreate {
	psc.mutation.SetStatus(s)
	return psc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (psc *ProviderSettingCreate) SetNillableStatus(s *string) *ProviderSettingCreate {
	if s != nil {
		psc.SetStatus(*s)
	}
	return psc
}

// Mutation returns the ProviderSettingMutation object of the builder.
func (psc *ProviderSettingCreate) Mutation() *ProviderSettingMutation {
	return psc.mutation
}

// Save creates the ProviderSetting in the database.
func (psc *ProviderSettingCreate) Save(ctx context.Context) (*ProviderSetting, error) {
	psc.defaults()
	return withHooks(ctx, psc.sqlSave, psc.mutation, psc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (psc *ProviderSettingCreate) SaveX(ctx context.Context) *ProviderSetting {
	v, err := psc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psc *ProviderSettingCreate) Exec(ctx context.Context) error {
	_, err := psc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psc *ProviderSettingCreate) ExecX(ctx context.Context) {
	if err := psc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psc *ProviderSettingCreate) defaults() {
	if _, ok := psc.mutation.IsEncrypted(); !ok {
		v := providersetting.DefaultIsEncrypted
		psc.mutation.SetIsEncrypted(v)
	}
	if _, ok := psc.mutation.IsPlatform(); !ok {
		v := providersetting.DefaultIsPlatform
		psc.mutation.SetIsPlatform(v)
	}
	if _, ok := psc.mutation.IsActive(); !ok {
		v := providersetting.DefaultIsActive
		psc.mutation.SetIsActive(v)
	}
	if _, ok := psc.mutation.Status(); !ok {
		v := providersetting.DefaultStatus
		psc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psc *ProviderSettingCreate) check() error {
	if _, ok := psc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ProviderSetting.tenant_id"`)}
	}
	if _, ok := psc.mutation.IsEncrypted(); !ok {
		return &ValidationError{Name: "is_encrypted", err: errors.New(`ent: missing required field "ProviderSetting.is_encrypted"`)}
	}
	if _, ok := psc.mutation.IsPlatform(); !ok {
		return &ValidationError{Name: "is_platform", err: errors.New(`ent: missing required field "ProviderSetting.is_platform"`)}
	}
	if _, ok := psc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "ProviderSetting.is_active"`)}
	}
	return nil
}

func (psc *ProviderSettingCreate) sqlSave(ctx context.Context) (*ProviderSetting, error) {
	if err := psc.check(); err != nil {
		return nil, err
	}
	_node, _spec := psc.createSpec()
	if err := sqlgraph.CreateNode(ctx, psc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	psc.mutation.id = &_node.ID
	psc.mutation.done = true
	return _node, nil
}

func (psc *ProviderSettingCreate) createSpec() (*ProviderSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderSetting{config: psc.config}
		_spec = sqlgraph.NewCreateSpec(providersetting.Table, sqlgraph.NewFieldSpec(providersetting.FieldID, field.TypeInt))
	)
	if value, ok := psc.mutation.TenantID(); ok {
		_spec.SetField(providersetting.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := psc.mutation.Channel(); ok {
		_spec.SetField(providersetting.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := psc.mutation.Provider(); ok {
		_spec.SetField(providersetting.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := psc.mutation.ProviderType(); ok {
		_spec.SetField(providersetting.FieldProviderType, field.TypeString, value)
		_node.ProviderType = value
	}
	if value, ok := psc.mutation.ProviderName(); ok {
		_spec.SetField(providersetting.FieldProviderName, field.TypeString, value)
		_node.ProviderName = value
	}
	if value, ok := psc.mutation.Key(); ok {
		_spec.SetField(providersetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := psc.mutation.Value(); ok {
		_spec.SetField(providersetting.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := psc.mutation.Description(); ok {
		_spec.SetField(providersetting.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := psc.mutation.IsEncrypted(); ok {
		_spec.SetField(providersetting.FieldIsEncrypted, field.TypeBool, value)
		_node.IsEncrypted = value
	}
	if value, ok := psc.mutation.IsPlatform(); ok {
		_spec.SetField(providersetting.FieldIsPlatform, field.TypeBool, value)
		_node.IsPlatform = value
	}
	if value, ok := psc.mutation.IsActive(); ok {
		_spec.SetField(providersetting.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := psc.mutation.Status(); ok {
		_spec.SetField(providersetting.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	return _node, _spec
}

// ProviderSettingCreateBulk is the builder for creating many ProviderSetting entities in bulk.
type ProviderSettingCreateBulk struct {
	config
	err      error
	builders []*ProviderSettingCreate
}

// Save creates the ProviderSetting entities in the database.
func (pscb *ProviderSettingCreateBulk) Save(ctx context.Context) ([]*ProviderSetting, error) {
	if pscb.err != nil {
		return nil, pscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pscb.builders))
	nodes := make([]*ProviderSetting, len(pscb.builders))
	mutators := make([]Mutator, len(pscb.builders))
	for i := range pscb.builders {
		func(i int, root context.Context) {
			builder := pscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pscb *ProviderSettingCreateBulk) SaveX(ctx context.Context) []*ProviderSetting {
	v, err := pscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pscb *ProviderSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := pscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pscb *ProviderSettingCreateBulk) ExecX(ctx context.Context) {
	if err := pscb.Exec(ctx); err != nil {
		panic(err)
	}
}
