// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bengobox/notifications-api/internal/ent/credittransaction"
	"github.com/bengobox/notifications-api/internal/ent/deliverylog"
	"github.com/bengobox/notifications-api/internal/ent/notificationpermission"
	"github.com/bengobox/notifications-api/internal/ent/notificationrole"
	"github.com/bengobox/notifications-api/internal/ent/outboxevent"
	"github.com/bengobox/notifications-api/internal/ent/permission"
	"github.com/bengobox/notifications-api/internal/ent/platformbilling"
	"github.com/bengobox/notifications-api/internal/ent/providersetting"
	"github.com/bengobox/notifications-api/internal/ent/ratelimitconfig"
	"github.com/bengobox/notifications-api/internal/ent/role"
	"github.com/bengobox/notifications-api/internal/ent/schema"
	"github.com/bengobox/notifications-api/internal/ent/serviceconfig"
	"github.com/bengobox/notifications-api/internal/ent/tenant"
	"github.com/bengobox/notifications-api/internal/ent/tenantcredit"
	"github.com/bengobox/notifications-api/internal/ent/user"
	"github.com/bengobox/notifications-api/internal/ent/userroleassignment"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	credittransactionFields := schema.CreditTransaction{}.Fields()
	_ = credittransactionFields
	// credittransactionDescMetadata is the schema descriptor for metadata field.
	credittransactionDescMetadata := credittransactionFields[8].Descriptor()
	// credittransaction.DefaultMetadata holds the default value on creation for the metadata field.
	credittransaction.DefaultMetadata = credittransactionDescMetadata.Default.(map[string]interface{})
	// credittransactionDescCreatedAt is the schema descriptor for created_at field.
	credittransactionDescCreatedAt := credittransactionFields[9].Descriptor()
	// credittransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	credittransaction.DefaultCreatedAt = credittransactionDescCreatedAt.Default.(func() time.Time)
	// credittransactionDescID is the schema descriptor for id field.
	credittransactionDescID := credittransactionFields[0].Descriptor()
	// credittransaction.DefaultID holds the default value on creation for the id field.
	credittransaction.DefaultID = credittransactionDescID.Default.(func() uuid.UUID)
	deliverylogFields := schema.DeliveryLog{}.Fields()
	_ = deliverylogFields
	// deliverylogDescTenantID is the schema descriptor for tenant_id field.
	deliverylogDescTenantID := deliverylogFields[1].Descriptor()
	// deliverylog.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	deliverylog.TenantIDValidator = deliverylogDescTenantID.Validators[0].(func(string) error)
	// deliverylogDescTemplateID is the schema descriptor for template_id field.
	deliverylogDescTemplateID := deliverylogFields[2].Descriptor()
	// deliverylog.TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	deliverylog.TemplateIDValidator = deliverylogDescTemplateID.Validators[0].(func(string) error)
	// deliverylogDescChannel is the schema descriptor for channel field.
	deliverylogDescChannel := deliverylogFields[3].Descriptor()
	// deliverylog.ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	deliverylog.ChannelValidator = deliverylogDescChannel.Validators[0].(func(string) error)
	// deliverylogDescRecipient is the schema descriptor for recipient field.
	deliverylogDescRecipient := deliverylogFields[4].Descriptor()
	// deliverylog.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	deliverylog.RecipientValidator = deliverylogDescRecipient.Validators[0].(func(string) error)
	// deliverylogDescStatus is the schema descriptor for status field.
	deliverylogDescStatus := deliverylogFields[5].Descriptor()
	// deliverylog.DefaultStatus holds the default value on creation for the status field.
	deliverylog.DefaultStatus = deliverylogDescStatus.Default.(string)
	// deliverylogDescCreatedAt is the schema descriptor for created_at field.
	deliverylogDescCreatedAt := deliverylogFields[6].Descriptor()
	// deliverylog.DefaultCreatedAt holds the default value on creation for the created_at field.
	deliverylog.DefaultCreatedAt = deliverylogDescCreatedAt.Default.(func() time.Time)
	// deliverylogDescID is the schema descriptor for id field.
	deliverylogDescID := deliverylogFields[0].Descriptor()
	// deliverylog.DefaultID holds the default value on creation for the id field.
	deliverylog.DefaultID = deliverylogDescID.Default.(func() uuid.UUID)
	notificationpermissionFields := schema.NotificationPermission{}.Fields()
	_ = notificationpermissionFields
	// notificationpermissionDescPermissionCode is the schema descriptor for permission_code field.
	notificationpermissionDescPermissionCode := notificationpermissionFields[1].Descriptor()
	// notificationpermission.PermissionCodeValidator is a validator for the "permission_code" field. It is called by the builders before save.
	notificationpermission.PermissionCodeValidator = notificationpermissionDescPermissionCode.Validators[0].(func(string) error)
	// notificationpermissionDescName is the schema descriptor for name field.
	notificationpermissionDescName := notificationpermissionFields[2].Descriptor()
	// notificationpermission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	notificationpermission.NameValidator = notificationpermissionDescName.Validators[0].(func(string) error)
	// notificationpermissionDescModule is the schema descriptor for module field.
	notificationpermissionDescModule := notificationpermissionFields[3].Descriptor()
	// notificationpermission.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	notificationpermission.ModuleValidator = notificationpermissionDescModule.Validators[0].(func(string) error)
	// notificationpermissionDescAction is the schema descriptor for action field.
	notificationpermissionDescAction := notificationpermissionFields[4].Descriptor()
	// notificationpermission.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	notificationpermission.ActionValidator = notificationpermissionDescAction.Validators[0].(func(string) error)
	// notificationpermissionDescCreatedAt is the schema descriptor for created_at field.
	notificationpermissionDescCreatedAt := notificationpermissionFields[7].Descriptor()
	// notificationpermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	notificationpermission.DefaultCreatedAt = notificationpermissionDescCreatedAt.Default.(func() time.Time)
	// notificationpermissionDescID is the schema descriptor for id field.
	notificationpermissionDescID := notificationpermissionFields[0].Descriptor()
	// notificationpermission.DefaultID holds the default value on creation for the id field.
	notificationpermission.DefaultID = notificationpermissionDescID.Default.(func() uuid.UUID)
	notificationroleFields := schema.NotificationRole{}.Fields()
	_ = notificationroleFields
	// notificationroleDescRoleCode is the schema descriptor for role_code field.
	notificationroleDescRoleCode := notificationroleFields[2].Descriptor()
	// notificationrole.RoleCodeValidator is a validator for the "role_code" field. It is called by the builders before save.
	notificationrole.RoleCodeValidator = notificationroleDescRoleCode.Validators[0].(func(string) error)
	// notificationroleDescName is the schema descriptor for name field.
	notificationroleDescName := notificationroleFields[3].Descriptor()
	// notificationrole.NameValidator is a validator for the "name" field. It is called by the builders before save.
	notificationrole.NameValidator = notificationroleDescName.Validators[0].(func(string) error)
	// notificationroleDescIsSystemRole is the schema descriptor for is_system_role field.
	notificationroleDescIsSystemRole := notificationroleFields[5].Descriptor()
	// notificationrole.DefaultIsSystemRole holds the default value on creation for the is_system_role field.
	notificationrole.DefaultIsSystemRole = notificationroleDescIsSystemRole.Default.(bool)
	// notificationroleDescCreatedAt is the schema descriptor for created_at field.
	notificationroleDescCreatedAt := notificationroleFields[6].Descriptor()
	// notificationrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	notificationrole.DefaultCreatedAt = notificationroleDescCreatedAt.Default.(func() time.Time)
	// notificationroleDescUpdatedAt is the schema descriptor for updated_at field.
	notificationroleDescUpdatedAt := notificationroleFields[7].Descriptor()
	// notificationrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notificationrole.DefaultUpdatedAt = notificationroleDescUpdatedAt.Default.(func() time.Time)
	// notificationrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notificationrole.UpdateDefaultUpdatedAt = notificationroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationroleDescID is the schema descriptor for id field.
	notificationroleDescID := notificationroleFields[0].Descriptor()
	// notificationrole.DefaultID holds the default value on creation for the id field.
	notificationrole.DefaultID = notificationroleDescID.Default.(func() uuid.UUID)
	outboxeventFields := schema.OutboxEvent{}.Fields()
	_ = outboxeventFields
	// outboxeventDescAggregateType is the schema descriptor for aggregate_type field.
	outboxeventDescAggregateType := outboxeventFields[2].Descriptor()
	// outboxevent.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	outboxevent.AggregateTypeValidator = outboxeventDescAggregateType.Validators[0].(func(string) error)
	// outboxeventDescEventType is the schema descriptor for event_type field.
	outboxeventDescEventType := outboxeventFields[4].Descriptor()
	// outboxevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	outboxevent.EventTypeValidator = outboxeventDescEventType.Validators[0].(func(string) error)
	// outboxeventDescStatus is the schema descriptor for status field.
	outboxeventDescStatus := outboxeventFields[6].Descriptor()
	// outboxevent.DefaultStatus holds the default value on creation for the status field.
	outboxevent.DefaultStatus = outboxeventDescStatus.Default.(string)
	// outboxeventDescAttempts is the schema descriptor for attempts field.
	outboxeventDescAttempts := outboxeventFields[7].Descriptor()
	// outboxevent.DefaultAttempts holds the default value on creation for the attempts field.
	outboxevent.DefaultAttempts = outboxeventDescAttempts.Default.(int)
	// outboxeventDescCreatedAt is the schema descriptor for created_at field.
	outboxeventDescCreatedAt := outboxeventFields[11].Descriptor()
	// outboxevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxevent.DefaultCreatedAt = outboxeventDescCreatedAt.Default.(func() time.Time)
	// outboxeventDescID is the schema descriptor for id field.
	outboxeventDescID := outboxeventFields[0].Descriptor()
	// outboxevent.DefaultID holds the default value on creation for the id field.
	outboxevent.DefaultID = outboxeventDescID.Default.(func() uuid.UUID)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescName is the schema descriptor for name field.
	permissionDescName := permissionFields[1].Descriptor()
	// permission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permission.NameValidator = permissionDescName.Validators[0].(func(string) error)
	// permissionDescModule is the schema descriptor for module field.
	permissionDescModule := permissionFields[2].Descriptor()
	// permission.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	permission.ModuleValidator = permissionDescModule.Validators[0].(func(string) error)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[4].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionFields[5].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionFields[0].Descriptor()
	// permission.DefaultID holds the default value on creation for the id field.
	permission.DefaultID = permissionDescID.Default.(func() uuid.UUID)
	platformbillingFields := schema.PlatformBilling{}.Fields()
	_ = platformbillingFields
	// platformbillingDescCostPerSms is the schema descriptor for cost_per_sms field.
	platformbillingDescCostPerSms := platformbillingFields[1].Descriptor()
	// platformbilling.DefaultCostPerSms holds the default value on creation for the cost_per_sms field.
	platformbilling.DefaultCostPerSms = platformbillingDescCostPerSms.Default.(float64)
	// platformbillingDescCostPerWhatsapp is the schema descriptor for cost_per_whatsapp field.
	platformbillingDescCostPerWhatsapp := platformbillingFields[2].Descriptor()
	// platformbilling.DefaultCostPerWhatsapp holds the default value on creation for the cost_per_whatsapp field.
	platformbilling.DefaultCostPerWhatsapp = platformbillingDescCostPerWhatsapp.Default.(float64)
	// platformbillingDescMinTopupAmount is the schema descriptor for min_topup_amount field.
	platformbillingDescMinTopupAmount := platformbillingFields[3].Descriptor()
	// platformbilling.DefaultMinTopupAmount holds the default value on creation for the min_topup_amount field.
	platformbilling.DefaultMinTopupAmount = platformbillingDescMinTopupAmount.Default.(float64)
	// platformbillingDescUpdatedAt is the schema descriptor for updated_at field.
	platformbillingDescUpdatedAt := platformbillingFields[5].Descriptor()
	// platformbilling.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	platformbilling.DefaultUpdatedAt = platformbillingDescUpdatedAt.Default.(func() time.Time)
	// platformbilling.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	platformbilling.UpdateDefaultUpdatedAt = platformbillingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// platformbillingDescID is the schema descriptor for id field.
	platformbillingDescID := platformbillingFields[0].Descriptor()
	// platformbilling.DefaultID holds the default value on creation for the id field.
	platformbilling.DefaultID = platformbillingDescID.Default.(func() uuid.UUID)
	providersettingFields := schema.ProviderSetting{}.Fields()
	_ = providersettingFields
	// providersettingDescIsEncrypted is the schema descriptor for is_encrypted field.
	providersettingDescIsEncrypted := providersettingFields[8].Descriptor()
	// providersetting.DefaultIsEncrypted holds the default value on creation for the is_encrypted field.
	providersetting.DefaultIsEncrypted = providersettingDescIsEncrypted.Default.(bool)
	// providersettingDescIsPlatform is the schema descriptor for is_platform field.
	providersettingDescIsPlatform := providersettingFields[9].Descriptor()
	// providersetting.DefaultIsPlatform holds the default value on creation for the is_platform field.
	providersetting.DefaultIsPlatform = providersettingDescIsPlatform.Default.(bool)
	// providersettingDescIsPlatformManaged is the schema descriptor for is_platform_managed field.
	providersettingDescIsPlatformManaged := providersettingFields[10].Descriptor()
	// providersetting.DefaultIsPlatformManaged holds the default value on creation for the is_platform_managed field.
	providersetting.DefaultIsPlatformManaged = providersettingDescIsPlatformManaged.Default.(bool)
	// providersettingDescEnvironment is the schema descriptor for environment field.
	providersettingDescEnvironment := providersettingFields[11].Descriptor()
	// providersetting.DefaultEnvironment holds the default value on creation for the environment field.
	providersetting.DefaultEnvironment = providersettingDescEnvironment.Default.(string)
	// providersettingDescIsSecret is the schema descriptor for is_secret field.
	providersettingDescIsSecret := providersettingFields[12].Descriptor()
	// providersetting.DefaultIsSecret holds the default value on creation for the is_secret field.
	providersetting.DefaultIsSecret = providersettingDescIsSecret.Default.(bool)
	// providersettingDescIsActive is the schema descriptor for is_active field.
	providersettingDescIsActive := providersettingFields[13].Descriptor()
	// providersetting.DefaultIsActive holds the default value on creation for the is_active field.
	providersetting.DefaultIsActive = providersettingDescIsActive.Default.(bool)
	// providersettingDescStatus is the schema descriptor for status field.
	providersettingDescStatus := providersettingFields[14].Descriptor()
	// providersetting.DefaultStatus holds the default value on creation for the status field.
	providersetting.DefaultStatus = providersettingDescStatus.Default.(string)
	ratelimitconfigFields := schema.RateLimitConfig{}.Fields()
	_ = ratelimitconfigFields
	// ratelimitconfigDescServiceName is the schema descriptor for service_name field.
	ratelimitconfigDescServiceName := ratelimitconfigFields[1].Descriptor()
	// ratelimitconfig.ServiceNameValidator is a validator for the "service_name" field. It is called by the builders before save.
	ratelimitconfig.ServiceNameValidator = ratelimitconfigDescServiceName.Validators[0].(func(string) error)
	// ratelimitconfigDescKeyType is the schema descriptor for key_type field.
	ratelimitconfigDescKeyType := ratelimitconfigFields[2].Descriptor()
	// ratelimitconfig.KeyTypeValidator is a validator for the "key_type" field. It is called by the builders before save.
	ratelimitconfig.KeyTypeValidator = ratelimitconfigDescKeyType.Validators[0].(func(string) error)
	// ratelimitconfigDescEndpointPattern is the schema descriptor for endpoint_pattern field.
	ratelimitconfigDescEndpointPattern := ratelimitconfigFields[3].Descriptor()
	// ratelimitconfig.DefaultEndpointPattern holds the default value on creation for the endpoint_pattern field.
	ratelimitconfig.DefaultEndpointPattern = ratelimitconfigDescEndpointPattern.Default.(string)
	// ratelimitconfigDescRequestsPerWindow is the schema descriptor for requests_per_window field.
	ratelimitconfigDescRequestsPerWindow := ratelimitconfigFields[4].Descriptor()
	// ratelimitconfig.DefaultRequestsPerWindow holds the default value on creation for the requests_per_window field.
	ratelimitconfig.DefaultRequestsPerWindow = ratelimitconfigDescRequestsPerWindow.Default.(int)
	// ratelimitconfig.RequestsPerWindowValidator is a validator for the "requests_per_window" field. It is called by the builders before save.
	ratelimitconfig.RequestsPerWindowValidator = ratelimitconfigDescRequestsPerWindow.Validators[0].(func(int) error)
	// ratelimitconfigDescWindowSeconds is the schema descriptor for window_seconds field.
	ratelimitconfigDescWindowSeconds := ratelimitconfigFields[5].Descriptor()
	// ratelimitconfig.DefaultWindowSeconds holds the default value on creation for the window_seconds field.
	ratelimitconfig.DefaultWindowSeconds = ratelimitconfigDescWindowSeconds.Default.(int)
	// ratelimitconfig.WindowSecondsValidator is a validator for the "window_seconds" field. It is called by the builders before save.
	ratelimitconfig.WindowSecondsValidator = ratelimitconfigDescWindowSeconds.Validators[0].(func(int) error)
	// ratelimitconfigDescBurstMultiplier is the schema descriptor for burst_multiplier field.
	ratelimitconfigDescBurstMultiplier := ratelimitconfigFields[6].Descriptor()
	// ratelimitconfig.DefaultBurstMultiplier holds the default value on creation for the burst_multiplier field.
	ratelimitconfig.DefaultBurstMultiplier = ratelimitconfigDescBurstMultiplier.Default.(float64)
	// ratelimitconfigDescIsActive is the schema descriptor for is_active field.
	ratelimitconfigDescIsActive := ratelimitconfigFields[7].Descriptor()
	// ratelimitconfig.DefaultIsActive holds the default value on creation for the is_active field.
	ratelimitconfig.DefaultIsActive = ratelimitconfigDescIsActive.Default.(bool)
	// ratelimitconfigDescCreatedAt is the schema descriptor for created_at field.
	ratelimitconfigDescCreatedAt := ratelimitconfigFields[9].Descriptor()
	// ratelimitconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	ratelimitconfig.DefaultCreatedAt = ratelimitconfigDescCreatedAt.Default.(func() time.Time)
	// ratelimitconfigDescUpdatedAt is the schema descriptor for updated_at field.
	ratelimitconfigDescUpdatedAt := ratelimitconfigFields[10].Descriptor()
	// ratelimitconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ratelimitconfig.DefaultUpdatedAt = ratelimitconfigDescUpdatedAt.Default.(func() time.Time)
	// ratelimitconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ratelimitconfig.UpdateDefaultUpdatedAt = ratelimitconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ratelimitconfigDescID is the schema descriptor for id field.
	ratelimitconfigDescID := ratelimitconfigFields[0].Descriptor()
	// ratelimitconfig.DefaultID holds the default value on creation for the id field.
	ratelimitconfig.DefaultID = ratelimitconfigDescID.Default.(func() uuid.UUID)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescScope is the schema descriptor for scope field.
	roleDescScope := roleFields[3].Descriptor()
	// role.DefaultScope holds the default value on creation for the scope field.
	role.DefaultScope = roleDescScope.Default.(string)
	// roleDescSystemRole is the schema descriptor for system_role field.
	roleDescSystemRole := roleFields[4].Descriptor()
	// role.DefaultSystemRole holds the default value on creation for the system_role field.
	role.DefaultSystemRole = roleDescSystemRole.Default.(bool)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[5].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[6].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleFields[0].Descriptor()
	// role.IDValidator is a validator for the "id" field. It is called by the builders before save.
	role.IDValidator = roleDescID.Validators[0].(func(string) error)
	serviceconfigFields := schema.ServiceConfig{}.Fields()
	_ = serviceconfigFields
	// serviceconfigDescConfigKey is the schema descriptor for config_key field.
	serviceconfigDescConfigKey := serviceconfigFields[2].Descriptor()
	// serviceconfig.ConfigKeyValidator is a validator for the "config_key" field. It is called by the builders before save.
	serviceconfig.ConfigKeyValidator = serviceconfigDescConfigKey.Validators[0].(func(string) error)
	// serviceconfigDescConfigValue is the schema descriptor for config_value field.
	serviceconfigDescConfigValue := serviceconfigFields[3].Descriptor()
	// serviceconfig.ConfigValueValidator is a validator for the "config_value" field. It is called by the builders before save.
	serviceconfig.ConfigValueValidator = serviceconfigDescConfigValue.Validators[0].(func(string) error)
	// serviceconfigDescConfigType is the schema descriptor for config_type field.
	serviceconfigDescConfigType := serviceconfigFields[4].Descriptor()
	// serviceconfig.DefaultConfigType holds the default value on creation for the config_type field.
	serviceconfig.DefaultConfigType = serviceconfigDescConfigType.Default.(string)
	// serviceconfigDescIsSecret is the schema descriptor for is_secret field.
	serviceconfigDescIsSecret := serviceconfigFields[6].Descriptor()
	// serviceconfig.DefaultIsSecret holds the default value on creation for the is_secret field.
	serviceconfig.DefaultIsSecret = serviceconfigDescIsSecret.Default.(bool)
	// serviceconfigDescCreatedAt is the schema descriptor for created_at field.
	serviceconfigDescCreatedAt := serviceconfigFields[7].Descriptor()
	// serviceconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	serviceconfig.DefaultCreatedAt = serviceconfigDescCreatedAt.Default.(func() time.Time)
	// serviceconfigDescUpdatedAt is the schema descriptor for updated_at field.
	serviceconfigDescUpdatedAt := serviceconfigFields[8].Descriptor()
	// serviceconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	serviceconfig.DefaultUpdatedAt = serviceconfigDescUpdatedAt.Default.(func() time.Time)
	// serviceconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	serviceconfig.UpdateDefaultUpdatedAt = serviceconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// serviceconfigDescID is the schema descriptor for id field.
	serviceconfigDescID := serviceconfigFields[0].Descriptor()
	// serviceconfig.DefaultID holds the default value on creation for the id field.
	serviceconfig.DefaultID = serviceconfigDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[2].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantFields[3].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(string)
	// tenantDescCountry is the schema descriptor for country field.
	tenantDescCountry := tenantFields[8].Descriptor()
	// tenant.DefaultCountry holds the default value on creation for the country field.
	tenant.DefaultCountry = tenantDescCountry.Default.(string)
	// tenantDescTimezone is the schema descriptor for timezone field.
	tenantDescTimezone := tenantFields[9].Descriptor()
	// tenant.DefaultTimezone holds the default value on creation for the timezone field.
	tenant.DefaultTimezone = tenantDescTimezone.Default.(string)
	// tenantDescMetadata is the schema descriptor for metadata field.
	tenantDescMetadata := tenantFields[18].Descriptor()
	// tenant.DefaultMetadata holds the default value on creation for the metadata field.
	tenant.DefaultMetadata = tenantDescMetadata.Default.(map[string]interface{})
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[19].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[20].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	tenantcreditFields := schema.TenantCredit{}.Fields()
	_ = tenantcreditFields
	// tenantcreditDescBalance is the schema descriptor for balance field.
	tenantcreditDescBalance := tenantcreditFields[3].Descriptor()
	// tenantcredit.DefaultBalance holds the default value on creation for the balance field.
	tenantcredit.DefaultBalance = tenantcreditDescBalance.Default.(float64)
	// tenantcreditDescRate is the schema descriptor for rate field.
	tenantcreditDescRate := tenantcreditFields[4].Descriptor()
	// tenantcredit.DefaultRate holds the default value on creation for the rate field.
	tenantcredit.DefaultRate = tenantcreditDescRate.Default.(float64)
	// tenantcreditDescCreatedAt is the schema descriptor for created_at field.
	tenantcreditDescCreatedAt := tenantcreditFields[5].Descriptor()
	// tenantcredit.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantcredit.DefaultCreatedAt = tenantcreditDescCreatedAt.Default.(func() time.Time)
	// tenantcreditDescUpdatedAt is the schema descriptor for updated_at field.
	tenantcreditDescUpdatedAt := tenantcreditFields[6].Descriptor()
	// tenantcredit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantcredit.DefaultUpdatedAt = tenantcreditDescUpdatedAt.Default.(func() time.Time)
	// tenantcredit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantcredit.UpdateDefaultUpdatedAt = tenantcreditDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantcreditDescID is the schema descriptor for id field.
	tenantcreditDescID := tenantcreditFields[0].Descriptor()
	// tenantcredit.DefaultID holds the default value on creation for the id field.
	tenantcredit.DefaultID = tenantcreditDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescSyncStatus is the schema descriptor for sync_status field.
	userDescSyncStatus := userFields[4].Descriptor()
	// user.DefaultSyncStatus holds the default value on creation for the sync_status field.
	user.DefaultSyncStatus = userDescSyncStatus.Default.(string)
	// userDescFullName is the schema descriptor for full_name field.
	userDescFullName := userFields[6].Descriptor()
	// user.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	user.FullNameValidator = userDescFullName.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[8].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescLocale is the schema descriptor for locale field.
	userDescLocale := userFields[10].Descriptor()
	// user.DefaultLocale holds the default value on creation for the locale field.
	user.DefaultLocale = userDescLocale.Default.(string)
	// userDescMetadata is the schema descriptor for metadata field.
	userDescMetadata := userFields[12].Descriptor()
	// user.DefaultMetadata holds the default value on creation for the metadata field.
	user.DefaultMetadata = userDescMetadata.Default.(map[string]interface{})
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[13].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[14].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	userroleassignmentFields := schema.UserRoleAssignment{}.Fields()
	_ = userroleassignmentFields
	// userroleassignmentDescAssignedAt is the schema descriptor for assigned_at field.
	userroleassignmentDescAssignedAt := userroleassignmentFields[5].Descriptor()
	// userroleassignment.DefaultAssignedAt holds the default value on creation for the assigned_at field.
	userroleassignment.DefaultAssignedAt = userroleassignmentDescAssignedAt.Default.(func() time.Time)
	// userroleassignmentDescID is the schema descriptor for id field.
	userroleassignmentDescID := userroleassignmentFields[0].Descriptor()
	// userroleassignment.DefaultID holds the default value on creation for the id field.
	userroleassignment.DefaultID = userroleassignmentDescID.Default.(func() uuid.UUID)
}
