// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/predicate"
	"github.com/bengobox/notifications-api/internal/ent/tenantcredit"
)

// TenantCreditDelete is the builder for deleting a TenantCredit entity.
type TenantCreditDelete struct {
	config
	hooks    []Hook
	mutation *TenantCreditMutation
}

// Where appends a list predicates to the TenantCreditDelete builder.
func (tcd *TenantCreditDelete) Where(ps ...predicate.TenantCredit) *TenantCreditDelete {
	tcd.mutation.Where(ps...)
	return tcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tcd *TenantCreditDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tcd.sqlExec, tcd.mutation, tcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tcd *TenantCreditDelete) ExecX(ctx context.Context) int {
	n, err := tcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tcd *TenantCreditDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenantcredit.Table, sqlgraph.NewFieldSpec(tenantcredit.FieldID, field.TypeUUID))
	if ps := tcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tcd.mutation.done = true
	return affected, err
}

// TenantCreditDeleteOne is the builder for deleting a single TenantCredit entity.
type TenantCreditDeleteOne struct {
	tcd *TenantCreditDelete
}

// Where appends a list predicates to the TenantCreditDelete builder.
func (tcdo *TenantCreditDeleteOne) Where(ps ...predicate.TenantCredit) *TenantCreditDeleteOne {
	tcdo.tcd.mutation.Where(ps...)
	return tcdo
}

// Exec executes the deletion query.
func (tcdo *TenantCreditDeleteOne) Exec(ctx context.Context) error {
	n, err := tcdo.tcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenantcredit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tcdo *TenantCreditDeleteOne) ExecX(ctx context.Context) {
	if err := tcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
