// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-app/internal/ent/tenantbranding"
)

// TenantBrandingCreate is the builder for creating a TenantBranding entity.
type TenantBrandingCreate struct {
	config
	mutation *TenantBrandingMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (tbc *TenantBrandingCreate) SetTenantID(s string) *TenantBrandingCreate {
	tbc.mutation.SetTenantID(s)
	return tbc
}

// SetLogoURL sets the "logo_url" field.
func (tbc *TenantBrandingCreate) SetLogoURL(s string) *TenantBrandingCreate {
	tbc.mutation.SetLogoURL(s)
	return tbc
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (tbc *TenantBrandingCreate) SetNillableLogoURL(s *string) *TenantBrandingCreate {
	if s != nil {
		tbc.SetLogoURL(*s)
	}
	return tbc
}

// SetPrimaryColor sets the "primary_color" field.
func (tbc *TenantBrandingCreate) SetPrimaryColor(s string) *TenantBrandingCreate {
	tbc.mutation.SetPrimaryColor(s)
	return tbc
}

// SetNillablePrimaryColor sets the "primary_color" field if the given value is not nil.
func (tbc *TenantBrandingCreate) SetNillablePrimaryColor(s *string) *TenantBrandingCreate {
	if s != nil {
		tbc.SetPrimaryColor(*s)
	}
	return tbc
}

// SetSecondaryColor sets the "secondary_color" field.
func (tbc *TenantBrandingCreate) SetSecondaryColor(s string) *TenantBrandingCreate {
	tbc.mutation.SetSecondaryColor(s)
	return tbc
}

// SetNillableSecondaryColor sets the "secondary_color" field if the given value is not nil.
func (tbc *TenantBrandingCreate) SetNillableSecondaryColor(s *string) *TenantBrandingCreate {
	if s != nil {
		tbc.SetSecondaryColor(*s)
	}
	return tbc
}

// SetFontFamily sets the "font_family" field.
func (tbc *TenantBrandingCreate) SetFontFamily(s string) *TenantBrandingCreate {
	tbc.mutation.SetFontFamily(s)
	return tbc
}

// SetNillableFontFamily sets the "font_family" field if the given value is not nil.
func (tbc *TenantBrandingCreate) SetNillableFontFamily(s *string) *TenantBrandingCreate {
	if s != nil {
		tbc.SetFontFamily(*s)
	}
	return tbc
}

// SetCustomCSS sets the "custom_css" field.
func (tbc *TenantBrandingCreate) SetCustomCSS(s string) *TenantBrandingCreate {
	tbc.mutation.SetCustomCSS(s)
	return tbc
}

// SetNillableCustomCSS sets the "custom_css" field if the given value is not nil.
func (tbc *TenantBrandingCreate) SetNillableCustomCSS(s *string) *TenantBrandingCreate {
	if s != nil {
		tbc.SetCustomCSS(*s)
	}
	return tbc
}

// SetMetadata sets the "metadata" field.
func (tbc *TenantBrandingCreate) SetMetadata(m map[string]interface{}) *TenantBrandingCreate {
	tbc.mutation.SetMetadata(m)
	return tbc
}

// Mutation returns the TenantBrandingMutation object of the builder.
func (tbc *TenantBrandingCreate) Mutation() *TenantBrandingMutation {
	return tbc.mutation
}

// Save creates the TenantBranding in the database.
func (tbc *TenantBrandingCreate) Save(ctx context.Context) (*TenantBranding, error) {
	return withHooks(ctx, tbc.sqlSave, tbc.mutation, tbc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tbc *TenantBrandingCreate) SaveX(ctx context.Context) *TenantBranding {
	v, err := tbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tbc *TenantBrandingCreate) Exec(ctx context.Context) error {
	_, err := tbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tbc *TenantBrandingCreate) ExecX(ctx context.Context) {
	if err := tbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tbc *TenantBrandingCreate) check() error {
	if _, ok := tbc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenantBranding.tenant_id"`)}
	}
	return nil
}

func (tbc *TenantBrandingCreate) sqlSave(ctx context.Context) (*TenantBranding, error) {
	if err := tbc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tbc.mutation.id = &_node.ID
	tbc.mutation.done = true
	return _node, nil
}

func (tbc *TenantBrandingCreate) createSpec() (*TenantBranding, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantBranding{config: tbc.config}
		_spec = sqlgraph.NewCreateSpec(tenantbranding.Table, sqlgraph.NewFieldSpec(tenantbranding.FieldID, field.TypeInt))
	)
	if value, ok := tbc.mutation.TenantID(); ok {
		_spec.SetField(tenantbranding.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := tbc.mutation.LogoURL(); ok {
		_spec.SetField(tenantbranding.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = value
	}
	if value, ok := tbc.mutation.PrimaryColor(); ok {
		_spec.SetField(tenantbranding.FieldPrimaryColor, field.TypeString, value)
		_node.PrimaryColor = value
	}
	if value, ok := tbc.mutation.SecondaryColor(); ok {
		_spec.SetField(tenantbranding.FieldSecondaryColor, field.TypeString, value)
		_node.SecondaryColor = value
	}
	if value, ok := tbc.mutation.FontFamily(); ok {
		_spec.SetField(tenantbranding.FieldFontFamily, field.TypeString, value)
		_node.FontFamily = value
	}
	if value, ok := tbc.mutation.CustomCSS(); ok {
		_spec.SetField(tenantbranding.FieldCustomCSS, field.TypeString, value)
		_node.CustomCSS = value
	}
	if value, ok := tbc.mutation.Metadata(); ok {
		_spec.SetField(tenantbranding.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	return _node, _spec
}

// TenantBrandingCreateBulk is the builder for creating many TenantBranding entities in bulk.
type TenantBrandingCreateBulk struct {
	config
	err      error
	builders []*TenantBrandingCreate
}

// Save creates the TenantBranding entities in the database.
func (tbcb *TenantBrandingCreateBulk) Save(ctx context.Context) ([]*TenantBranding, error) {
	if tbcb.err != nil {
		return nil, tbcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tbcb.builders))
	nodes := make([]*TenantBranding, len(tbcb.builders))
	mutators := make([]Mutator, len(tbcb.builders))
	for i := range tbcb.builders {
		func(i int, root context.Context) {
			builder := tbcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantBrandingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tbcb *TenantBrandingCreateBulk) SaveX(ctx context.Context) []*TenantBranding {
	v, err := tbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tbcb *TenantBrandingCreateBulk) Exec(ctx context.Context) error {
	_, err := tbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tbcb *TenantBrandingCreateBulk) ExecX(ctx context.Context) {
	if err := tbcb.Exec(ctx); err != nil {
		panic(err)
	}
}
