// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-api/internal/ent/tenantcredit"
	"github.com/google/uuid"
)

// TenantCreditCreate is the builder for creating a TenantCredit entity.
type TenantCreditCreate struct {
	config
	mutation *TenantCreditMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (tcc *TenantCreditCreate) SetTenantID(u uuid.UUID) *TenantCreditCreate {
	tcc.mutation.SetTenantID(u)
	return tcc
}

// SetType sets the "type" field.
func (tcc *TenantCreditCreate) SetType(t tenantcredit.Type) *TenantCreditCreate {
	tcc.mutation.SetType(t)
	return tcc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tcc *TenantCreditCreate) SetNillableType(t *tenantcredit.Type) *TenantCreditCreate {
	if t != nil {
		tcc.SetType(*t)
	}
	return tcc
}

// SetBalance sets the "balance" field.
func (tcc *TenantCreditCreate) SetBalance(f float64) *TenantCreditCreate {
	tcc.mutation.SetBalance(f)
	return tcc
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (tcc *TenantCreditCreate) SetNillableBalance(f *float64) *TenantCreditCreate {
	if f != nil {
		tcc.SetBalance(*f)
	}
	return tcc
}

// SetRate sets the "rate" field.
func (tcc *TenantCreditCreate) SetRate(f float64) *TenantCreditCreate {
	tcc.mutation.SetRate(f)
	return tcc
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (tcc *TenantCreditCreate) SetNillableRate(f *float64) *TenantCreditCreate {
	if f != nil {
		tcc.SetRate(*f)
	}
	return tcc
}

// SetCreatedAt sets the "created_at" field.
func (tcc *TenantCreditCreate) SetCreatedAt(t time.Time) *TenantCreditCreate {
	tcc.mutation.SetCreatedAt(t)
	return tcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tcc *TenantCreditCreate) SetNillableCreatedAt(t *time.Time) *TenantCreditCreate {
	if t != nil {
		tcc.SetCreatedAt(*t)
	}
	return tcc
}

// SetUpdatedAt sets the "updated_at" field.
func (tcc *TenantCreditCreate) SetUpdatedAt(t time.Time) *TenantCreditCreate {
	tcc.mutation.SetUpdatedAt(t)
	return tcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tcc *TenantCreditCreate) SetNillableUpdatedAt(t *time.Time) *TenantCreditCreate {
	if t != nil {
		tcc.SetUpdatedAt(*t)
	}
	return tcc
}

// SetID sets the "id" field.
func (tcc *TenantCreditCreate) SetID(u uuid.UUID) *TenantCreditCreate {
	tcc.mutation.SetID(u)
	return tcc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tcc *TenantCreditCreate) SetNillableID(u *uuid.UUID) *TenantCreditCreate {
	if u != nil {
		tcc.SetID(*u)
	}
	return tcc
}

// Mutation returns the TenantCreditMutation object of the builder.
func (tcc *TenantCreditCreate) Mutation() *TenantCreditMutation {
	return tcc.mutation
}

// Save creates the TenantCredit in the database.
func (tcc *TenantCreditCreate) Save(ctx context.Context) (*TenantCredit, error) {
	tcc.defaults()
	return withHooks(ctx, tcc.sqlSave, tcc.mutation, tcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tcc *TenantCreditCreate) SaveX(ctx context.Context) *TenantCredit {
	v, err := tcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcc *TenantCreditCreate) Exec(ctx context.Context) error {
	_, err := tcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcc *TenantCreditCreate) ExecX(ctx context.Context) {
	if err := tcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tcc *TenantCreditCreate) defaults() {
	if _, ok := tcc.mutation.GetType(); !ok {
		v := tenantcredit.DefaultType
		tcc.mutation.SetType(v)
	}
	if _, ok := tcc.mutation.Balance(); !ok {
		v := tenantcredit.DefaultBalance
		tcc.mutation.SetBalance(v)
	}
	if _, ok := tcc.mutation.Rate(); !ok {
		v := tenantcredit.DefaultRate
		tcc.mutation.SetRate(v)
	}
	if _, ok := tcc.mutation.CreatedAt(); !ok {
		v := tenantcredit.DefaultCreatedAt()
		tcc.mutation.SetCreatedAt(v)
	}
	if _, ok := tcc.mutation.UpdatedAt(); !ok {
		v := tenantcredit.DefaultUpdatedAt()
		tcc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tcc.mutation.ID(); !ok {
		v := tenantcredit.DefaultID()
		tcc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tcc *TenantCreditCreate) check() error {
	if _, ok := tcc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenantCredit.tenant_id"`)}
	}
	if _, ok := tcc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "TenantCredit.type"`)}
	}
	if v, ok := tcc.mutation.GetType(); ok {
		if err := tenantcredit.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TenantCredit.type": %w`, err)}
		}
	}
	if _, ok := tcc.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "TenantCredit.balance"`)}
	}
	if _, ok := tcc.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "TenantCredit.rate"`)}
	}
	if _, ok := tcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantCredit.created_at"`)}
	}
	if _, ok := tcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TenantCredit.updated_at"`)}
	}
	return nil
}

func (tcc *TenantCreditCreate) sqlSave(ctx context.Context) (*TenantCredit, error) {
	if err := tcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tcc.mutation.id = &_node.ID
	tcc.mutation.done = true
	return _node, nil
}

func (tcc *TenantCreditCreate) createSpec() (*TenantCredit, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantCredit{config: tcc.config}
		_spec = sqlgraph.NewCreateSpec(tenantcredit.Table, sqlgraph.NewFieldSpec(tenantcredit.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = tcc.conflict
	if id, ok := tcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tcc.mutation.TenantID(); ok {
		_spec.SetField(tenantcredit.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := tcc.mutation.GetType(); ok {
		_spec.SetField(tenantcredit.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := tcc.mutation.Balance(); ok {
		_spec.SetField(tenantcredit.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := tcc.mutation.Rate(); ok {
		_spec.SetField(tenantcredit.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if value, ok := tcc.mutation.CreatedAt(); ok {
		_spec.SetField(tenantcredit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tcc.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantcredit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TenantCredit.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TenantCreditUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (tcc *TenantCreditCreate) OnConflict(opts ...sql.ConflictOption) *TenantCreditUpsertOne {
	tcc.conflict = opts
	return &TenantCreditUpsertOne{
		create: tcc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TenantCredit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tcc *TenantCreditCreate) OnConflictColumns(columns ...string) *TenantCreditUpsertOne {
	tcc.conflict = append(tcc.conflict, sql.ConflictColumns(columns...))
	return &TenantCreditUpsertOne{
		create: tcc,
	}
}

type (
	// TenantCreditUpsertOne is the builder for "upsert"-ing
	//  one TenantCredit node.
	TenantCreditUpsertOne struct {
		create *TenantCreditCreate
	}

	// TenantCreditUpsert is the "OnConflict" setter.
	TenantCreditUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *TenantCreditUpsert) SetTenantID(v uuid.UUID) *TenantCreditUpsert {
	u.Set(tenantcredit.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantCreditUpsert) UpdateTenantID() *TenantCreditUpsert {
	u.SetExcluded(tenantcredit.FieldTenantID)
	return u
}

// SetType sets the "type" field.
func (u *TenantCreditUpsert) SetType(v tenantcredit.Type) *TenantCreditUpsert {
	u.Set(tenantcredit.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TenantCreditUpsert) UpdateType() *TenantCreditUpsert {
	u.SetExcluded(tenantcredit.FieldType)
	return u
}

// SetBalance sets the "balance" field.
func (u *TenantCreditUpsert) SetBalance(v float64) *TenantCreditUpsert {
	u.Set(tenantcredit.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *TenantCreditUpsert) UpdateBalance() *TenantCreditUpsert {
	u.SetExcluded(tenantcredit.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *TenantCreditUpsert) AddBalance(v float64) *TenantCreditUpsert {
	u.Add(tenantcredit.FieldBalance, v)
	return u
}

// SetRate sets the "rate" field.
func (u *TenantCreditUpsert) SetRate(v float64) *TenantCreditUpsert {
	u.Set(tenantcredit.FieldRate, v)
	return u
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *TenantCreditUpsert) UpdateRate() *TenantCreditUpsert {
	u.SetExcluded(tenantcredit.FieldRate)
	return u
}

// AddRate adds v to the "rate" field.
func (u *TenantCreditUpsert) AddRate(v float64) *TenantCreditUpsert {
	u.Add(tenantcredit.FieldRate, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantCreditUpsert) SetUpdatedAt(v time.Time) *TenantCreditUpsert {
	u.Set(tenantcredit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantCreditUpsert) UpdateUpdatedAt() *TenantCreditUpsert {
	u.SetExcluded(tenantcredit.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TenantCredit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tenantcredit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TenantCreditUpsertOne) UpdateNewValues() *TenantCreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tenantcredit.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tenantcredit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TenantCredit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TenantCreditUpsertOne) Ignore() *TenantCreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TenantCreditUpsertOne) DoNothing() *TenantCreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TenantCreditCreate.OnConflict
// documentation for more info.
func (u *TenantCreditUpsertOne) Update(set func(*TenantCreditUpsert)) *TenantCreditUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TenantCreditUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantCreditUpsertOne) SetTenantID(v uuid.UUID) *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantCreditUpsertOne) UpdateTenantID() *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateTenantID()
	})
}

// SetType sets the "type" field.
func (u *TenantCreditUpsertOne) SetType(v tenantcredit.Type) *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TenantCreditUpsertOne) UpdateType() *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateType()
	})
}

// SetBalance sets the "balance" field.
func (u *TenantCreditUpsertOne) SetBalance(v float64) *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *TenantCreditUpsertOne) AddBalance(v float64) *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *TenantCreditUpsertOne) UpdateBalance() *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateBalance()
	})
}

// SetRate sets the "rate" field.
func (u *TenantCreditUpsertOne) SetRate(v float64) *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *TenantCreditUpsertOne) AddRate(v float64) *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *TenantCreditUpsertOne) UpdateRate() *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateRate()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantCreditUpsertOne) SetUpdatedAt(v time.Time) *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantCreditUpsertOne) UpdateUpdatedAt() *TenantCreditUpsertOne {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TenantCreditUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TenantCreditCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TenantCreditUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TenantCreditUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TenantCreditUpsertOne.ID is not supported by MySQL driver. Use TenantCreditUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TenantCreditUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TenantCreditCreateBulk is the builder for creating many TenantCredit entities in bulk.
type TenantCreditCreateBulk struct {
	config
	err      error
	builders []*TenantCreditCreate
	conflict []sql.ConflictOption
}

// Save creates the TenantCredit entities in the database.
func (tccb *TenantCreditCreateBulk) Save(ctx context.Context) ([]*TenantCredit, error) {
	if tccb.err != nil {
		return nil, tccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tccb.builders))
	nodes := make([]*TenantCredit, len(tccb.builders))
	mutators := make([]Mutator, len(tccb.builders))
	for i := range tccb.builders {
		func(i int, root context.Context) {
			builder := tccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantCreditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tccb *TenantCreditCreateBulk) SaveX(ctx context.Context) []*TenantCredit {
	v, err := tccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tccb *TenantCreditCreateBulk) Exec(ctx context.Context) error {
	_, err := tccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tccb *TenantCreditCreateBulk) ExecX(ctx context.Context) {
	if err := tccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TenantCredit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TenantCreditUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (tccb *TenantCreditCreateBulk) OnConflict(opts ...sql.ConflictOption) *TenantCreditUpsertBulk {
	tccb.conflict = opts
	return &TenantCreditUpsertBulk{
		create: tccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TenantCredit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tccb *TenantCreditCreateBulk) OnConflictColumns(columns ...string) *TenantCreditUpsertBulk {
	tccb.conflict = append(tccb.conflict, sql.ConflictColumns(columns...))
	return &TenantCreditUpsertBulk{
		create: tccb,
	}
}

// TenantCreditUpsertBulk is the builder for "upsert"-ing
// a bulk of TenantCredit nodes.
type TenantCreditUpsertBulk struct {
	create *TenantCreditCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TenantCredit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tenantcredit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TenantCreditUpsertBulk) UpdateNewValues() *TenantCreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tenantcredit.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tenantcredit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TenantCredit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TenantCreditUpsertBulk) Ignore() *TenantCreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TenantCreditUpsertBulk) DoNothing() *TenantCreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TenantCreditCreateBulk.OnConflict
// documentation for more info.
func (u *TenantCreditUpsertBulk) Update(set func(*TenantCreditUpsert)) *TenantCreditUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TenantCreditUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantCreditUpsertBulk) SetTenantID(v uuid.UUID) *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantCreditUpsertBulk) UpdateTenantID() *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateTenantID()
	})
}

// SetType sets the "type" field.
func (u *TenantCreditUpsertBulk) SetType(v tenantcredit.Type) *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TenantCreditUpsertBulk) UpdateType() *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateType()
	})
}

// SetBalance sets the "balance" field.
func (u *TenantCreditUpsertBulk) SetBalance(v float64) *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *TenantCreditUpsertBulk) AddBalance(v float64) *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *TenantCreditUpsertBulk) UpdateBalance() *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateBalance()
	})
}

// SetRate sets the "rate" field.
func (u *TenantCreditUpsertBulk) SetRate(v float64) *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *TenantCreditUpsertBulk) AddRate(v float64) *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *TenantCreditUpsertBulk) UpdateRate() *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateRate()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantCreditUpsertBulk) SetUpdatedAt(v time.Time) *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantCreditUpsertBulk) UpdateUpdatedAt() *TenantCreditUpsertBulk {
	return u.Update(func(s *TenantCreditUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TenantCreditUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TenantCreditCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TenantCreditCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TenantCreditUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
