// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/notifications-app/internal/ent/predicate"
	"github.com/bengobox/notifications-app/internal/ent/tenantbranding"
)

// TenantBrandingDelete is the builder for deleting a TenantBranding entity.
type TenantBrandingDelete struct {
	config
	hooks    []Hook
	mutation *TenantBrandingMutation
}

// Where appends a list predicates to the TenantBrandingDelete builder.
func (tbd *TenantBrandingDelete) Where(ps ...predicate.TenantBranding) *TenantBrandingDelete {
	tbd.mutation.Where(ps...)
	return tbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tbd *TenantBrandingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tbd.sqlExec, tbd.mutation, tbd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tbd *TenantBrandingDelete) ExecX(ctx context.Context) int {
	n, err := tbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tbd *TenantBrandingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenantbranding.Table, sqlgraph.NewFieldSpec(tenantbranding.FieldID, field.TypeInt))
	if ps := tbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tbd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tbd.mutation.done = true
	return affected, err
}

// TenantBrandingDeleteOne is the builder for deleting a single TenantBranding entity.
type TenantBrandingDeleteOne struct {
	tbd *TenantBrandingDelete
}

// Where appends a list predicates to the TenantBrandingDelete builder.
func (tbdo *TenantBrandingDeleteOne) Where(ps ...predicate.TenantBranding) *TenantBrandingDeleteOne {
	tbdo.tbd.mutation.Where(ps...)
	return tbdo
}

// Exec executes the deletion query.
func (tbdo *TenantBrandingDeleteOne) Exec(ctx context.Context) error {
	n, err := tbdo.tbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenantbranding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tbdo *TenantBrandingDeleteOne) ExecX(ctx context.Context) {
	if err := tbdo.Exec(ctx); err != nil {
		panic(err)
	}
}
