// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ProviderSetting is the predicate function for providersetting builders.
type ProviderSetting func(*sql.Selector)

// TenantBranding is the predicate function for tenantbranding builders.
type TenantBranding func(*sql.Selector)
